<style>
	.hidden {
		visibility: hidden;
	}

	input[type="checkbox"] {
		margin-left: 5px;
	}
</style>
<script type="text/javascript">
	$(function(){
		$( "#slider_per_hour" ).slider({
			range: true,
			min: 0,
			max: 25000,
			values: [ 0, 25000  ],
			slide: function( event, ui ) {
				$( "#amount_per_hour" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] + " руб");
		  }
		});

		$( "#amount_per_hour" ).val($( "#slider_per_hour" ).slider( "values", 0 ) +
		  " - " + $( "#slider_per_hour" ).slider( "values", 1 ) + " руб");

		$( "#slider_breast_size" ).slider({
			range: true,
			min: 0,
			max: 8,
			values: [ 0, 8 ],
			slide: function( event, ui ) {
				$( "#amount_breast_size" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ]);
		  }
		});

		$( "#amount_breast_size" ).val($( "#slider_breast_size" ).slider( "values", 0 ) +
		  " - " + $( "#slider_breast_size" ).slider( "values", 1 ));
	});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$('.add_review').click(function(){
			$('#hide_register_block').fadeIn();
				return false;
		})
	});
</script>
<aside id="sidebar">
	<?= $this->render('index/_user_admin.phtml') ?>
	<div class="sidebox">
		<div class="sidebox_header">
			<h3>Быстрый поиск</h3>
		</div>
		<div class="sidebox_content">
			<form action="#">
				<fieldset>
					<h4 class="red_side_title">Цена за час</h4>
					<div class="range_slider">
						<input type="text" id="amount_per_hour" class="grey_price"
							readonly />
						<div id="slider_per_hour"></div>
					</div>
					<h4 class="red_side_title">Размер груди</h4>
					<div class="range_slider">
						<input type="text" id="amount_breast_size" class="grey_price"
							readonly />
						<div id="slider_breast_size"></div>
					</div>
					<div class="get_all_search_box">
						<a href="#" class="all_search_label">Pасширенный поиск</a>
						<button class="button pink_button">
							<span class="search_icon"></span>Найти
						</button>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
	<div class="sidebox pink">
		<div class="sidebox_header">
			<h3>Фильтровать</h3>
		</div>
		<div class="sidebox_content filter_girl_min_height">
			<h5 class="category_header">Возраст</h5>
			<ul class="red_dot_list">
				<li><a href="/kategorii/molodye">"Молодые"</a> <span
					class="small_gray">(18-22)</span>
				</li>
				<li><a href="/kategorii/starye">"Старые"</a> <span
					class="small_gray">(23-29)</span>
				</li>
			</ul>
			<h5 class="category_header">Телосложение</h5>
			<ul class="red_dot_list">
				<li><a href="/kategorii/hudye">"Худые"</a>
				</li>
				<li><a href="/kategorii/tolstye">"Толстые"</a>
				</li>
			</ul>
			<h5 class="category_header">Внешность</h5>
			<ul class="red_dot_list">
				<li><a href="/kategorii/aziatki">Азиатки</a>
				</li>
				<li><a href="/kategorii/mulatki">Мулатки</a>
				</li>
				<li><a href="/kategorii/negrityanki">Негритянки</a>
				</li>
				<li><a href="/kategorii/uzbechki">Узбечечки</a>
				</li>
			</ul>
			<h5 class="category_header">Расценки</h5>
			<ul class="red_dot_list">
				<li><a href="/kategorii/deshevye">Дешевые</a>
				</li>
				<li><a href="/kategorii/elitnye">Элитные</a>
				</li>
			</ul>
			<h5 class="category_header">Место встречи</h5>
			<ul class="red_dot_list">
				<li><a href="/kategorii/vyezd-na-dom">Выезд на дом</a>
				</li>
				<li><a href="/kategorii/s-apartamentami">С апартаментами</a>
				</li>
			</ul>
			<h5 class="category_header">Анкеты</h5>
			<ul class="red_dot_list">
				<li><a href="#">Новые</a>
				</li>
				<li><a href="/?st=30-40">Проверенные</a>
				</li>
				<li><a href="/?v=1-0">С видео</a>
				</li>
			</ul>
			<div class="filter_girl_bg"></div>
		</div>
	</div>
	<div class="sidebox pink">
		<div class="sidebox_header">
			<h3>Услуги</h3>
		</div>
		<div class="sidebox_content servises_girl_min_height">
			<h5 class="category_header">Услуги интим</h5>
			<ul class="red_dot_list">
				<?php foreach($this->services as $part=>$srv) : ?>
				<?php array_shift($srv); ?>
				<?php foreach($srv as $num=>$val) : ?>
				<?php if ($part == 'intim' ) : ?>
				<li><?php echo $val ?>
				<?php endif ?>
				<?php endforeach ?>
				<?php endforeach ?>
			</ul>
			<h5 class="category_header">Услуги массажа</h5>
			<ul class="red_dot_list">
				<?php foreach($this->services as $part=>$srv) : ?>
				<?php array_shift($srv); ?>
				<?php foreach($srv as $num=>$val) : ?>
				<?php if ($part == 'mass' ) : ?>
				<li>
					<?php echo $val ?>
				</li>
				<?php endif ?>
				<?php endforeach ?>
				<?php endforeach ?>
			</ul>
			<div class="servises_girl_bg"></div>
		</div>
	</div>
	<ul class="see_in_mobile">
		<li>
			<div class="first_phone"></div> <span>Вы можете просматривать сайт на
				экране своего <a href="#">портативного компьютера</a>
		</span>
		</li>
	</ul>
</aside>
