<?
	$usettings = new Model_USettings();
		
	if ( $this->user_id ) {
		$res = $usettings->getConfig( $this->user_id, "show_user_cab" );
	}
	
	if ( $res === 'true' ) {
		$class = "right_user_cabinet_show";
	} else {
		$class = "right_user_cabinet_hide";
	}

?>
<div class="<?= $class ?>" >
	<div class="right_aside_title">Кабинет посетителя</div>
	
	<div class="user_cabinet_links">
		<a href="/index/postpone">Отложенные анкеты<?= $this->countPostpone( $this->user_id ) ?></a>
		<a href="/index/user-comments">Мои отзывы<?= $this->countNewComments( $this->user_id ) ?></a>
		<a href="/index/profile">Настройки профиля</a>
	</div>
	
	<span>Сообщения:</span>
	<div class="user_cabinet_links">
		<a href="/index/user-connect">Связь с администрацией</a>
		<a href="/index/user-messages">Мои сообщения
			<? if ( $count = $this->countNewMessages() ) { 
					echo "(+" . $count . ")"; 
			   } 
			?>
		</a>		
	</div>
	
	<span>Рекламодателю:</span>
	<div class="user_cabinet_links">
		<?
			if ( $this->user_id ) {
				$users = new Model_UsersTest();
				$flags = $users->getFlags( $this->user_id );
			} else {
				$flags = null;
			}
		?>
		<? if ( $flags == 2 ) : ?>
			<a href="/cabinet">Перейти в кабинет рекламодателя</a>
		<? elseif( $flags == 0 ) : ?>
			<a href="/cabinet">Разместить анкету</a>
		<? endif ?>		
	</div>
	
	<br />
	<div class="user_cabinet_links">
		<a href="javascript:void(0)" id="hide_user_cab">Свернуть</a>
	</div>
</div>
<script type="text/javascript">			
	<? if ( $this->user_id ) : ?>
		$("#hide_user_cab").click(function() {
			$.get("/remote/show-user-cabinet", { show : "false", user_id : <?= $this->user_id ?> }, function(){
				$(".right_user_cabinet_show").removeClass("right_user_cabinet_show").addClass("right_user_cabinet_hide");			
			});
		});	
	<? endif ?>					
</script>