<div class="user_cab_message">
	<div class="ribbon_title_bg">
		<h2>Анкета <a href="/anketa/<?= $this->name?>-<?= $this->ank_id ?>" target="_blank" >"<?= $this->name ?>"</a></h2>
	</div>
	<div class="user_cab_message_group">
		<label>
			<input type="checkbox" name="del_<?= $this->id ?>" >
			<?= rusdate( strtotime($this->time), 'j %MONTH% Y H:i' ); ?>
		</label>
	</div>
	<div class="user_cab_message_text">
		<p><?= $this->text ?></p>
	</div>
</div>