<? if ( !$this->auth ) : ?>
	<form class="root_girl_form" method="post" action="/auth">
    	<div class="root_girl_form_text">Отзывы могут оставлять только зарегистрированные пользователи!</div>
        <div class="root_girl_form_elem">
        	<input type="text" id="num_phone" name="username">
            <input type="password" id="num_phone" name="password">
            <input type="hidden" name="url" id="url">
            <button class="btn firstbut">Войти на сайт</button>
            <a href="/auth/registration" class="btn btn-link">Регистрация</a>
        </div>
    </form>
<? else: ?>
<h3>Оставить комментарий:</h3>
<form id="commform" class="cab_form" method="post">
	<div class="ca_top">
		<table>
			<tr>
				<th>Введите ваше имя:</th>
				<td><input name="name" /></td>
				<td rowspan="2">
					<img src="/captcha/<?=$this->captcha?>.png" id="captcha-image" />
					<img src="/img/captcha_refresh.png" id="captcha-refresh" onclick="captchaRefresh();" />
				</td>
			</tr>	
			<tr>
				<th>Введите код защиты:</th>
				<td><input type="text" name="captcha"></td>
			</tr>
		</table>
	</div>
	<div class="ca_bottom"><textarea name="text"></textarea></div>
	<br />
	<input id="captcha-id" type="hidden" name="id" value="<?=$this->captcha?>" />
	<input id="add_comment_button" class="button" type="submit" value="Отправить" />
</form>
<? endif; ?>