<div class="fix_width">
	<div id="main">
		<div id="content">
			<div class="main_title_block">
				<?php if ( !isset($this->search_by_phone) && !$this->search_by_phone) : ?>
				<h1>
					<? if(isset($this->info['title'])):?>
                   		<?=$this->textToView($this->info['title'])?>
               		<?elseif($_SERVER['REQUEST_URI'] == '/'):?>
                		<?=nl2br(stripslashes($this->meta['title']))?>
                	<? else:?>
                    	Проститутки Санкт-Петербурга, индивидуалки
               		<? endif; ?>
				</h1>
				<?php endif ?>
				<?php if ( !isset($this->search_by_phone) && !$this->search_by_phone && !$this->sections->getId(substr($_SERVER['REQUEST_URI'], 1)) ) : ?>
					<?php if ( count($this->ankets_new) > 0 ) : ?>
					<h2>новые анкеты</h2>
					<div class="new_ankets_block">
						<ul class="new_ankets">
							<?php foreach($this->ankets_new as $row): $i++;
								if ($i > 6) {break;}
								if(!empty($row['photolist'])){
									$photolist=unserialize($row['photolist']);
								if(isset($photolist['preview'])){$photo=$photolist[$photolist['preview']];}
									else{$photo=array_shift($photolist);}
								}else{
									$photo=false;
								}
							?>
							<li>
								<a href="/anketa/<?=urlencode($row['name_eng'])?>-<?=$row['id']?>" target="_blank">
									<div class="wrap_photo_new" style="background:url('<?php echo $this->url_user_ph. '/' . $row['user_id'] . '/tn_' . $photo ?>') no-repeat scroll center top transparent;"></div>
								</a>
								<!-- <div class="new_ribbon"></div> -->
								<div class="tooltip">
									<div class="tooltip_corner"></div>
									<div class="tooltip_content">
										<span class="tooltip_girl_name"><a href="/anketa/<?=urlencode($row['name_eng'])?>-<?=$row['id']?>" target="_blank"><?=$row['name']?></a>, <?= $row['age'] ?></span>
										<span class="tooltip_girl_place">Россия, <?= $this->city_text ?></span>
									</div>
								</div>
							</li>
							<?php endforeach ?>
						</ul>
						<a href="/ankety/novye" class="button all_list_btn">весь список</a>
					</div>
					<?php endif ?>
					<?php if ( $this->top_100 ) : ?>
						<div class="best_massage_preview_block">
						<h2>Рейтинг лучших анкет</h2>
						<ul class="best_massage_preview">
							<?php foreach($this->top_100 as $top):
								$j++;
								if(!empty($top['photolist'])){
									$photolist=unserialize($top['photolist']);
								if(isset($photolist['preview'])){$photo=$photolist[$photolist['preview']];}
									else{$photo=array_shift($photolist);}
								}else{
									$photo=false;
								}
							?>
							<div class="wrap_photo_review <?php if ( $j > 24 ) echo "hidden" ?>" style="background:url('<?php echo $this->url_user_ph. '/' . $top['user_id'] . '/tr_' . $photo ?>') no-repeat scroll center top transparent;"></div>
							<?php endforeach ?>
						</ul>
						<a href="#" class="button all_rate_btn">весь рейтинг</a>
						</div>
					<?php endif ?>
				<?php endif ?>
				<div class="pager_holder gray_pager_holder">
					<div class="pagination">
						<?php echo $this->paginationControl($this->ankets,'Sliding','shared/pagination_pub.phtml') ?>
					</div>
					<?php if ( !isset($this->search_by_phone) && !$this->search_by_phone) : ?>
						<ul class="categories_page">
							<li><a href="#">Фото без ретуши</a></li>
							<li><a href="#">Реальные индивидулаки</a></li>
							<li><a href="#">Анкеты с видео</a></li>
						</ul>
					<?php else : ?>
						<ul class="categories_page">
							<li>Результат поиска по параметрам: </li>
							<li>тел: <?php echo $this->filter['tel']?></li>
						</ul>
					<?php endif; ?>
				</div>
				<?php foreach($this->ankets as $row):
						$meta_tags=array('name', 'type', 'performer', 'city', 'metro', 'age', 'breast', 'height', 'weight');
						$meta_replace=array();
						foreach($meta_tags as $key){$meta_replace[$key]=$row[$key];}
						foreach($meta_tags as $key=>$value){$meta_tags[$key]='%'.strtoupper($value).'%';}
						$meta_img=str_replace($meta_tags,$meta_replace,$this->meta['ank_img_alt']);
						$meta_detail=str_replace($meta_tags,$meta_replace,$this->meta['ank_detail']);
						if(!empty($row['photolist'])){
							$photolist=unserialize($row['photolist']);
							if(isset($photolist['preview'])){$photo=$photolist[$photolist['preview']];}
							else{$photo=array_shift($photolist);}
						}else{
							$photo=false;
						}
				?>
				<div class="girl_card">
					<div class="main_info_photo_holder">
						<div class="girl_card_photo">
							<a href="/anketa/<?=urlencode($row['name_eng'])?>-<?=$row['id']?>" target="_blank">
								<img src="<?php echo $this->url_user_ph. '/' . $row['user_id'] . '/th_' . $photo ?>" width="185" height="280" alt="description">
							</a>
							<!-- <div class="without_retouch"></div> -->
						</div>
						<div class="girl_card_main_info">
							<h4 class="girl_card_title"><?php echo $row['name'] ?></h4>
							<span class="girl_card_price"><?php echo $row['price_1h_ap'] ? $row['price_1h_ap'] : '' ?><span>руб/час</span></span>
							<span class="grey_city"><?=$this->city_text?></span>
							<span class="grey_metro"><span class="grey_metro_icon"></span><?php echo $this->metro_list[$row['metro']] ?></span>
							<ul class="girl_card_info_list">
								<li><a href="/<?php echo getLink($row['age'],array(array(18,21),array(22,30),array(31,40),array(41, 99)),array('vozrast/junye','vozrast/molodye','vozrast/zrelye','vozrast/v-vozraste')); ?>">Возраст..............<?php echo $row['age'] ?></a></li>
								<li><a href="/<?php echo getLink($row['height'], array(array(1,165),array(166,175),array(175, 1000)),array('rost/malenkie','rost/sredego-rosta','rost/vysokie'));?>">Рост...................<?php echo $row['height'] ?></a></li>
								<li><a href="/<?php echo getLink($row['weight'],array(array(1,49),array(50,60),array(61,300)),array('ves/hudenkie', 'ves/strojnye', 'ves/polnenkie')) ?>">Вес....................<?php echo $row['weight'] ?></a></li>
								<li><a href="/<?php echo getLink($row['breast'],array(array(0,2),array(3,5),array(6,8)),array('razmer-grudi/s-malenkoj-grudiu','razmer-grudi/s-bolshoj-grudiu','razmer-grudi/s-ochen-bolshoj-grudiu'))?>">Грудь.................<?php echo $row['breast'] ?></a></li>
							</ul>
							<span class="contain_video"><?php if ( $row['videolist'] ) : ?><span class="contain_video_icon"></span>Есть видео<?php endif ?></span>
							<span class="photo_verified"><?php if ( $row['status']>20 ) : ?><span class="photo_verified_icon"></span>Фото проверено<?php endif ?></span>
							<span class="real_individual"><?php if ( $row['real'] ) : ?><span class="real_individual_icon"></span>Реальня индивидуалка<?php endif ?></span>
							<? if ( $row['priority'] && (date('Y-m-d', strtotime($row['timestamp'])) > date('Y-m-d', strtotime("- 2 week")) ) ) : ?>
								<div class="new_ribbon"></div>
							<? endif; ?>
						</div>
					</div>
					<div class="girl_card_another_info">
						<div class="girl_card_likes_holder">
							<div class=girl_card_likes_programms>
								<h5>Любимые программы:</h5>
								<?php 
									$this->row = $row;
									echo $this->render('_show-services.phtml');
								 ?>
							</div>
							<div class="girl_card_rating_block">
								<div class="girl_card_rating">
									<span class="common_girl_card_rating"><span class="white_star_icon"></span><?php echo $this->getRatioVoices($row['id']) ?></span>
									<ul class="rating_stars">
										<?php echo str_repeat("<li></li>", floor($this->getRatioVoices($row['id'])) ) ?>
									</ul>
									<span class="all_voices_text">Всего голосов: <?php echo $this->getCountVoices($row['id']) ?></span>
								</div>
								<div class="girl_card_revies">
									<span class="green_label">Отзывы пользователей</span>
									<ul class="voices_counter">
										<li><span class="good_voice"><?php echo $this->getPositiveVoices($row['id']) ?></span></li>
										<li><span class="voice"><?php echo $this->getNeutralVoices($row['id']) ?></span></li>
										<li><span class="bad_voice"><?php echo $this->getNegativeVoices($row['id']) ?></span></li>
									</ul>
								</div>
							</div>
						</div>
						<div class="girl_card_text_unpadding">
							<span><?=substr($row['about'], 0, 233)."..."?></span>
						</div>
					</div>
						<?php if ($row['score']) : ?>
							<span class="good_score good_score_in_preview"><span class="good_score_icon"></span>&nbsp;Рекомендуют</span>
						<?php endif ?>
						<a href="/anketa/<?=urlencode($row['name_eng'])?>-<?=$row['id']?>" target="_blank" class="button show_anket_btn">Посмотреть анкету</a>
				</div>
				<?php endforeach ?>
				<div class="pager_holder gray_pager_holder">
					<div class="pagination">
						<?php echo $this->paginationControl($this->ankets,'Sliding','shared/pagination_pub.phtml') ?>
					</div>
					<ul class="categories_page">
						<li><a href="#">Фото без ретуши</a></li>
						<li><a href="#">Реальные индивидулаки</a></li>
						<li><a href="#">Анкеты с видео</a></li>
					</ul>
				</div>
				<h2 class="pre_table_title">ФОРУМ О массажистКАХ Спб</h2>
				<table class="even_odd">
					<thead>
						<tr>
							<td>Тема</td>
							<td>Автор</td>
							<td>Ответов</td>
							<td>Создана</td>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
				<div class="clear">
					<a href="#" class="button btn_to_right">Перейти в форум</a>
				</div>
			</div>
		</div>
		<?=$this->render('index/_sidebar.phtml') ?>
	</div>
</div>
<script type="text/javascript">
	$(".all_rate_btn").click(function(e){
		e.preventDefault();		
		$(".hidden").each(function(){
			$(this).removeClass("hidden");
		});
	})
</script>