<div class="fix_width">
 	<div id="main">
 		<div id="content">
 			<? if ( is_null($this->paginator) ) : ?>
 				<div class="main_title_block">
 					<h1>У вас нет отложенных анкет</h1>
 				</div>
 			<?php  else : ?>
 				<div class="main_title_block">
 					<h1>Ваши отложенные анкеты</h1>
 				</div>
 				<?php if ($this->paginator->count() > 1) : ?>
 				<div class="pager_holder gray_pager_holder">
					<div class="pagination">
						<?php echo $this->paginationControl($this->paginator,'Sliding','shared/pagination_pub.phtml') ?>
					</div>
				</div>
				<?php endif ?>
				<?php foreach($this->paginator as $row):
						$meta_tags=array('name', 'type', 'performer', 'city', 'metro', 'age', 'breast', 'height', 'weight');
						$meta_replace=array();
						foreach($meta_tags as $key){$meta_replace[$key]=$row[$key];}
						foreach($meta_tags as $key=>$value){$meta_tags[$key]='%'.strtoupper($value).'%';}
						$meta_img=str_replace($meta_tags,$meta_replace,$this->meta['ank_img_alt']);
						$meta_detail=str_replace($meta_tags,$meta_replace,$this->meta['ank_detail']);
						if(!empty($row['photolist'])){
							$photolist=unserialize($row['photolist']);
							if(isset($photolist['preview'])){$photo=$photolist[$photolist['preview']];}
							else{$photo=array_shift($photolist);}
						}else{
							$photo=false;
						}
				?>
				<div class="girl_card girl_card_postpone">
					<div class="main_info_photo_holder">
						<div class="girl_card_photo">
							<a href="/anketa/<?=urlencode($row['name_eng'])?>-<?=$row['id']?>" target="_blank">
								<img src="<?php echo $this->url_user_ph. '/' . $row['user_id'] . '/th_' . $photo ?>" width="185" height="280" alt="description">
							</a>
							<!-- <div class="without_retouch"></div> -->
						</div>
						<div class="girl_card_main_info">
							<h4 class="girl_card_title"><?php echo $row['name'] ?></h4>
							<span class="girl_card_price"><?php echo $row['price_1h_ap'] ? $row['price_1h_ap'] : '' ?><span>руб/час</span></span>
							<span class="grey_metro"><span class="grey_metro_icon"></span><?php echo $this->metro_list[$row['metro']] ?></span>
							<ul class="girl_card_info_list gir_card_info_list_postpont">
								<li><a href="/<?php echo getLink($row['age'],array(array(18,21),array(22,30),array(31,40),array(41, 99)),array('vozrast/junye','vozrast/molodye','vozrast/zrelye','vozrast/v-vozraste')); ?>">Возраст..............<?php echo $row['age'] ?></a></li>
								<li><a href="/<?php echo getLink($row['height'], array(array(1,165),array(166,175),array(175, 1000)),array('rost/malenkie','rost/sredego-rosta','rost/vysokie'));?>">Рост...................<?php echo $row['height'] ?></a></li>
								<li><a href="/<?php echo getLink($row['weight'],array(array(1,49),array(50,60),array(61,300)),array('ves/hudenkie', 'ves/strojnye', 'ves/polnenkie')) ?>">Вес....................<?php echo $row['weight'] ?></a></li>
								<li><a href="/<?php echo getLink($row['breast'],array(array(0,2),array(3,5),array(6,8)),array('razmer-grudi/s-malenkoj-grudiu','razmer-grudi/s-bolshoj-grudiu','razmer-grudi/s-ochen-bolshoj-grudiu'))?>">Грудь.................<?php echo $row['breast'] ?></a></li>
							</ul>
							<span class="contain_video"><?php if ( $row['videolist'] ) : ?><span class="contain_video_icon"></span>Есть видео<?php endif ?></span>
							<span class="photo_verified"><?php if ( $row['status']>20 ) : ?><span class="photo_verified_icon"></span>Фото проверено<?php endif ?></span>
							<span class="real_individual"><?php if ( true ) : ?><span class="real_individual_icon"></span>Реальня индивидуалка<?php endif ?></span>	
							<div class="new_ribbon"></div>
						</div>
						<div class="postpone_del_ank">
							<a href="/index/del-postpone/id/<?= $row[id]?>">Удалить</a>
						</div>
					</div>
				</div>
				<?php endforeach ?>
				<?php if ($this->paginator->count() > 1) : ?>
				<div class="pager_holder gray_pager_holder pager_holder_postpone">
					<div class="pagination">
						<?php echo $this->paginationControl($this->ankets,'Sliding','shared/pagination_pub.phtml') ?>
					</div>
				</div>
				<?php endif; ?>
 			<?php endif ?>
 		</div>
 		<?= $this->render('index/_sidebar.phtml') ?>
 	</div>
</div>