 <style>
	.hidden {
		visibility: hidden;
	}
</style>
<script type="text/javascript">
	$(function(){
		$( "#slider_per_hour" ).slider({
			range: true,
			min: 0,
			max: 25000,
			values: [ 0, 25000  ],
			slide: function( event, ui ) {
				$( "#amount_per_hour" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] + " руб");
		  }
		});

		$( "#amount_per_hour" ).val($( "#slider_per_hour" ).slider( "values", 0 ) +
		  " - " + $( "#slider_per_hour" ).slider( "values", 1 ) + " руб");

		$( "#slider_breast_size" ).slider({
			range: true,
			min: 0,
			max: 8,
			values: [ 0, 8 ],
			slide: function( event, ui ) {
				$( "#amount_breast_size" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ]);
		  }
		});

		$( "#amount_breast_size" ).val($( "#slider_breast_size" ).slider( "values", 0 ) +
		  " - " + $( "#slider_breast_size" ).slider( "values", 1 ));
	});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$('.add_review').click(function(){
			$('#hide_register_block').fadeIn();
				return false;
		})
	});
</script>
 <div class="fix_width">
 	<div id="main">
 		<div id="content">
 			<? if ( is_null($this->paginator) ) : ?>
 				<div class="main_title_block">
 					<h1>У вас нет отложенных анкет</h1>
 				</div>
 			<?php  else : ?>
 				<div class="main_title_block">
 					<h1>Отложенные анкеты</h1>
 				</div>
 				<div class="pager_holder gray_pager_holder">
					<div class="pagination">
						<?php echo $this->paginationControl($this->paginator,'Sliding','shared/pagination_pub.phtml') ?>
					</div>
					<!-- 
					<ul class="categories_page">
						<li><a href="#">Фото без ретуши</a></li>
						<li><a href="#">Реальные индивидулаки</a></li>
						<li><a href="#">Анкеты с видео</a></li>
					</ul>
					-->
				</div>
				<?php foreach($this->paginator as $row): 
						$meta_tags=array('name', 'type', 'performer', 'city', 'metro', 'age', 'breast', 'height', 'weight');
						$meta_replace=array();
						foreach($meta_tags as $key){$meta_replace[$key]=$row[$key];}
						foreach($meta_tags as $key=>$value){$meta_tags[$key]='%'.strtoupper($value).'%';}
						$meta_img=str_replace($meta_tags,$meta_replace,$this->meta['ank_img_alt']);
						$meta_detail=str_replace($meta_tags,$meta_replace,$this->meta['ank_detail']);
						if(!empty($row['photolist'])){
							$photolist=unserialize($row['photolist']);
							if(isset($photolist['preview'])){$photo=$photolist[$photolist['preview']];}
							else{$photo=array_shift($photolist);}
						}else{
							$photo=false;
						}
				?>
				<div class="girl_card girl_card_postpone">
					<div class="main_info_photo_holder">
						<div class="girl_card_photo">
							<a href="/anketa/<?=$row['name_eng']?>-<?=$row['id']?>" target="_blank">
								<img src="<?php echo $this->url_user_ph. '/' . $row['user_id'] . '/th_' . $photo ?>" width="185" height="280" alt="description">
							</a>
							<!-- <div class="without_retouch"></div> -->
						</div>
						<div class="girl_card_main_info">
							<h4 class="girl_card_title"><?php echo $row['name'] ?></h4>
							<span class="girl_card_price"><?php echo $row['price_1h_ap'] ? $row['price_1h_ap'] : '' ?><span>руб/час</span></span>
							<span class="grey_metro"><span class="grey_metro_icon"></span><?php echo $this->metro_list[$row['metro']] ?></span>
							<ul class="girl_card_info_list gir_card_info_list_postpont">
								<li><a href="/<?php echo getLink($row['age'],array(array(18,21),array(22,30),array(31,40),array(41, 99)),array('vozrast/junye','vozrast/molodye','vozrast/zrelye','vozrast/v-vozraste')); ?>">Возраст..............<?php echo $row['age'] ?></a></li>
								<li><a href="/<?php echo getLink($row['height'], array(array(1,165),array(166,175),array(175, 1000)),array('rost/malenkie','rost/sredego-rosta','rost/vysokie'));?>">Рост...................<?php echo $row['height'] ?></a></li>
								<li><a href="/<?php echo getLink($row['weight'],array(array(1,49),array(50,60),array(61,300)),array('ves/hudenkie', 'ves/strojnye', 'ves/polnenkie')) ?>">Вес....................<?php echo $row['weight'] ?></a></li>
								<li><a href="/<?php echo getLink($row['breast'],array(array(0,2),array(3,5),array(6,8)),array('razmer-grudi/s-malenkoj-grudiu','razmer-grudi/s-bolshoj-grudiu','razmer-grudi/s-ochen-bolshoj-grudiu'))?>">Грудь.................<?php echo $row['breast'] ?></a></li>
							</ul>
							<span class="contain_video"><?php if ( $row['videolist'] ) : ?><span class="contain_video_icon"></span>Есть видео<?php endif ?></span>
							<span class="photo_verified"><?php if ( $row['status']>20 ) : ?><span class="photo_verified_icon"></span>Фото проверено<?php endif ?></span>
							<span class="real_individual"><?php if ( true ) : ?><span class="real_individual_icon"></span>Реальня индивидуалка<?php endif ?></span>
							<div style="text-align: right">
								<a href="/index/del-postpone/id/<?= $row[id]?>">Удалить</a>
							</div>
							<div class="new_ribbon"></div>
						</div>
					</div>
				</div>
				<?php endforeach ?>
				<div class="pager_holder gray_pager_holder pager_holder_postpone">
					<div class="pagination">
						<?php echo $this->paginationControl($this->ankets,'Sliding','shared/pagination_pub.phtml') ?>
					</div>
					<!-- 
						<ul class="categories_page">
							<li><a href="#">Фото без ретуши</a></li>
							<li><a href="#">Реальные индивидулаки</a></li>
							<li><a href="#">Анкеты с видео</a></li>
						</ul>
					-->
				</div>
 			<?php endif ?>
 		</div>
 		<aside id="sidebar">
			<?= $this->render('index/_user_admin.phtml') ?>
			<div class="sidebox">
				<div class="sidebox_header">
					<h3>Быстрый поиск</h3>
				</div>
				<div class="sidebox_content">
					<form action="#">
						<fieldset>
							<h4 class="red_side_title">Цена за час</h4>
							<div class="range_slider">
								<input type="text" id="amount_per_hour" class="grey_price" readonly />
								<div id="slider_per_hour"></div>
							</div>
							<h4 class="red_side_title">Размер груди</h4>
								<div class="range_slider">
									<input type="text" id="amount_breast_size" class="grey_price" readonly />
									<div id="slider_breast_size"></div>
								</div>
								<div class="get_all_search_box">
									<a href="#" class="all_search_label">Pасширенный поиск</a>
									<button class="button pink_button"><span class="search_icon"></span>Найти</button>
								</div>
						</fieldset>
					</form>
				</div>
			</div>
			<div class="sidebox pink">
				<div class="sidebox_header">
					<h3>Фильтровать</h3>
				</div>
				<div class="sidebox_content filter_girl_min_height">
					<h5 class="category_header">Возраст</h5>
					<ul class="red_dot_list">
						<li><a href="/kategorii/molodye">"Молодые"</a> <span class="small_gray">(18-22)</span></li>
						<li><a href="/kategorii/starye">"Старые"</a> <span class="small_gray">(23-29)</span></li>
					</ul>
					<h5 class="category_header">Телосложение</h5>
					<ul class="red_dot_list">
						<li><a href="/kategorii/hudye">"Худые"</a></li>
						<li><a href="/kategorii/tolstye">"Толстые"</a></li>
					</ul>
					<h5 class="category_header">Внешность</h5>
					<ul class="red_dot_list">
						<li><a href="/kategorii/aziatki">Азиатки</a></li>
						<li><a href="/kategorii/mulatki">Мулатки</a></li>
						<li><a href="/kategorii/negrityanki">Негритянки</a></li>
						<li><a href="/kategorii/uzbechki">Узбечечки</a></li>
					</ul>
					<h5 class="category_header">Расценки</h5>
					<ul class="red_dot_list">
						<li><a href="/kategorii/deshevye">Дешевые</a></li>
						<li><a href="/kategorii/elitnye">Элитные</a></li>
					</ul>
					<h5 class="category_header">Место встречи</h5>
					<ul class="red_dot_list">
						<li><a href="/kategorii/vyezd-na-dom">Выезд на дом</a></li>
						<li><a href="/kategorii/s-apartamentami">С апартаментами</a></li>
					</ul>
					<h5 class="category_header">Анкеты</h5>
					<ul class="red_dot_list">
						<li><a href="#">Новые</a></li>
						<li><a href="/?st=30-40">Проверенные</a></li>
						<li><a href="/?v=1-0">С видео</a></li>
					</ul>
					<div class="filter_girl_bg"></div>
				</div>
			</div>
			<div class="sidebox pink">
				<div class="sidebox_header">
					<h3>Услуги</h3>
				</div>
				<div class="sidebox_content servises_girl_min_height">
					<h5 class="category_header">Основные программы</h5>
					<ul class="red_dot_list">
						<?php foreach($this->services as $part=>$srv) : ?>
						    <?php array_shift($srv); ?>
							<?php foreach($srv as $num=>$val) : ?>
								<?php if ($part == 'main' ) : ?>
									<a href="/<?php echo $this->sections->getUriForServices('srv_' . $part . '&1<<' . $num) ? $this->sections->getUriForServices('srv_' . $part . '&1<<' . $num) : '#';?>">
										<li><?php echo $val ?></li>
									</a>
								<?php endif ?>
							<?php endforeach ?>
						<?php endforeach ?>
					</ul>
					<h5 class="category_header">Дополнительные программы</h5>
					<ul class="red_dot_list">
						<?php foreach($this->services as $part=>$srv) : ?>
						    <?php array_shift($srv); ?>
							<?php foreach($srv as $num=>$val) : ?>
								<?php if ($part == 'add' ) : ?>
									<a href="/<?php echo $this->sections->getUriForServices('srv_' . $part . '&1<<' . $num) ? $this->sections->getUriForServices('srv_' . $part . '&1<<' . $num) : '#';?>">
										<li><?php echo $val ?></li>
									</a>
								<?php endif ?>
							<?php endforeach ?>
						<?php endforeach ?>
					</ul>
					<div class="servises_girl_bg"></div>
				</div>
			</div>
			<div class="sidebox pink">
				<div class="sidebox_header">
					<h3><span class="white_metro_icon"></span>Станция метро</h3>
				</div>
				<div class="sidebox_content">
					<div class="left_sidebox_content">
					<h5 class="category_header">Район ЦАО</h5>
						<ul class="red_dot_list">
							<li><a href="#">Курская</a></li>
							<li><a href="#">Красные Ворота</a></li>
							<li><a href="#">Сухаревская</a></li>
							<li><a href="#">Чкаловская</a></li>
							<li><a href="#">Таганская</a></li>
						</ul>
					</div>
					<div class="right_sidebox_content">
					<h5 class="category_header">Район ЮЗАО</h5>
						<ul class="red_dot_list">
							<li><a href="#">Спортивная</a></li>
							<li><a href="#">Фрунзенская</a></li>
							<li><a href="#">Университет</a></li>
						</ul>
					</div>
				</div>
			</div>
			<ul class="see_in_mobile">
				<li>
					<div class="first_phone"></div>
					<span>Вы можете просматривать сайт на экране своего <a href="#">портативного компьютера</a></span>
				</li>
				<li>
					<div class="second_phone"></div>
					<span>Вы можете просматривать сайт на экране своего <a href="#">портативного компьютера</a></span>
				</li>
			</ul>
		</aside>
 	</div>
 </div>
 
 <!-- 
 <div class="row">
 	<div class="span10">
    	<ul class="nav nav-tabs bottom_nav_tabs">
        	<li class="<?=($this->menu_sub['active'] == 'default')?'active':''?>"><a href="/" class="bnt1">Все</a></li>
            <li class="<?=($this->menu_sub['active'] == 'st')?'active':''?>"><a href="?st=50-0" class="bnt2">Фото проверено</a></li>
            <li class="<?=($this->menu_sub['active'] == 'v')?'active':''?>"><a href="?v=1-0" class="bnt4">Анкеты с видео</a></li>
            <li class="<?=($this->menu_sub['active'] == 'rv')?'active':''?>"><a href="/?rv=1-0" class="bnt3">С отзывами</a></li>
        </ul>
    </div>
    <div class="row bg_line">
        <div class="span2">
            <?= $this->render('index/_filter_left.phtml')?>
            <?#= $this->render('index/_sections_list.phtml')?>
            <?#= $this->render('index/_banners_left.phtml')?>
            <?= $this->render('index/_articles_list.phtml')?>
            <div class="left_block_text">               
                <?if($_SERVER['REQUEST_URI'] == '/'):?>
                    <?=nl2br(stripslashes($this->meta['column_left']))?>
                <?endif;?>
				<? if(isset($this->info['text_left'])): ?>
                    <p class="word-wrap"><?=nl2br(stripslashes($this->info['text_left']))?></p>
                <? endif ?>
            </div>
        </div>
        <?if ( is_null($this->paginator) ): ?> 
        	<div class="span6">  
            	<div class="right_aside_title">У вас нет отложенных анкет</div>
            </div>
       	<? else: ?>
        	<div class="span6"> 
        		<div class="right_aside_title">Ваши отложенные анкеты</div>
        		<div class="wrap_girl">
       	        <?foreach($this->paginator as $row):?>
        			<?
        				if ( !empty($row['photolist']) ) {
        					$photolist=unserialize($row['photolist']);
        					if ( isset($photolist['preview']) ) {
        						$photo=$photolist[$photolist['preview']];
        					}
        					else{
        						$photo=array_shift($photolist);
        					}
        				} else {
        					$photo=false;
        				} 
        			?>
        			<div class="girl">
                    	<div class="girl_name" style="float: left;"><?= $row['name']?$row['name'] : '' ?></div>
                    	<div class="del_girl" style="float: right; margin-right: 10px;"><a href="/index/del-postpone/id/<?= $row[id]?>">Удалить</a></div>
                   		<div class="girl_addres" style="clear: both;">г. Санкт-Петербург, <?if(!empty($row['metro'])):?>м. <?=$this->metro_list[$row['metro']]?><?endif?></div>
                    	<div class="girl_phone" id="phone_<?=$row['id']?>">
                    		<?//= $row['phone'] ? $this->phoneFormat(array('phone'=>$row['phone'])) : '' ?>
                    		<script>
    							$.get("/remote/phone/n/<?=$row['id']?>", function(data){
       								$("#phone_<?=$row['id']?>").html(data); 
    							},"");      
							</script>
                   		</div>
                   		<div class="wrap_girl_info">
                            <div class="girl_foto">
                            	<a target="_blank" class="img" href="/anketa/<?=$row['name_eng']?>-<?=$row['id']?>" <?if(!empty($meta_img)):?>title="<?=$meta_img?>"<?endif?> onclick="addHistory(<?=$row['id']?>)" style="background:#fff url('<?= $this->url_user_ph. '/' . $row['user_id'] . '/th_' . $photo ?>') no-repeat center top;"></a>                            
                            </div>
                       		<div class="girl_info">
                            	<div class="girl_price">
                            		1 час: 
                            		<? if ( $row['price_1h_ap'] ) :?>
                            			<span>
                            				<?=number_format($row['price_1h_ap'], 0, ',', ' ');?>
                            			</span>
                            		<? endif; ?>
                            		<br>2 часа: 
                            		<? if ( $row['price_2h_ap'] ) :?>
                            			<span>
                            				<?=number_format($row['price_2h_ap'], 0, ',', ' ');?>
                            			</span>
                            		<? endif ?>
                            		<br>Ночь:
                            		<? if ( $row['price_n_ap'] ) :?>
                            			<span>
                            				<?=number_format($row['price_n_ap'], 0, ',', ' ');?>
                            			</span>
                            		<? endif ?>
                          	  	</div>
                            	<div class="girl_stats">
                                	<?if(!empty($row['age'])):?>Возраст: <?=$row['age']?><br /><?endif?>
                                	<?if(!empty($row['height']) || !empty($row['weight'])):?>
                                    	<?if(!empty($row['height'])):?>Рост: <?=$row['height']?><br /><?endif?>
                                    	<?if(!empty($row['weight'])):?>Вес: <?=$row['weight']?><br /><?endif?>
                                	<?endif?>
                                	<?if(!empty($row['breast']) || $row['breast']==0):?>Грудь: <?=$row['breast']?><br /><?endif?>
                                	<?if($row['videolist']):?><a>Есть видео</a><br /><?endif?>
                                	<?if($row['status']>50):?><span>Фото проверено</span><?endif?></div>
                            	<a target="_blank" class="btn" <?if(!empty($meta_detail)):?>title="<?=$meta_detail?>"<?endif?>href="/anketa/<?=$row['name_eng']?>-<?=$row['id']?>" onclick="addHistory(<?=$row['id']?>)">Подробнее &gt;&gt;</a>
                        	</div>
                    	</div>
                	</div>        			
        		<? endforeach; ?>
        		<div class="pagination pagination-centered pagin_girls">  
        			<?=$this->paginationControl($this->paginator,'Sliding','shared/pagination_pub.phtml')?>
        		</div> 
        	</div>
        </div>
        <? endif; ?>        
   		<div class="span2">
        	<?= $this->render('index/_user_admin.phtml') ?>
        	<?= $this->render('index/_filter_right.phtml')?>
        	<?#=$this->render('index/_banners_right.phtml')?>
        	<div class="right_block_text word-wrap">                    
        		<p class="word-wrap"><?=nl2br($this->textToView($this->info['text_right']))?></p>
        	</div>
       	</div>
    </div>
</div>
-->