<div class="row">
	<div class="span10">
    	<ul class="nav nav-tabs bottom_nav_tabs">
        	<li class="<?=($this->menu_sub['active'] == 'default')?'active':''?>"><a href="/" class="bnt1">Все</a></li>
            <li class="<?=($this->menu_sub['active'] == 'st')?'active':''?>"><a href="?st=50-0" class="bnt2">Фото проверено</a></li>
            <li class="<?=($this->menu_sub['active'] == 'v')?'active':''?>"><a href="?v=1-0" class="bnt4">Анкеты с видео</a></li>
            <li class="<?=($this->menu_sub['active'] == 'rv')?'active':''?>"><a href="/?rv=1-0" class="bnt3">С отзывами</a></li>
        </ul>
    </div>
</div>
<div class="row bg_line">
	<div class="span2">
    	<?= $this->render('index/_filter_left.phtml')?>
        <?#= $this->render('index/_sections_list.phtml')?>
        <?#= $this->render('index/_banners_left.phtml')?>
        <?= $this->render('index/_articles_list.phtml')?>
    	<div class="left_block_text">               
        	<?if($_SERVER['REQUEST_URI'] == '/'):?>
            	<?=nl2br(stripslashes($this->meta['column_left']))?>
            <?endif;?>
			<? if(isset($this->info['text_left'])): ?>
            	<p class="word-wrap"><?=nl2br(stripslashes($this->info['text_left']))?></p>
            <? endif ?>
        </div>
    </div>
    <div class="span6">
    	<div class="user_profile">
    		<div class="right_aside_title">Настройки профиля</div>
    		<div class="form-buttons">
				<a href="/index/profile?type=pass">Смена пароля</a>|<a href="/index/profile?type=mess">Уведомления</a>
			</div>
			<? if ( $this->form instanceof Form_EditPassForm ) :?>
				<div class="info">
					<span>Логин: <?= $this->login ?> E-mail: <?= $this->email ?></span>
				</div>
			<? elseif ( $this->form instanceof Form_EditUserMessForm ) : ?>
				<div class="info">
					<span>Включить уведомление на e-mail: <?= $this->email ?></span>
				</div>
			<? endif ?>
			<? if ( $this->message ) :?>
				<div class="<?= $this->color ?>">
					<span><?= $this->message ?></span>
				</div>
			<? endif; ?>
			<form id="<?= $this->form->getId() ?>" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
				<div class="form">
					<div class="form-left">
					<?=$this->form->getElement('balance')?>
					<?=$this->form->getElement('days_info')?>
        			<? foreach ($this->form as $element): ?>
        				<? if ( !preg_match('/submit|balance|days_info/', $element->getName() ) ) :?>
        					<?= $element ?>
        				<? endif ?>
  					<? endforeach; ?>
  					</div>  
  					<?= $this->form->getElement('submit') ?> 				 				
  				</div>
  			</form>	
  		</div>
    </div>
    <div class="span2">    	
        <?= $this->render('index/_user_admin.phtml') ?>           
        <?= $this->render('index/_filter_right.phtml')?>
        <?#=$this->render('index/_banners_right.phtml')?>
        <div class="right_block_text word-wrap">                    
        	<p class="word-wrap"><?=nl2br($this->textToView($this->info['text_right']))?></p>
        </div>
    </div>
</div>