<div class="fix_width">
	<div id="main">
		<div id="content">
			<div class="main_title_block">
				<h1>Мой профиль</h1>
			</div>
			<div class="pager_holder gray_pager_holder">
				<div class="pagination_big_text">
					<? if ( $this->form instanceof Form_EditPassForm ) :?>
						<span>Логин: <?= $this->login ?> E-mail: <?= $this->email ?></span>
					<? elseif ( $this->form instanceof Form_EditUserMessForm ) : ?>
						<span>Включить уведомление на e-mail: <?= $this->email ?></span>
					<? endif ?>
				</div>
				<ul class="categories_page">
					<li><a href="/index/profile?type=pass">Смена пароля</a></li>
					<li><a href="/index/profile?type=mess">Уведомления</a></li>
				</ul>
			</div>
			<? if ( $this->message ) :?>
				<?php if ( $this->success ) : ?>
					<div style="margin-left: 10px;">
						<span class="photo_verified"><?= $this->message ?></span>
					</div>
				<?php else : ?>
					<div style="margin-left: 10px;">
						<span class="real_individual"><?= $this->message ?></span>
					</div>
				<?php endif; ?>
			<? endif; ?>
			<? if ( $this->form instanceof Form_EditPassForm ) :?>
				<form id="change_password" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
					<div class="form">
						<div class="form-left">
							<div class="user_cabinet_form_wrap">
								<div>
									<span class="search_radius_labe">Старый пароль:</span><input type="password" name="old_pass" id="old_pass" value="">
								</div>
								<div>
									<span class="search_radius_labe">Новый пароль:</span><input type="password" name="new_pass" id="new_pass" value="">
								</div>
								<div>
									<span class="search_radius_labe">Новый пароль (еще раз):</span><input type="password" name="new_pass_repeat" id="new_pass_repeat" value="">
								</div>
  							</div>
  						</div>
  						<input class="button pink_button main_search_button" type="submit" name="submit" id="submit_pass" value="Сохранить">
  					</div>
  				</form>
			<? elseif ( $this->form instanceof Form_EditUserMessForm ) : ?>
				<form id="<?= $this->form->getId() ?>" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
					<div class="form">
						<div class="form-left">
							<div class="user_cabinet_form_wrap">
							<?=$this->form->getElement('balance')?>
								<?=$this->form->getElement('days_info')?>
        					<? foreach ($this->form as $element): ?>
        						<? if ( !preg_match('/submit|balance|days_info/', $element->getName() ) ) :?>
        							<?= $element ?>
        						<? endif ?>
  							<? endforeach; ?>
  							</div>
  							<input class="button pink_button main_search_button" type="submit" name="submit" id="submit" value="Сохранить">
  						</div>
  					</div>
  				</form>
			<? endif ?>
		</div>
		<?= $this->render('index/_sidebar.phtml') ?>
	</div>
</div>
<script type="text/javascript">
$("#submit_pass").click(function(event) {
	event.preventDefault();

	var $form = $('#change_password');

	/* remove old valid messages */
    $(".not_valid").each(function(){
		$(this).remove();
  	})

  	/* validation */
  	var isBreak = false;
  	if ( !$form.find( 'input[name="old_pass"]' ).val() ) {
    	input = $form.find( 'input[name="old_pass"]' );
    	input.after('<p class="not_valid">Заполните</p>');
    	isBreak = true;
  	}

  	if ( !$form.find( 'input[name="new_pass"]' ).val() ) {
  		input = $form.find( 'input[name="new_pass"]' );
  		input.after('<p class="not_valid">Заполните</p>');
    	isBreak = true;
  	}

  	if ( !$form.find( 'input[name="new_pass_repeat"]' ).val() ) {
  		input = $form.find( 'input[name="new_pass_repeat"]' );
  		input.after('<p class="not_valid">Заполните</p>');
    	isBreak = true;
  	}

  	if ( $form.find( 'input[name="new_pass"]' ).val() != $form.find('input[name="new_pass_repeat"]').val() ) {
  		input = $form.find( 'input[name="new_pass_repeat"]' );
  		input.after('<p class="not_valid">Пароли должны совпадать</p>');
    	isBreak = true;
  	}

  	if (isBreak) {
        return;
    } else {
    	$form.submit();
    }
});
</script>