<div class="fix_width">
	<div id="main">
		<div id="content">
			<div class="main_title_block">
				<?php if( isset( $this->info['title'] ) ): ?>
					<h1><?php echo $this->textToView($this->info['title']) ?></h1>
				<?else:?>
					<h1>Салоны Санкт-Петербурга, интим, массажные, бдсм</h1>
				<?endif;?>
			</div>
			<p><?php echo nl2br(stripslashes($this->info['text'])) ?></p>
			<div class="pager_holder">
				<div class="pagination">
					<?php echo $this->paginationControl($this->salons,'Sliding','shared/pagination_pub.phtml') ?>
				</div>
				<ul class="categories_page">
					<li <?php echo ($this->menu_sub['active'] == 'default') ? 'class="active"' : '' ?>><a href="/<?=$this->info['uri']?>">Все</a></li>
					<li <?php echo ($this->menu_sub['active'] == 'intim' ) ? 'class="active"' : '' ?>><a href="/<?=$this->info['uri']?>?intim=true" class="bnt2">Интим</a></li>
					<li <?php echo ($this->menu_sub['active'] == 'mass' ) ? 'class="active"' : '' ?>><a href="/<?=$this->info['uri']?>?mass=true" class="bnt4">Массажный</a></li>
					<li <?php echo ($this->menu_sub['active'] == 'bdsm' ) ? 'class="active"' : '' ?>><a href="/<?=$this->info['uri']?>?bdsm=true" class="bnt3">БДСМ</a></li>
				</ul>
			</div>
			<?php	foreach ( $this->salons as $row ) : ?>
			<?php 
					if(!empty($row['photolist'])){
						$photolist=unserialize($row['photolist']);
						if(isset($photolist['preview'])){
							$photo=$photolist[$photolist['preview']];
						}
						else{
							$photo=array_shift($photolist);
						}
					} else {
						$photo = false;
					}
			?>
			<div class="salon_card_holder">
				<h2>
					<?php echo strlen($row['name']) < 50 ? $row['name'] : substr($row['name'],0,100) . "..." ?>
				</h2>
				<div class="salon_card">
					<div class="salon_card_common_left">
						<div class="salon_card_photo">
							<img src="<?=$this->url_user_ph.'/'.$row['user_id'].'/th_'.$photo?>" width="332" height="226">
						</div>
						<div class="salon_card_main_info">
							<h4 class="salon_card_title"><?php echo $this->types_of_salon[$row['type']] ?></h4>
							<span class="salon_card_price"><?php echo $row['price_1h_ap'] ?><span>руб/час</span></span>
							<span class="grey_metro"><span class="grey_metro_icon"></span><?php $metro = explode(";", $row['metro']); echo $this->metro_list[$metro[0]]; ?></span>
							<ul class="salon_card_info_list">
								<li>Девушек...<?php echo $row['girl_number'] ?></li>
								<li>Комнат.....<?php echo $row['room_number'] ?></li>
							</ul>
							<?php if ( $row['videolist'] ) : ?>
								<span class="contain_video"><span class="contain_video_icon"></span>Есть видео</span>
							<?php endif; ?>
						</div>
						<div class="salon_card_text_desc">
							<span><?php echo $row['about'] ?></span>
						</div>
					</div>
					<div class="salon_card_another_info">
						<div class="salon_card_rating_block">
							<div class="salon_card_rating">
								<span class="common_salon_card_rating"><span class="white_star_icon"></span>8.5</span>
								<ul class="rating_stars">
									<li></li>
									<li></li>
									<li></li>
									<li></li>
								</ul>
								<span class="all_voices_text">Всего голосов: 837</span>
							</div>
							<div class="salon_card_revies">
								<span class="green_label">Отзывы пользователей</span>
								<ul class="voices_counter">
									<li><span class="good_voice">+188</span></li>
									<li><span class="voice">1</span></li>
									<li><span class="bad_voice">-0</span></li>
								</ul>
							</div>
						</div>
						<h5>Основные программы:</h5>
						<?php 
							$this->row = $row;
							echo $this->render('_show-services-salon.phtml')
						?>
						<h5 class="common_programs">Дополнительно:</h5>
						<?php 
							$this->row = $row;
							echo $this->render('_show-services-salon-dop.phtml')
						?>
						<div class="salon_card_text_desc_holder">
							<a target="_blank" href="/salon/<?=$row['name_eng']?>-<?=$row['id']?>" class="button show _salon_btn">Посмотреть салон</a>
						</div>
					</div>
				</div>
			</div>
			<?php
				endforeach;
			?>
		</div>
		<?= $this->render('index/_sidebar_salons.phtml') ?>
	</div>
</div>