<div class="fix_width">
	<div id="main">
		<div id="content">
			<? if ( $this->message ) :?>
				<div class="<?= $this->color ?>">
					<span><?= $this->message ?></span>
				</div>
			<? endif; ?>
			<? if ( $this->form ) : ?>
				<form id="send_answer" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>"  <?= $this->get ?> enctype="multipart/form-data">
					<div class="form">
						<div class="form-left show_message_element">
							<div class="">
								<span><?= $this->from ?></span>
							</div>
							<div class="subject show_message_element">
								<span><?=$this->subject?></span>&nbsp;(<?= rusdate(strtotime($this->timestamp), "j %MONTH% Y H:i") ?>)
							</div>
							<div class="body show_message_element">
								<label>Текст сообщения:</label>
								<textarea name="body"><?php echo $this->body ?></textarea>
							</div>
							<div class="file show_message_element">
								Прикрепленный файл:
								<a class="black_link" href="/user_messages_photos/<?= $this->file ?>" ><?= $this->file ?></a>
							</div>
							<br/>
							Ответ:
							<div class="body show_message_element">
								<label>Текст ответного сообщения:</label>
								<textarea name="answer"></textarea>
							</div>
							<div class="show_message_element">
								<span class="search_radius_labe">Прикрепить фото:</span>
								<input type="file" name="upload" id="upload">
							</div>
							<input class="button pink_button main_search_button_user_cabinet" type="submit" name="submit" id="submit" value="Ответить">
							<input class="button pink_button main_search_button_user_cabinet" name="create_message" type="button" id="create-message" value="Удалить">
						</div>
					</div>
				</form>
			<? else : ?>
				<div class="form">
					<div class="form-left show_message_element">
						<div class="">
							<span><?= $this->from ?></span>
						</div>
						<div class="subject show_message_element">
							<span><?=$this->subject?></span>&nbsp;(<?= rusdate(strtotime($this->timestamp), "j %MONTH% Y H:i") ?>)
						</div>
						<div class="body show_message_element">
							<label>Текст сообщения:</label>
							<textarea name="body">
								<?php echo $this->body ?>
							</textarea>
						</div>
						<div class="file show_message_element">
							Прикрепленный файл:
							<a class="black_link" href="/user_messages_photos/<?= $this->file ?>" ><?= $this->file ?></a>
						</div>
					</div>
				</div>
			<? endif; ?>
		</div>
		<?= $this->render('index/_sidebar.phtml') ?>
	</div>
</div>
<script type="text/javascript">
$("#submit").click(function(event) {
	var $form = $('#send_answer');

	/* remove old valid messages */
    $(".not_valid").each(function(){
		$(this).remove();
  	})

  	/* validation */
  	var isBreak = false;

  	if ( !$form.find( 'textarea[name="answer"]' ).val() ) {
    	input = $form.find( 'textarea[name="answer"]' );
    	input.after('<p class="not_valid">Это поле обязательно к заполнению.</p>');
    	isBreak = true;
  	}

  	if (isBreak) {
  		event.preventDefault();
    }
});
</script>