<div class="fix_width">
	<div id="main">
		<div id="content">
			<div class="main_title_block">
				<h1>Мои комментарии</h1>
			</div>
			<?php if ( $this->paginator->count() ) : ?>	
				<div class="pager_holder gray_pager_holder">
					<div class="pagination">
						<?php echo $this->paginationControl($this->paginator,'Sliding','shared/pagination_pub.phtml') ?>
					</div>
					<ul class="categories_page">
						<li>Выделить:</li>
						<li><a href="javascript:void(0)" class="choose_all">Все</a></li>
						<li><a href="javascript:void(0)" class="unchoose_all">Снять выделение</a></li>
						<li><a href="javascript:void(0)" class="del_all">Удалить отмеченные</a></li>
					</ul>
				</div>
    			<div class="wrapper_user_messages_form">
    				<form action="/index/user-comments" method="post" id="user_messages_form">
    				<?
    					if ( $this->paginator->count() > 0 ) {
    						echo $this->partialLoop( 'index/comments-row.phtml', $this->paginator );
    					}
    				?>
    				</form>
    			</div>
    			<div class="pager_holder gray_pager_holder">
					<div class="pagination">
						<?php echo $this->paginationControl($this->paginator,'Sliding','shared/pagination_pub.phtml') ?>
					</div>
					<ul class="categories_page">
						<li>Выделить:</li>
						<li><a href="javascript:void(0)" class="choose_all">Все</a></li>
						<li><a href="javascript:void(0)" class="unchoose_all">Снять выделение</a></li>
						<li><a href="javascript:void(0)" class="del_all">Удалить отмеченные</a></li>
					</ul>
				</div>
       		<?php else : ?>
       	    	<div class="form">
        			<h5 style="margin-left: 15px;">У вас нет комментариев</h5>
        		</div>
        	<?php endif ?>
		</div>
		<?= $this->render('index/_sidebar.phtml') ?>
	</div>
</div>
<script type="text/javascript">
	$(".choose_all").click(function(){
		$("input[name^='del_']").each(function(){
			$(this).click();
		});
	});	

	$(".unchoose_all").click(function(){
		$("input[name^='del_']").each(function(){
			$(this).removeAttr("checked");
		});
	});

	$(".del_all").click(function() {
		$("form#user_messages_form").submit();
	});
</script>
