<div class="fix_width">
	<div id="main">
		<div id="content">
			<? if ( is_null($this->paginator) ) : ?>
 				<div class="main_title_block">
 					<h1>У вас нет сообщений</h1>
 				</div>
 			<?php  else : ?>
 				<div class="main_title_block">
 					<h1>Мои сообщения</h1>
 				</div>
 				<?php if ($this->paginator->count() > 1) : ?>
 					<div class="pager_holder gray_pager_holder">
 						<div class="pagination">
							<?php echo $this->paginationControl($this->paginator,'Sliding','shared/pagination_pub.phtml') ?>
						</div>
						<ul class="categories_page">
							<li>Выделить:</li>
							<li><a href="#" id="all" >все</a></li>
							<li><a href="#" id="viewed">прочитанные</a></li>
							<li><a href="#" id="new">новые</a></li>
						</ul>
					</div>
					<form id="user-messages-form" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
						<div class="form">
							<?php
								echo $this->partialLoop('index/messages-row.phtml', $this->paginator);
							?>
							<input class="button pink_button main_search_button_user_cabinet" type="submit" name="submit" id="submit" value="Удалить отмеченные">
							<input class="button pink_button main_search_button_user_cabinet" name="create_message" type="button" id="create-message" value="Новое сообщение">
						</div>
					</form>
				<?php endif ?>
 			<?php endif; ?>
		</div>
		<?= $this->render('index/_sidebar.phtml') ?>
	</div>
</div>
<script type="text/javascript">
	$("#all").click(function(e){
		e.preventDefault();
		$("input[type='checkbox']").each(function(){
			$(this).removeAttr("checked");
		});

		$("input[type='checkbox']").each(function(){
			$(this).click();
		});
	});

	$("#viewed").click(function(e){
		e.preventDefault();
		$("input[type='checkbox']").each(function(){
			$(this).removeAttr("checked");
		});

		$(".checkbox-viewed").each(function(){
			$(this).click();
		});
	});	

	$("#new").click(function(e){
		e.preventDefault();
		$("input[type='checkbox']").each(function(){
			$(this).removeAttr("checked");
		});

		$(".checkbox-new").each(function(){
			$(this).click();
		});
	});

	$("#create-message").click(function(){
		window.location.href = "/index/user-connect";
	});
</script>