<div class="row">
	<div class="span10">
    	<ul class="nav nav-tabs bottom_nav_tabs">
        	<li class="<?=($this->menu_sub['active'] == 'default')?'active':''?>"><a href="/" class="bnt1">Все</a></li>
            <li class="<?=($this->menu_sub['active'] == 'st')?'active':''?>"><a href="?st=50-0" class="bnt2">Фото проверено</a></li>
            <li class="<?=($this->menu_sub['active'] == 'v')?'active':''?>"><a href="?v=1-0" class="bnt4">Анкеты с видео</a></li>
            <li class="<?=($this->menu_sub['active'] == 'rv')?'active':''?>"><a href="/?rv=1-0" class="bnt3">С отзывами</a></li>
        </ul>
    </div>
</div>
<div class="row bg_line">
	<div class="span2">
    	<?= $this->render('index/_filter_left.phtml')?>
        <?#= $this->render('index/_sections_list.phtml')?>
        <?#= $this->render('index/_banners_left.phtml')?>
        <?= $this->render('index/_articles_list.phtml')?>
    	<div class="left_block_text">               
        	<?if($_SERVER['REQUEST_URI'] == '/'):?>
            	<?=nl2br(stripslashes($this->meta['column_left']))?>
            <?endif;?>
			<? if(isset($this->info['text_left'])): ?>
            	<p class="word-wrap"><?=nl2br(stripslashes($this->info['text_left']))?></p>
            <? endif ?>
        </div>
    </div>
    <div class="span6">
    	<div class="right_aside_title">Мои сообщения</div>
    	
    	<?php if ( $this->paginator->count() > 0 ) : ?>    	
    		<div class="form-buttons-user-messages">
				Выделить: <a href="javascript:void(0)" id="all" >все</a>&nbsp;|&nbsp;<a href="javascript:void(0)" id="viewed">прочитанные</a>&nbsp;|&nbsp;<a href="javascript:void(0)" id="new">новые</a>
			</div>	
			<form id="user-messages-form" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
				<div class="form">				
					<?php  
						echo $this->partialLoop('index/messages-row.phtml', $this->paginator); 
					?>
					
					<?= $this->form->getElement('submit') ?> 
					<input name="create_message" type="button" id="create-message" value="Новое сообщение" />			
				</div>
			</form>
			<div class="pagination pagination-centered pagin_girls">  
        		<?=$this->paginationControl($this->paginator,'Sliding','shared/pagination_pub.phtml')?>
        	</div>
        <?php else : ?>
        	<div class="form">
        		<h5 style="margin-left: 15px;">У вас нет сообщений</h5>
        		<input style="margin-left: 15px" name="create_message" type="button" id="create-message" value="Новое сообщение" />		        		
        	</div>
        <?php endif ?>
    </div>
    <div class="span2">
       	<?= $this->render('index/_user_admin.phtml') ?>
        <?= $this->render('index/_filter_right.phtml')?>
        <?#=$this->render('index/_banners_right.phtml')?>
        <div class="right_block_text word-wrap">                    
        	<p class="word-wrap"><?=nl2br($this->textToView($this->info['text_right']))?></p>
        </div>
    </div>
</div>
<script type="text/javascript">
	$(".all").click(function(){
		$("input[type='checkbox']").each(function(){
			$(this).attr("checked", "checked");
		});
	});		

	$(".viewed").click(function(){
		$("input[type='checkbox']").each(function(){
			$(this).removeAttr("checked");
		});
	
		$(".checkbox-viewed").each(function(){
			$(this).attr("checked", "checked");
		});
	});	

	$(".new").click(function(){
		$("input[type='checkbox']").each(function(){
			$(this).removeAttr("checked");
		});
	
		$(".checkbox-new").each(function(){
			$(this).attr("checked", "checked");
		});
	});

	$(document).ready(function(){
		$("#submit").parent().css({
		    'display' : 'inline',
		    'margin-left' : '10px'
		});
	});

	$("#create-message").click(function(){
		window.location.href = "/index/user-connect";
	});
</script>
