<div class="fix_width">
	<div id="main">
		<div id="content">
			<div class="main_title_block">
				<h1>Форма отправки сообщений администрации</h1>
			</div>
			<? if ( $this->message ) :?>
				<?php if ( $this->success ) : ?>
					<div style="margin-left: 10px;">
						<span class="photo_verified"><?= $this->message ?></span>
					</div>
				<?php else : ?>
					<div style="margin-left: 10px;">
						<span class="real_individual"><?= $this->message ?></span>
					</div>
				<?php endif ?>
			<? endif; ?>
			<form id="send_message" action="/index/user-connect" method="post" enctype="multipart/form-data">
				<div class="form">
					<div class="form-left">
						<div class="user_cabinet_form_wrap">
							<div class="user_cabinet_element_wrapper">
								<span class="search_radius_labe">Кому:</span>
								<select name="send_to" id="send_to">
    								<option value="0" label="Выбрать" selected="selected">Выбрать</option>
    								<option value="TO_MODERATION" label="Модерация анкет">Модерация анкет</option>
    								<option value="TO_ADMIN" label="Финансовые вопросы">Финансовые вопросы</option>
								</select>
							</div>
							<div class="user_cabinet_element_wrapper">
								<span class="search_radius_labe">Тема сообщения:</span>
								<input type="text" name="subject" id="subject" value="">
							</div>
							<div class="user_cabinet_element_wrapper">
								<span class="search_radius_labe">Текст сообщения:</span>
								<textarea name="body" id="body"></textarea>
							</div>
							<div class="user_cabinet_element_wrapper">
								<span class="search_radius_labe">Прикрепить фото:</span>
								<input type="file" name="upload" id="upload">
							</div>
  						</div>
  					</div>
  					<input class="button pink_button main_search_button" type="submit" name="submit" id="submit" value="Отправить">
  				</div>
  			</form>
		</div>
		<?= $this->render('index/_sidebar.phtml') ?>
	</div>
</div>
<script type="text/javascript">
$("#submit").click(function(event) {
	var $form = $('#send_message');

	/* remove old valid messages */
    $(".not_valid").each(function(){
		$(this).remove();
  	})

  	/* validation */
  	var isBreak = false;
  	if ( $form.find( 'select[name="send_to"]' ).val() == "0" ) {
    	input = $form.find( 'select[name="send_to"]' );
    	input.after('<p class="not_valid">Укажите получателя.</p>');
    	isBreak = true;
  	}

  	if ( !$form.find( 'input[name="subject"]' ).val() ) {
    	input = $form.find( 'input[name="subject"]' );
    	input.after('<p class="not_valid">Это поле обязательно к заполнению.</p>');
    	isBreak = true;
  	}

  	if ( !$form.find( 'textarea[name="body"]' ).val() ) {
    	input = $form.find( 'textarea[name="body"]' );
    	input.after('<p class="not_valid">Это поле обязательно к заполнению.</p>');
    	isBreak = true;
  	}

  	if (isBreak) {
  		event.preventDefault();
    }
});
</script>