<?php if ( $this->flag == 'banned' ) : ?>
	<div id="center">
		<div class="message">
			<h2>Пользотватель заблокирован!</h2>
		</div>	
	</div>
<?php elseif ( $this->flag == 'error_credentials' ) : ?>
	<div id="center">
		<div class="message">
			<h2>Ошибка авторизации !</h2>
			<br />
			<p>Возможно вы ошиблись при вводе логина (имени пользователя) или пароля.</p>
			<p>Вы можете попытаться ввести пароль и логин ещё раз или воспользоваться <a href="/auth/recovery/">системой восстановления пароля</a>, если вы указали электронный адрес при регистрации.</p>
		</div>
	</div>
<?php elseif ( $this->flag = 'error_banned' ) : ?>
	<div id="center">
		<div class="message">
			<div class="info_message">
				<h2>Неудачные попытки ввода пароля!</h2>
				<p>После многократных попыток авторизации, в целях безопасности, Вам закрыт доступ в админ панель сайта на 15 минут!</p>
			</div>
		</div>
	</div>
<?php endif; ?>