<style>
	.hidden {
		visibility: hidden;
	}
</style>
<script type="text/javascript">
	$(function(){
		$( "#slider_per_hour" ).slider({
			range: true,
			min: 0,
			max: 25000,
			values: [ 0, 25000  ],
			slide: function( event, ui ) {
				$( "#amount_per_hour" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] + " руб");
		  }
		});

		$( "#amount_per_hour" ).val($( "#slider_per_hour" ).slider( "values", 0 ) +
		  " - " + $( "#slider_per_hour" ).slider( "values", 1 ) + " руб");

		$( "#slider_breast_size" ).slider({
			range: true,
			min: 0,
			max: 8,
			values: [ 0, 8 ],
			slide: function( event, ui ) {
				$( "#amount_breast_size" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ]);
		  }
		});

		$( "#amount_breast_size" ).val($( "#slider_breast_size" ).slider( "values", 0 ) +
		  " - " + $( "#slider_breast_size" ).slider( "values", 1 ));
	});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$('.add_review').click(function(){
			$('#hide_register_block').fadeIn();
				return false;
		})
	});
</script>
<div class="fix_width">
	<div id="main">
		<div id="content">
			<div class="main_title_block">
				<h1>
					Новые анкеты - Vbordele.com
				</h1>
			</div>
			<div class="pager_holder gray_pager_holder">
				<div class="pagination">
					<?php echo $this->paginationControl($this->ankets, 'Sliding', 'shared/pagination_pub.phtml')?>
				</div>
				<ul class="categories_page">
					<li><a class="href_send_param" href="javascript:void(0)" param="1">За сегодня</a></li>
					<li><a class="href_send_param" href="javascript:void(0)" param="2">За неделю</a></li>
					<li><a class="href_send_param" href="javascript:void(0)" param="3">За месяц</a></li>
				</ul>
			</div>
			<?php foreach($this->ankets as $row):
					$meta_tags=array('name', 'type', 'performer', 'city', 'metro', 'age', 'breast', 'height', 'weight');
					$meta_replace=array();
					foreach($meta_tags as $key){$meta_replace[$key]=$row[$key];}
					foreach($meta_tags as $key=>$value){$meta_tags[$key]='%'.strtoupper($value).'%';}
					$meta_img=str_replace($meta_tags,$meta_replace,$this->meta['ank_img_alt']);
					$meta_detail=str_replace($meta_tags,$meta_replace,$this->meta['ank_detail']);
					if(!empty($row['photolist'])){
						$photolist=unserialize($row['photolist']);
						if(isset($photolist['preview'])){$photo=$photolist[$photolist['preview']];}
						else{$photo=array_shift($photolist);}
					}else{
						$photo=false;
					}
			?>
			<div class="girl_card">
				<div class="main_info_photo_holder">
					<div class="girl_card_photo">
						<a href="/anketa/<?=$row['name_eng']?>-<?=$row['id']?>" target="_blank">
							<img src="<?php echo $this->url_user_ph. '/' . $row['user_id'] . '/th_' . $photo ?>" width="185" height="280" alt="description">
						</a>
						<!-- <div class="without_retouch"></div> -->
					</div>
					<div class="girl_card_main_info">
					<h4 class="girl_card_title"><?php echo $row['name'] ?></h4>
						<span class="girl_card_price"><?php echo $row['price_1h_ap'] ? $row['price_1h_ap'] : '' ?><span>руб/час</span></span>
						<span class="grey_metro"><span class="grey_metro_icon"></span><?php echo $this->metro_list[$row['metro']] ?></span>
						<ul class="girl_card_info_list">
							<li><a href="/<?php echo getLink($row['age'],array(array(18,21),array(22,30),array(31,40),array(41, 99)),array('vozrast/junye','vozrast/molodye','vozrast/zrelye','vozrast/v-vozraste')); ?>">Возраст..............<?php echo $row['age'] ?></a></li>
							<li><a href="/<?php echo getLink($row['height'], array(array(1,165),array(166,175),array(175, 1000)),array('rost/malenkie','rost/sredego-rosta','rost/vysokie'));?>">Рост...................<?php echo $row['height'] ?></a></li>
							<li><a href="/<?php echo getLink($row['weight'],array(array(1,49),array(50,60),array(61,300)),array('ves/hudenkie', 'ves/strojnye', 'ves/polnenkie')) ?>">Вес....................<?php echo $row['weight'] ?></a></li>
							<li><a href="/<?php echo getLink($row['breast'],array(array(0,2),array(3,5),array(6,8)),array('razmer-grudi/s-malenkoj-grudiu','razmer-grudi/s-bolshoj-grudiu','razmer-grudi/s-ochen-bolshoj-grudiu'))?>">Грудь.................<?php echo $row['breast'] ?></a></li>
						</ul>
						<span class="contain_video"><?php if ( $row['videolist'] ) : ?><span class="contain_video_icon"></span>Есть видео<?php endif ?></span>
						<span class="photo_verified"><?php if ( $row['status']>20 ) : ?><span class="photo_verified_icon"></span>Фото проверено<?php endif ?></span>
						<span class="real_individual"><?php if ( true ) : ?><span class="real_individual_icon"></span>Реальня индивидуалка<?php endif ?></span>
						<div class="new_ribbon"></div>
					</div>
				</div>
				<div class="girl_card_another_info">
					<div class="girl_card_likes_holder">
						<div class=girl_card_likes_programms>
							<h5>Любимые программы:</h5>
								<?php 
									$this->row = $row;
									echo $this->render('_show-services.phtml');
								 ?>
						</div>
						<div class="girl_card_rating_block">
							<div class="girl_card_rating">
								<span class="common_girl_card_rating"><span class="white_star_icon"></span><?php echo $this->getRatioVoices($row['id']) ?></span>
								<ul class="rating_stars">
									<?php echo str_repeat("<li></li>", floor($this->getRatioVoices($row['id'])) ) ?>
								</ul>
									<span class="all_voices_text">Всего голосов: <?php echo $this->getCountVoices($row['id']) ?></span>
							</div>
							<div class="girl_card_revies">
								<span class="green_label">Отзывы пользователей</span>
									<ul class="voices_counter">
										<li><span class="good_voice"><?php echo $this->getPositiveVoices($row['id']) ?></span></li>
										<li><span class="voice"><?php echo $this->getNeutralVoices($row['id']) ?></span></li>
										<li><span class="bad_voice"><?php echo $this->getNegativeVoices($row['id']) ?></span></li>
									</ul>
							</div>
						</div>
					</div>
					<div class="girl_card_text">
						<span><?=nl2br($row['about'])?></span>
					</div>
				</div>
					<?php if ($row['score']) : ?>
						<span class="good_score in_preview"><span class="good_score_icon"></span>&nbsp;Рекомендуют</span></span>
					<?php endif ?>
					<a href="/anketa/<?=$row['name_eng']?>-<?=$row['id']?>" target="_blank" class="button show_anket_btn">Посмотреть анкету</a>
			</div>
			<?php endforeach ?>	
		</div>
	</div>
	<?= $this->render('index/_sidebar.phtml') ?>
</div>
<form id="href_send_param" action="<?php echo $_SERVER['REQUEST_URI'] ?>" method="post" style="display: none;">
	<input type="hidden" value="" name="novelty" id="input_hidden_href">
</form>
<script type="text/javascript">
	$(".href_send_param").click(function(e){
		e.preventDefault();

		var $param = $(this).attr('param');
		$('#input_hidden_href').val($param);
		$("#href_send_param").submit();
	});
</script>