
		<div class="main_title_block">
			<h1>Интим карта</h1>
		</div>
		<div>
			<script type="text/javascript">
				var myMap = null;
				var coords = <?=$this->coords?>;
				var salons_coords = <?=$this->salons_coords?>;
				var city = <?=$this->city?>;

				function init() {
					switch (city) { //set center appropiatally city
						case 2: center = [59.938, 30.313]; break;
						case 1: center = [55.76, 37.64]; break;
						default: center = [59.938, 30.313];
					}

					document.getElementById("map").innerHTML = "";
					myMap = new ymaps.Map('map', {
						center: center,
						zoom: 10,
						behaviors: ['default', 'scrollZoom']
					},
					{
						minZoom: 9,
						maxZoom: 18
					});
					myMap.controls
						.add('zoomControl', { left: 10, top: 10 })
						.add('mapTools', { left: 35, top: 10 });

					if (coords != null) { //start of display ankets coords
						clusterer = new ymaps.Clusterer({
							preset: 'twirl#whiteClusterIcons',
							groupByCoordinates: false,
							clusterDisableClickZoom: true
						});

						getPointData = function (index) {
							return {
								balloonContentBody: '<span style="margin-bottom: 3px; display: block;">'+coords[index][6]+' ('+coords[index][7]+')</span><div style="background:url(\'/user_photos/'+coords[index][4]+'/tn_'+coords[index][5] + '\') no-repeat scroll center top transparent; width: 110px; height: 110px;"></div>',
								clusterCaption: '<strong>' + coords[index][6] + '</strong>'
							};
						}

						getPointOptions = function (index) {
							switch (coords[index][1]) {
								case 1: preset = 'twirl#redStretchyIcon'; break;
								case 2: preset = 'twirl#brownStretchyIcon';	break;
								case 3: preset = 'twirl#yellowStretchyIcon'; break;
								case 4: preset = 'twirl#orangeStretchyIcon'; break;
								case 5: preset = 'twirl#pinkStretchyIcon'; break;
								case 6: preset = 'twirl#nightStretchyIcon'; break;
								case 7: preset = 'twirl#blackStretchyIcon'; break;
								default: preset = 'twirl#violetIcon';
							}

							return {
								preset: preset
							};
						}

						geoObjects = [];
						for(var i = 0, len = coords.length; i < len; i++) {
							geoObjects[i] = new ymaps.Placemark([coords[i][2], coords[i][3]], getPointData(i), getPointOptions(i));
						}

						clusterer.options.set({
							gridSize: 50,
							clusterDisableClickZoom: true
						});

						clusterer.add(geoObjects);

						clusterer.events
							.add(['mouseenter', 'mouseleave'], function (e) {
								var target = e.get('target'), 
								eType = e.get('type'), 
								zIndex = Number(eType === 'mouseenter') * 1000;

								target.options.set('zIndex', zIndex);
							});

						myMap.geoObjects.add(clusterer);
					}

					if (salons_coords != null) { //start of display salons coords
						clusterer = new ymaps.Clusterer({
							preset: 'twirl#invertedVioletClusterIcons',
							groupByCoordinates: false,
							clusterDisableClickZoom: true
						});

						getPointData = function (index) {
							return {
								balloonContentBody: '<span style="margin-bottom: 3px; display: block;">'+salons_coords[index][6]+' ('+salons_coords[index][7]+')</span><div style="background:url(\'/user_photos/'+salons_coords[index][4]+'/tn_'+salons_coords[index][5] + '\') no-repeat scroll center top transparent; width: 110px; height: 110px;"></div>',
								clusterCaption: '<strong>' + salons_coords[index][6] + '</strong>'
							};
						}

						getPointOptions = function (index) {
							switch (salons_coords[index][1]) {
								default: preset = 'twirl#houseIcon';
							}

							return {
								preset: preset
							};
						}

						geoObjects = [];
						for(var i = 0, len = salons_coords.length; i < len; i++) {
							geoObjects[i] = new ymaps.Placemark([salons_coords[i][2], salons_coords[i][3]], getPointData(i), getPointOptions(i));
						}

						clusterer.options.set({
							gridSize: 50,
							clusterDisableClickZoom: true
						});

						clusterer.add(geoObjects);

						clusterer.events
							.add(['mouseenter', 'mouseleave'], function (e) {
								var target = e.get('target'), 
								eType = e.get('type'), 
								zIndex = Number(eType === 'mouseenter') * 1000;

								target.options.set('zIndex', zIndex);
							});

						myMap.geoObjects.add(clusterer);
					}
				}

				ymaps.ready(init);
			</script>
			<div id="map" style="width:100%; height:600px"></div>
		</div>
