<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.4.3.2 setup script
 * Date: Wed, 18 Jan 2012 06:27:34 +0400
 */

/* Servers configuration */
$i = 0;

/* Server: mysqlserver [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'allexx';
$cfg['Servers'][$i]['password'] = 'O0CsLPd98';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = '4f162dabe7d730.14808162';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
