<?php //get sections for right uri links ?>
<?$srv_add_text=unserialize($this->row['srv_add_text']);?>
<?php $sections = new Model_SectionsTest(); ?>
<ul class="red_dot_list">
<?php
    $count = 0;
	foreach($this->services as $srv=>$list){
		array_shift($list);
		foreach($list as $key=>$value){
			if( $this->row['srv'.'_'.$srv] & 1<<$key ) {
				echo "<a href='/";
				echo $sections->getUriForServices('srv_' . $srv . '&1<<' . $key) ? $sections->getUriForServices('srv_' . $srv . '&1<<' . $key) : '#';
				echo "' />";
				echo "<li>" . $value;
				if ( $srv_add_text[$srv.'_'.$key.'_add_input']) {
					echo '<br/>'.$srv_add_text[$srv.'_'.$key.'_add_input'];
				}
				echo "</li>";
				echo "</a>";
				$count++;
				if ( $count > 2 ) {
					break 2;
				}
			}
		}
	}
?>
</ul>
