<div class="pagination">
	<ul>
	<?php if( isset( $this->previous ) ) : ?>
		<li>
			<a href="<?= "/cabinet" . $this->getRightUri( $_GET ) . "p=" . $this->previous ?>">«</a>
		</li>
	<?php else : ?>
		<li>
			<a href="javascript:void(0)">«</a>
		</li>
	<?php endif; ?>
	<?php foreach($this->pagesInRange as $page) : ?>
		<?php if( $page != $this->current) : ?>
			<li><a href="<?= "/cabinet" . $this->getRightUri( $_GET ) . "p=" . $page ?>"><?php echo $page; ?></a></li>
		<?php else : ?>
			<li><a href="javascript:void(0)" style="background: #e8e8e8"><?= $page; ?></a></li>
		<?php endif; ?>
	<?php endforeach; ?>
	<?php if( isset( $this->next ) ) : ?>
		<li>
			<a href="<?= "/cabinet" . $this->getRightUri( $_GET ) . "p=" . $this->next ?>">»</a>
		</li>
	<?php else : ?>
		<li>
			<a href="javascript:void(0)">»</a>
		</li>
	<?php endif; ?>
	</ul>
</div>