<?php if ( $this->comments->getTotalItemCount() ): ?>
	<div class="ribbon_title_bg">
		<div class="ribbon_title_overflow">
			<h2 class="ribbon_title_fll">Отзывы</h2>
			<span class="allreviews_in_title"><a href="#"><?php echo $this->comments->getTotalItemCount() ?> отзыва(ов) </a>от работодателей за все время</span>
		</div>
	</div>
	<div class="clear">
		<div class="comes_count_block">
			<span class="common_salon_card_rating">1987 <span class="smaller_rate">пойду</span></span>
			<span>11 <span class="notcome">не пойду</span></span>
		</div>
	</div>
	<ul class="reviews">
	<?php foreach ( $this->comments as $comment) : ?>
		<li>
			<div class="avatar"><img src="pics/pic19.jpg" width="60" height="60" alt="description"></div>
			<div class="good_score_icon"></div>
			<?=$comment['text']?>
		</li>
	<?php endforeach; ?>
	</ul>	
<?php endif ?>
<?=$this->paginationControl($this->comments,'Sliding','shared/pagination_comm.phtml')?>
<!-- 
<?php if ( count($this->comments) ): ?>
	
	<div class="root_girl_title">Отзывы:</div>
	<?foreach($this->comments as $comment):?>
    	<div class="review_title">
        	<?if($this->admin):?><a href="<?=$this->url(array('action'=>'comm-del-req','cn'=>$comment['id']))?>" class="del">УДАЛИТЬ</a><?endif?>
            <span><?=date('d.m.y G:i',strtotime($comment['timestamp']))?></span>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#"><?=$comment['user_login']?></a>
        </div>
    	<div class="review_text"><?=$comment['text']?></div>
	<?endforeach?>
<?php endif ?>
<?=$this->paginationControl($this->comments,'Sliding','shared/pagination_comm.phtml')?>	
<?php if ( $this->flags != '2') : ?>
	<? if(isset($this->auth)): ?>
		<div class="root_girl_title">Написать отзыв:
			<div class="ca_top">
				<textarea name="text" cols="18" style="width: 343px;"></textarea>
			</div>
			<a id="add_comment_button" class="button"/>Отправить</a>				
		</div>
		<script type="text/javascript">
			$("#add_comment_button").click(function () {			
         	   var text = $("textarea[name=text]").val();

				$.get("/index/comm-add/n/<?= $this->info['id'] ?>", 
					{text: text},
					function (response) {
						$("textarea[name=text]").val('');
					}
				);
			});
		</script>
	<?else:?>
		<div class="root_girl_title" id="add-comment">
			<a id="add_comment_button" href="javascript:addComment('<?=$this->url(array('action'=>'comm-add','n'=>$this->info['id']))?>');">
				Написать отзыв
			</a>
		</div>
	<?endif?>
<?php endif ?>
-->