<? if ( $this->comments->getTotalItemCount() ): ?>
	<div class="ribbon_title_bg">
		<div class="ribbon_title_overflow">
			<h2 class="ribbon_title_fll">Комментарии</h2>
			<span class="allreviews_in_title">
				<a href="#"><?php echo $this->comments->getTotalItemCount() ?> комментариев </a>от работодателей за все время
			</span>
		</div>
	</div>
	<ul class="reviews">
	<?php foreach ( $this->comments as $comment) : ?>
		<li>
			<?php echo rusdate(strtotime($comment['timestamp']), 'j %MONTH% Y H:i') ?> | <?php echo $this->getUserLoginById($comment['user_id']) ?><br/>
			<?=$comment['text']?>
		</li>
	<?php endforeach; ?>
	</ul>
<? endif ?>
<?=$this->paginationControl($this->comments,'Sliding','shared/pagination_comm.phtml')?>
<a href="#" class="add_comm">
	<span class="add_review_icon"></span>Оставить комментарий
</a>
<?php if ( !$this->user_id ): ?>
<div id="hide_register_block_comm">
	<div class="popup_holder">
		<div class="root_girl_title">
			<form action="/auth" method="post" class="root_girl_form">
				<div class="root_girl_form_text">Комментарии могут оставлять только зарегистрированные пользователи!</div>
				<div class="root_girl_form_elem">
					<input type="text" name="username" id="num_phone">
					<input type="password" name="password" id="num_phone">
					<input type="hidden" id="url" name="url" value="<?php echo $_SERVER['REQUEST_URI'] ?>">
					<button class="button">Войти на сайт</button>
					<a class="btn_reg" href="#">Регистрация</a>
				</div>
			</form>
		</div>
	</div>
</div>
<?php else: ?>
<div class="comments_common_block hide">
	<h5 class="question_title">Комментарий <span class="required">*</span></h5>
	<textarea name="comment_text" cols="30" rows="10"></textarea>
	<div class="clear">
		<button class="send_comment button">Отправить</button>
	</div>
</div>
<? endif ?>
<script type="text/javascript">
$(".send_comment").click(function () {
	var text = $("textarea[name=comment_text]").val();

	$.get("/index/comm-add/n/<?= $this->info['id'] ?>",
		{text: text},
		function (response) {
			$("textarea[name=comment_text]").val('');
		}
	);
});
</script>
<script type="text/javascript">
	$(".add_comm").click(function(e){
		e.preventDefault();

		var $user_id = <?php if ( $this->user_id ) echo $this->user_id; else echo "null"; ?>;

		if ( $user_id ) {
			$('div.comments_common_block').toggleClass('hide');
		} else {
			$('#hide_register_block_comm').fadeIn();
		}
	});
</script>