<?php $sections = new Model_SectionsTest(); ?>
<?foreach($this->services as $part=>$srv):?>	
	<?if(isset($this->part_active[$part])): $i++?>
		<?php if ( $i % 2 == 0 ) : ?><div class="additional_skils_right"><?php else : ?><div class="additional_skils_left"><?php endif ?>
        	<h5><?php echo array_shift($srv) ?></h5>
        	<ul class="red_dot_list">
				<?foreach($srv as $num=>$val):?>
					<a href="<?php echo $sections->getUriForServices('srv_' . $part . '&1<<' . $num) ? $sections->getUriForServices('srv_' . $part . '&1<<' . $num) : '#';?>">
					<?if($this->srv_active[$part.'_'.$num]):?>
						<li><?=$val?></li>
					<?endif?>
					</a>
				<?endforeach?>
			</ul>
      	</div>
    <?endif?>
    <?php if ( $i % 2 == 0 ) : ?>
      		<div style="clear: both;"></div>
     <?php endif ?>
<?endforeach?>
<?if( $this->info['only']) : $i++?>
	<?php if ( $i % 2 == 0 ) : ?><div class="additional_skils_right"><?php else : ?><div class="additional_skils_left"><?php endif ?>
		<h5>Только у меня:</h5>
		<ul class="red_dot_list">
			<li><?=$this->info['only']?></li>
		</ul>
	</div>
<?endif?>