<?$srv_add_text=unserialize($this->info['srv_add_text']);?>
<?foreach($this->services as $part=>$srv):?>
	<?if(isset($this->part_active[$part])): $i++?>
		<?php if ( $i % 2 == 0 ) : ?><div class="additional_skils_right"><?php else : ?><div class="additional_skils_left"><?php endif ?>
        	<h5><?php echo array_shift($srv) ?></h5>
        	<ul class="red_dot_list">
				<?foreach($srv as $num=>$val):?>
					<a href="/<?php echo $this->sections->getUriForServices('srv_' . $part . '&1<<' . $num) ? $this->sections->getUriForServices('srv_' . $part . '&1<<' . $num) : '#';?>">
					<?if($this->srv_active[$part.'_'.$num]):?>
						<li>
							<?=$val?><br/>
							<span style="color: #d84a2e;"><?if(!empty($srv_add_text)){echo $srv_add_text[$part.'_'.$num.'_add_input'];}?></span>
						</li>
					<?endif?>
					</a>
				<?endforeach?>
			</ul>
      	</div>
    <?endif?>
    <?php if ( $i % 2 == 0 ) : ?>
      		<div style="clear: both;"></div>
     <?php endif ?>
<?endforeach?>
<?if( $this->info['only']) : $i++?>
	<?php if ( $i % 2 == 0 ) : ?><div class="additional_skils_right"><?php else : ?><div class="additional_skils_left"><?php endif ?>
		<h5>Только у меня:</h5>
		<ul class="red_dot_list">
			<li><?=$this->info['only']?></li>
			<?$onlys=unserialize($this->info['only_add']);?>
			<?if(!empty($onlys)):?>
				<?foreach($onlys as $k => $v):?>
					<li><?=$v?></li>
				<?endforeach?>
			<?endif?>
		</ul>
	</div>
<?endif?>