<div class="fix_width">
	<div id="main">
		<div class="side_narrow_common_holder">
			<div class="main_title_block">
				<h1 class="float_main_title">
					<?=$this->info['performer']?>
                	<?=$this->info['name']?>
                	<?if ( $this->info['name_2'] ):?>
            	  		 и<?=" ".$this->info['name_2']?>
               		<?endif?>
				</h1>
				<span class="button pink_button float_pink_button">Новенькая</span>
				<?php
         			if ( $this->flags == '0' || $this->flags == '2' ) :
            			$postpone = new Model_Postpone();
            			$ids = $postpone->getUserAnkPostponeIds( $this->user_id );

            			if ( !in_array($this->info['id'], $ids) ) :
        		 ?>
							<a class="add_favorites" href="javascript:void(0)" id="postpone" >
								<span class="add_favorites_icon"></span>В избранное
							</a>
					<?php else : ?>
							<a class="add_favorites" href="javascript:void(0)">
								<span class="add_favorites_icon"></span>Уже в избранном
							</a>
					<?php endif ?>
				<?php endif ?>
			</div>
			<aside id="left_sidebar">
				<? if($this->info['photolist']):?>
					<ul class="anket_preview_girl">
					<?php foreach($this->info['photolist'] as $thumb):?>
                	<? if ( $thumb['fs'] ) : ?>	
                    	<li>
                    		<a href="/watermark.php?image=.<?=$thumb['fs']?>" onclick="return hs.expand(this, { align: 'center' })">
                    			<img src="/watermark.php?image=.<?=$thumb['fs']?>" width="233" height="352" alt="description">
                    		</a>
                    	</li>
                	<? endif ?>
               		<? endforeach; ?> 
               		</ul>
               	<?php endif; ?>
			</aside>
			<div id="narrow_content">
				<div class="ribbon_title_bg">
					<h2>основная информация</h2>
				</div>
				<div class="single_girl_main_info_block">
					<div class="single_girl_main_info_block_l">
						<span class="big_red_phone"></span>
						<ul class="single_girl_from">
							<li><span class="red_col">Санкт-Петербург,</span></li>
							<a href="/<?php echo $this->sections->getUriForDistrict($this->info['district'], $this->city ) ?>"><li><?php echo $this->district_list[$this->info['district']] ?></li></a>
							<br />
							<h5>Место встречи: </h5>
							<a href="/<?php echo getLink($this->info['place'], array(array(1,1),array(2,2),array(3,3)),array('mesto-vstrechi/vstrecha-v-apartamentah','mesto-vstrechi/vyezd','mesto-vstrechi/vstrecha-v-saune')) ?>"><li><?php echo $this->places[$this->info['place']] ?></li></a>
						</ul>
						<a href="/<?php echo $this->sections->getUriForMetro($this->info['metro'], $this->city) ?>">
							<span class="grey_metro">
								<span class="grey_metro_icon"></span>
								<?= $this->metro_list[$this->info['metro']]?>
							</span>
						</a>
						<h5>Параметры:</h5>
						<ul class="girl_card_info_list black_list">
							<li><a href="<?php echo getLink($this->info['age'],array(array(18,21),array(22,30),array(31,40),array(41, 99)),array('vozrast/junye','vozrast/molodye','vozrast/zrelye','vozrast/v-vozraste')); ?>">Возраст..............<?php echo $this->info['age'] ?></a></li>
							<li><a href="<?php echo getLink($this->info['height'], array(array(1,165),array(166,175),array(175, 1000)),array('rost/malenkie','rost/sredego-rosta','rost/vysokie'));?>">Рост...................<?php echo $this->info['height'] ?></a></li>
							<li><a href="<?php echo getLink($this->info['weight'],array(array(1,49),array(50,60),array(61,300)),array('ves/hudenkie', 'ves/strojnye', 'ves/polnenkie')) ?>">Вес....................<?php echo $this->info['weight'] ?></a></li>
							<li><a href="<?php echo getLink($this->info['breast'],array(array(0,2),array(3,5),array(6,8)),array('razmer-grudi/s-malenkoj-grudiu','razmer-grudi/s-bolshoj-grudiu','razmer-grudi/s-ochen-bolshoj-grudiu'))?>">Грудь.................<?php echo $this->info['breast'] ?></a></li>
						</ul>
						<br/>
						<h5>Внешность:
						<?php if ( $this->info['hair'] ) : ?>
							<a href="/<?php echo getLink($this->info['hair'],array(array(1,1),array(2,2),array(3,3),array(4,4),array(5,5)),array('tsvet-volos/blondinki', 'tsvet-volos/brunetki', 'tsvet-volos/rusye', 'tsvet-volos/ryzhye', 'tsvet-volos/shatenki'))?>"><?php echo $this->hair[$this->info['hair']] ?></a>
						<?php endif; ?>
						<?php if ( $this->info['exotics'] ) : ?>
							<a href="/<?php echo getLink($this->info['exotics'],array(array(1,1),array(2,2), array(3,3),array(4,4),array(5,5),array(6,6),array(7,7),array(8,8),array(9,9),array(10,10)), array('nacionalnost/aziatki', 'nacionalnost/mulatki', 'nacionalnost/negrityanki', 'nacionalnost/uzbechki', 'nacionalnost/ukrainki', 'nacionalnost/kazashki', 'nacionalnost/tatarki', 'nacionalnost/gruzinki', 'nacionalnost/cyganki', 'nacionalnost/kirgizki')) ?>"><?php echo $this->exotics[$this->info['exotics']] ?></a>
						<?php endif; ?>	
						<!-- <div class="without_ret2"></div> -->
						</h5>
					</div>
					<div class="single_girl_main_info_block_r">
						<div class="salon_card_another_info">
							<div class="salon_card_rating_block">
								<div class="salon_card_rating">
									<span class="common_salon_card_rating"><span class="white_star_icon"></span><?php echo $this->getRatioVoices($this->info['id']) ?></span>
										<ul class="rating_stars">
											<?php echo str_repeat("<li></li>", floor($this->getRatioVoices($this->info['id'])) ) ?>
										</ul>
									<span class="all_voices_text">Всего голосов: <?php echo $this->getCountVoices($this->info['id']) ?></span>
								</div>
								<div class="salon_card_revies">
									<span class="green_label">Отзывы пользователей</span>
									<ul class="voices_counter">
										<li><span class="good_voice"><?php echo $this->getPositiveVoices($this->info['id']) ?></span></li>
										<li><span class="voice"><?php echo $this->getNeutralVoices($this->info['id']) ?></span></li>
										<li><span class="bad_voice"><?php echo $this->getNegativeVoices($this->info['id']) ?></span></li>
									</ul>
								</div>
							</div>
							<span class="real_individual"><?php if ( true ) : ?><span class="real_individual_icon full"></span>Реальня индивидуалка<?php endif ?></span>
							<span class="photo_verified"><?php if ( $this->info['status'] > 20 ) : ?><span class="photo_verified_icon"></span>Фото проверено<?php endif ?></span>
							<h5 class="common_programs">Любимые программы:</h5>
							<?php 
								$this->row = $this->info;
								echo $this->render('_show-services.phtml');
							?>
						</div>
					</div>
				</div>
				<div class="grey_title_box">
					<strong>Тариф:</strong>
				</div>
				<table class="grey_table">
					<thead>
						<tr>
							<td></td>
							<td>Апартаменты</td>
							<td>Выезд</td>
							<td>Анал</td>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><span class="one_hour_icon"></span>1 час</td>
							<td><?if ( $this->info['price_1h_ap'] ): ?><?=number_format($this->info['price_1h_ap'], 0, ',', '.') . " руб";?><?endif?></td>
							<td><?if ( $this->info['price_1h_ex'] ): ?><?=number_format($this->info['price_1h_ex'], 0, ',', '.') . " руб";?><?endif?></td>
							<td></td>
						</tr>
						<tr>
							<td><span class="two_hour_icon"></span>2 часа</td>
							<td><?if ( $this->info['price_2h_ap'] ):?><?=number_format($this->info['price_2h_ap'], 0, ',', '.') . " руб";?><?endif?></td>
							<td><?if ( $this->info['price_2h_ex'] ):?><?=number_format($this->info['price_2h_ex'], 0, ',', '.') . " руб";?><?endif?></td>
							<td>-</td>
						</tr>
						<tr>
							<td><span class="all_night_icon"></span>Ночь</td>
							<td><?if ( $this->info['price_n_ap'] ):?><?=number_format($this->info['price_n_ap'], 0, ',', '.') . " руб";?><?endif?></td>
							<td><?if ( $this->info['price_n_ex'] ):?><?=number_format($this->info['price_n_ex'], 0, ',', '.') . " руб";?><?endif?></td>
							<td></td>
						</tr>
					</tbody>
				</table>
				<div class="ribbon_title_bg">
					<h2>предпочтения</h2>
				</div>
				<div class="additional_skils">
					<?php echo $this->render("anketa/_show-services.phtml") ?>
				</div>
				<div class="ribbon_title_bg">
					<h2>О себе</h2>
				</div>
				<p><?=nl2br($this->info['about'])?></p>
				<?php
					echo $this->render('anketa/_comments-block.phtml');
				?>
			</div>
		</div>
		<aside id="sidebar">
			<div class="sidebox pink">
				<?php if( $this->info['videolist'] ) : ?>
					<div class="sidebox_header">
						<h3>Мое видео</h3>
					</div>
					<div class="sidebox_content no_padding">
                  		<?php $video=array_shift($this->info['videolist']); ?>
                  		<?php $swflink = 'file='.$video['fs'].'&image=/img/videoprev.jpg&author=vipsoski.com&description=Видео - на видео проститутка '.$this->info['name'].', тел: '.$this->info['phone']?>
                  		<span id="video1" class="br_img01"><embed type="application/x-shockwave-flash" src="/player.swf" width="248" height="189" style="undefined" id="player" name="player" quality="high" allowfullscreen="true" allowscriptaccess="always" flashvars="<?=$swflink;?>"></span>
                  		<script type="text/javascript" src="/js/swfobject.js"></script>
                  		<script type="text/javascript">
                      		var s1 = new SWFObject('/player.swf','player','230','189','9');
                        	s1.addParam('allowfullscreen','true');
                        	s1.addParam('allowscriptaccess','always');
                        	s1.addParam('flashvars','<?=$swflink;?>');
                       		s1.write('video1');
                   	 	</script>
					</div>
				<?php endif ?>
			</div>
			<div class = "sidebox pink">
				<div class="sidebox_header">
					<h3>оценки клиентов</h3>
				</div>
				<div class="sidebox_content no_side_padding">
					<?php if ($this->info['score']) : ?>
						<span class="total_score"><span class="good_score"><span class="good_score_icon"></span>&nbsp;Рекомендуют</span></span>
					<?php endif ?>
					<ul class="reviews_sidebar_item">
						<?php foreach ( $this->latest2reviews as $review ) : ?>
						<li>
							<span class="reviewer_name"><?php echo $this->getUserLoginById($review['user_id']) ?></span>
							<ul class="reviews_sidebar_item_info">
								<li>Фото оригинал: 
									<span class="black">
									<?php if ( $review['photo_original'] ) : ?>
											Да
										<?php if ( $review['photo_original_select'] == 1 ) :?>
											, 100% без ретуши
										<?php else : ?>
											, есть фотошоп
										<?php endif ?>
									<?php else : ?>
										Чужие
									<?php endif ?>
									</span>
								</li>
								<li>Реальна индивидуалка: 
									<span class="black">
										<?php if ($review['real_individual'] == 1) : ?>
											Да
										<?php elseif ($review['real_individual'] == -1) : ?>
											Салон
										<?php elseif ($review['real_individual'] == 0) : ?>
											Не знаю
										<?php endif ?>
									</span>
								</li>
								<li>
									Отношение к клиенту:
									<div class="black">
										<ul class="rating_stars">
											<?php echo str_repeat("<li></li>", $review['service']) ?>
										</ul>
									</div>
								</li>
								<li>
									Апартаменты:
									<div class="black">
										<ul class="rating_stars">
											<?php echo str_repeat("<li></li>", $review['apartment']) ?>
										</ul>
									</div>
								</li>
								<?php $services = unserialize($review['services']) ?>
								<?php foreach ( $services as $srv ) : ?>
								<?php list($name, $score) = explode("_", $srv)?>
								<li>
									<?php echo $name; ?>
									<div class="black">
										<ul class="rating_stars">
											<?php echo str_repeat("<li></li>", $score ) ?>
										</ul>
									</div>
								</li>
								<?php endforeach ?>
							</ul>
							<span class="single_reviewer_total_score">Общая оценка: <span class="good_score">рекомендую <span class="good_score_icon"></span></span></span>
						</li>
						<?php endforeach ?>	
					</ul>
					<a href="#" class="more_reviews">Показать все отзывы</a>
				</div>
			</div>
			<div class="sidebox pink">
				<div class="sidebox_header">
					<h3>ищи меня на карте</h3>
				</div>
				<div class="sidebox_content no_padding">
					<img src="/img/pic30.jpg" width="248" height="189" alt="description">
				</div>
			</div>
			<?php
        		$salon = $this->salon;
            	if(!empty($salon['photolist'])){
					$photolist=unserialize($salon['photolist']);
					 if(isset($photolist['preview'])){$photo=$photolist[$photolist['preview']];}
						else{$photo=array_shift($photolist);}
				} else {
					$photo=false;
				}
				if ($photo) :
			?>
			<div class="sidebox">
				<div class="sidebox_header">
					<h3>анкета от салона</h3>
				</div>
				<div class="sidebox_content">
					<div class="salon_anket_sidebox">
						<div class="salon_anket_sidebox_name">
							<h4><?php echo $salon['name'] ?></h4>
							<!-- <span><?php echo $salon['about'] ?></span> -->
						</div>
						<div class="salon_anket_sidebox_place">
							<span><span class="grey_metro_icon"></span><?php $metro = explode(";", $salon['metro']); echo $this->metro_list[$metro[0]]; ?></span>
							<span>г. Москва</span>
							<span class="girl_card_price"><?php echo $salon['price_1h_ap']?><span>руб/час</span></span>
						</div>
					</div>
					<div class="salon_anket_sidebox_preview">
						<img src="<?php echo $this->url_user_ph.'/'.$salon['user_id'].'/th_'.$photo?>" width="237" height="161" alt="description">
						<!-- <div class="new_ribbon"></div> -->
					</div>
					<div class="salon_anket_sidebox_more_info">
						<div class="salon_anket_sidebox_more_left">
							<?php 
								$this->row = $salon;
								echo $this->render('_show-services-salon.phtml'); 
							?>
							<ul class="salon_anket_sidebox_more_left">
								<li></li>
								<li></li>
								<li></li>
							</ul>
						</div>
						<div class="salon_anket_sidebox_more_right">
							<ul class="salon_card_info_list">
								<li>Девушек...<?php echo $salon['girl_number'] ?></li>
								<li>Комнат.....<?php echo $salon['room_number'] ?></li>
							</ul>
							<a href="/salon/<?=$salon['name_eng']?>-<?=$salon['id']?>" class="more_link_side">Подробнее</a>
						</div>
					</div>
				</div>
			</div>
			<?php 
				endif;
			?>
		</aside>
	</div>
</div>
<script type="text/javascript">
	$.get("/remote/phone/n/<?=$this->info['id']?>", function(data){
		$(".big_red_phone").html(data); 
	},"");

	<? if ( $this->user_id ) : ?>
   	$("#postpone").click(function (){
        var user_id = <?= $this->user_id ?>;
        var ank_id = <?= $this->info['id']; ?>;
		$.get("/remote/postpone", {user_id : user_id , ank_id : ank_id }, function(data) {
			$("#postpone").html(data);
		});
    });
    <? endif ?>
</script>