<?
$kategorii = array('deshevye' => 1,
                    'elitnye' => 2,
                    'starye' => 3,
                    'molodye' => 4,
                    'tolstye' => 5,
                    'hudye' => 6,
                    'aziatki' => 7,
                    'negrityanki' => 8,
                    'mulatki' => 9,
                    'uzbechki' => 10,
                    's-otzyvami' => 11,
                    'vyezd-na-dom' => 12,
                    's-apartamentami' => 13);

$metro = array("avtovo" => 1,
                "admiraltejskaja" => 2,
                "akademicheskaja" => 3,
                "baltijskaja" => 4,
                "buharestskaja" => 5,
                "vasileostrovskaja" => 6,
                "vladimirskaja" => 7,
                "volkovskaja" => 8,
                "vyborgskaja" => 9,
                "gorkovskaja" => 10,
                "gostinyj-dvor" => 11,
                "grazhdanskij-prospekt" => 12,
                "devjatkino" => 13,
                "dostoevskaja" => 14,
                "elizarovskaja" => 15,
                "zvezdnaja" => 16,
                "zvenigorodskaja" => 17,
                "kirovskij-zavod" => 18,
                "komendantskij-prospekt" => 19,
                "krestovskij-ostrov" => 20,
                "kupchino" => 21,
                "ladozhskaja" => 22,
                "leninskij-prospekt" => 23,
                "lesnaja" => 24,
                "ligovskij-prospekt" => 25,
                "lomonosovskaja" => 26,
                "majakovskaja" => 27,
                "mezhdunarodnaja" => 28,
                "moskovskaja" => 29,
                "moskovskie vorota" => 30,
                "marvskaja" => 31,
                "nevskij-prospekt" => 32,
                "novocherkasskaja" => 33,
                "obvodnyj-kanal" => 34,
                "obuhovo" => 35,
                "ozerki" => 36,
                "park-pobedy" => 37,
                "parnas" => 38,
                "petrogradskaja" => 39,
                "pionerskaja" => 40,
                "ploshhad-nevskogo" => 41,
                "ploshhad-vosstanija" => 42,
                "ploshhad-lenina" => 43,
                "ploshhad-muzhestva" => 44,
                "politehnicheskaja" => 45,
                "primorskaja" => 46,
                "proletarskaja" => 47,
                "prospekt-bolshevikov" => 48,
                "prospektveteranov" => 49,
                "prospekt-rosveshhenija" => 50,
                "pushkinskaja" => 51,
                "rybackoe" => 52,
                "sadovaja" => 53,
                "sennaja-ploshhad" => 54,
                "sportivnaja" => 55,
                "staraja-derevnja" => 56,
                "tehnologicheskij-institut" => 57,
                "udelnaja" => 58,
                "ulica-dybenko" => 59,
                "frunzenskaja" => 60,
                "chernaja-rechka" => 61,
                "chernyshevskaja" => 62,
                "chkalovskaja" => 63,
                "jelektrosila" => 64);

$uslugi_mass = array('rasslabljajushhij' => 0,
                    'klassicheskij-massazh' => 1,
                    'professional' => 2,
                    'urologicheskij' => 3,
                    'tochechnyj' => 4,
                    'jeroticheskij' => 5,
                    'vetka_sakury' => 6,
                    'akva-pennyj' => 7);

$uslugi_bdsm = array('bondazh' => 0,
                    'gospozha' => 1,
                    'rabynja' => 2,
                    'igry' => 3,
                    'dominacija' => 4,
                    'porka' => 5,
                    'fetish' => 6,
                    'trampling' => 7);

$uslugi_extra = array('strapon-klientu' => 0,
                    'strapon-ispolnitelju' => 1,
                    'rimming-anilingus' => 2,
                    'zolotoj-dozhd-vydaju' => 3,
                    'zolotoj-dozhd-priem' => 4,
                    'kopro-vydaju' => 5,
                    'kopro-prinimaju' => 6,
                    'fisting-klass-klientu' => 7,
                    'fisting-klass-ispolnitelju' => 8,
                    'fisting-anal-klientu' => 9,
                    'fisting-anal-ispolnitelju' => 10);

$uslugi_strip = array('profi-striptiz' => 0,
                    'ne-profi-striptiz' => 1,
                    'otkrovennoe-lesbi' => 2,
                    'legkoe-lesbi-shou' => 3);

$uslugi_main = array('klassicheskij' => 0,
                    'analnyj' => 1,
                    'gruppovoj' => 2,
                    'lesbijskij' => 3,
                    'minet' => 4);
                    
$uslugi_add = array('minet-bez-rezinki' => 0,
                    'minet-glubokij' => 1,
                    'kunnilingus' => 2,
                    'igrushki' => 3,
                    'rolevye-igry' => 4,
                    'semejnym-param' => 5,
                    'gejam' => 6,
                    'devushkam' => 7,
                    'okonchanie-na-grud' => 8,
                    'okonchanie-na-lico' => 9,
                    'okonchanie-v-rot' => 10,
                    'foto-video' => 11,
                    'minet-v-mashine' => 12,
                    'jeskort' => 13,
                    'urologija' => 14);