                <div class="wrap_pre_see">
                    <div class="wrap_pre_see_title">Вы смотрели ранее &nbsp;<span>[</span>&nbsp;&nbsp;<a href="#">Полный список</a>&nbsp;&nbsp;<span>]</span></div>
                    <div class="wrap_slider">
                    	<a href="#" class="wrap_slider_left"></a>
                        <div class="slider_img"><a href="#"><img src="img/slider.jpg" width="95" height="134"></a><div><a href="#">Катя, 23 года</a></div></div>
                        <div class="slider_img"><a href="#"><img src="img/slider.jpg" width="95" height="134"></a><div><a href="#">Катя, 23 года</a></div></div>
                        <div class="slider_img"><a href="#"><img src="img/slider.jpg" width="95" height="134"></a><div><a href="#">Катя, 23 года</a></div></div>
                        <div class="slider_img"><a href="#"><img src="img/slider.jpg" width="95" height="134"></a><div><a href="#">Катя, 23 года</a></div></div>
                        <div class="slider_img"><a href="#"><img src="img/slider.jpg" width="95" height="134"></a><div><a href="#">Катя, 23 года</a></div></div>
                        <a href="#" class="wrap_slider_right"></a>
                    </div>
                 </div>
