<?php if ( $this->pageCount>1 ) : ?>
	<?php if(isset($this->previous)) : ?>
		<a href="" class="previouslink prev"></a>
	<?php endif ?>
	<?php 
		$i = ($this->current - 8 > 0 ) ? $this->current - 8 : 1;
	?>
	<? for($i; $i <= $this->current; $i++) : ?>
		<? if ( $i == $this->current) : ?>
			<a href="#" class="current"><?=$this->current?></a>
		<? else: ?>
			<a href="<?=$this->url(array('p'=>$i),'default')?>"><?=$i?></a>
		<? endif; ?>
	<? endfor; ?>
	<?php if(isset($this->next)) : ?>
		<a href="" class="nextlink next"></a>
	<?php endif ?>
<script>
	var link_prev = "<?=$this->url(array('p'=>$this->previous),'default')?>";
	var link_next = "<?=$this->url(array('p'=>$this->next),'default')?>";

	$('.prev').attr('href', link_prev);
	$('.next').attr('href', link_next);
</script>
<?endif?>