<div class="fix_width">
	<div id="main">
		<div class="side_narrow_common_holder">
			<div class="main_title_block">
				<h1 class="float_main_title"><?php echo $this->info['name'] ?></h1>
				<strong class="salon_title_desc"><?php echo $this->info['type'] ?></strong>
				<a class="add_favorites" href="#"><span class="add_favorites_icon"></span>В избранное</a>
			</div>
			<aside id="left_sidebar">
				<ul class="anket_preview_girl">
					 <? if($this->info['photolist']):
                 		foreach($this->info['photolist'] as $thumb):
                	 ?>
                    	<li>
                    		<a href="/watermark.php?image=.<?php echo $thumb['fs'] ?>" onclick="return hs.expand(this, { align : 'center' })">
                    		<img src="/watermark.php?image=.<?=$thumb['fs']?>" width="233" />
                    		</a>
                    	</li>
                 	<?
                   			endforeach; 
                  		 endif;
                	 ?>	
				</ul>
			</aside>
			<div id="narrow_content">
				<div class="ribbon_title_bg">
					<h2>основная информация</h2>
				</div>
				<div class="single_girl_main_info_block">
					<div class="single_girl_main_info_block_l">
						<span class="big_red_phone"></span>
						<ul class="single_girl_from">
							<li><span class="red_col">Санкт-Петербург,</span></li>
							<li><?php echo $this->district_list[$this->info['district']] ?></li>
						</ul>
						<span class="grey_metro"><span class="grey_metro_icon"></span><? $metro = explode(";", $this->info['metro']);  echo $this->metro_list[$metro[0]]; ?></span>
						<h5 style="display: inline-block">Адрес:</h5>&nbsp;<?=$this->info['address']?>
						<ul class="girl_card_info_list black_list">
							<li>Кол. девушек.............<?=$this->info['girl_number']?></li>
							<li>Кол. комнат...............<?=$this->info['room_number']?></li>
							<li>Время работы&nbsp;
								<?php if ( $this->info['time_from'] != 0 && $this->info['time_to'] != 0 ): ?>
                    				c: <?=$this->info['time_from']?> до: <?=$this->info['time_to']?>
                    			<?php else: ?>
                    				24 часа
                    			<?php endif ?>
							</li>
						</ul>
						<!-- <div class="without_ret2"></div> -->
					</div>
					<div class="single_girl_main_info_block_r">
						<div class="salon_card_another_info">
							<!--
							<div class="salon_card_rating_block">
								<div class="salon_card_rating">
									<span class="common_salon_card_rating"><span class="white_star_icon"></span>8.5</span>
									<ul class="rating_stars">
										<li></li>
										<li></li>
										<li></li>
										<li></li>
									</ul>
									<span class="all_voices_text">Всего голосов: 837</span>
								</div>
								<div class="salon_card_revies">
									<span class="green_label">Отзывы пользователей</span>
									<ul class="voices_counter">
										<li><span class="good_voice">+188</span></li>
										<li><span class="voice">1</span></li>
										<li><span class="bad_voice">-0</span></li>
									</ul>
								</div>
							</div>
							<span class="real_individual"><span class="real_individual_icon full"></span>Реальня индивидуалка</span>
							<span class="photo_verified"><span class="photo_verified_icon"></span>Фото проверено</span>
							<h5 class="common_programs">Любимые программы:</h5>
							-->
							<?php
								$this->row = $this->info;
								echo $this->render('_show-services-salon.phtml');
							?>
						</div>
					</div>
				</div>
				<div class="grey_title_box">
					<strong>Тариф:</strong>
				</div>
				<table class="grey_table">
					<thead>
						<tr>
							<td></td>
							<td>Апартаменты</td>
							<td>Выезд</td>
							<td>Анал</td>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><span class="one_hour_icon"></span>1 час</td>
							<td><?if ( $this->info['price_1h_ap'] ):?><?php echo number_format($this->info['price_1h_ap'], 0, ',', '.') . " руб.";?><?endif?></td>
							<td><?if ( $this->info['price_1h_ap'] ):?><?php echo number_format($this->info['price_2h_ap'], 0, ',', '.') . " руб.";?><?endif?></td>
							<td></td>
						</tr>
						<tr>
							<td><span class="two_hour_icon"></span>2 часа</td>
							<td><?if ( $this->info['price_1h_ex'] ):?><?php echo number_format($this->info['price_1h_ex'], 0, ',', '.') . " руб.";?><?endif?></td>
							<td><?if ( $this->info['price_2h_ex'] ):?><?php echo number_format($this->info['price_2h_ex'], 0, ',', '.') . " руб.";?><?endif?></td>
							<td></td>
						</tr>
						<tr>
							<td><span class="all_night_icon"></span>Ночь</td>
							<td><?if ( $this->info['price_n_ap'] ):?><?php echo number_format($this->info['price_n_ap'], 0, ',', '.') . " руб.";?><?endif?></td>
							<td><?if ( $this->info['price_n_ex'] ):?><?php echo number_format($this->info['price_n_ex'], 0, ',', '.') . " руб.";?><?endif?></td>
							<td></td>
						</tr>
					</tbody>
				</table>
				<div class="ribbon_title_bg">
					<h2>Услуги салона</h2>
				</div>
				<div class="additional_skils">
					<?php echo $this->render("salon/_show-services.phtml") ?>
				</div>
				<div class="ribbon_title_bg">
					<h2>Описание салона</h2>
				</div>
				<p><?php echo $this->info['about'] ?></p>
				<div class="salon_ankets">
					<h2>у салона <?php echo $this->ankets->getTotalItemCount() ?> анкет</h2>			
					<ul class="new_ankets">
					<?php foreach( $this->ankets as $row ) :
						$meta_tags=array(
							'name',
							'type',
							'performer',
							'city',
							'metro',
							'age',
							'breast',
							'height',
							'weight'
						);
						$meta_replace=array();
						foreach($meta_tags as $key){$meta_replace[$key]=$row[$key];}
						foreach($meta_tags as $key=>$value){$meta_tags[$key]='%'.strtoupper($value).'%';}
						$meta_img=str_replace($meta_tags,$meta_replace,$this->meta['ank_img_alt']);
						$meta_detail=str_replace($meta_tags,$meta_replace,$this->meta['ank_detail']);
						if(!empty($row['photolist'])){
							$photolist=unserialize($row['photolist']);
							if(isset($photolist['preview'])){$photo=$photolist[$photolist['preview']];}
							else{$photo=array_shift($photolist);}
						}
						else{$photo=false;}
					?>
					<li>
						<a target="_blank" href="/anketa/<?=$row['name_eng']?>-<?=$row['id']?>"><img src="<?=$this->url_user_ph.'/'.$row['user_id'].'/th_'.$photo?>" width="110px" height="110px" /></a>
						<a target="_blank" href="/anketa/<?=$row['name_eng']?>-<?=$row['id']?>" class="new_ankets_girl_name"><?php echo ucfirst($row['name']) . ", " . $row['age']?></a>
						<div class="tooltip">
							<div class="tooltip_corner"></div>
							<div class="tooltip_content">
								<span class="tooltip_girl_name"><a href="#"><?php echo ucfirst($row['name']) ?></a>, <?php echo $row['age'] ?></span>
								<span class="tooltip_girl_place">Россия, <?php echo $this->cities[$row['city']] ?></span>
							</div>
						</div>
					</li>
					<?php endforeach ?>
					</ul>
					<a target="_blank" href="/anketa/<?=$row['name_eng']?>-<?=$row['id']?>" class="button all_list_btn">весь список</a>
				</div>
			</div>
		</div>
		<?= $this->render('index/_sidebar.phtml') ?>
	</div>
</div>
<script type="text/javascript"> 
	<?php if ( $this->info['status'] > 20 && $this->info['active'] ) : ?>	
    	$.get("/remote/phone-salon/n/<?=$this->info['id']?>", function(data){
       		$(".big_red_phone").html(data); 
    	},"");
   	<?php endif ?>
</script>