<?php if( $this->pageCount ){ 
	$params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
	unset($params['module']);
	unset($params['controller']);
	unset($params['action']);
?>
<div class="paginationControl">
	<?php if( isset( $this->previous ) ){ ?>
		<a href="<?php echo $this->url(array_merge(
			$params, array('page' => $this->previous ))); ?>">
			Предидущая	
		</a> |
	<?php } else { ?>
		<span class="disabled"> Предидущая</span> |
	<?php } ?>
	
	<?php foreach($this->pagesInRange as $page){ ?>
		<?php if( $page != $this->current){ ?>
			<a href="<?php echo $this->url(array_merge($params,
				array('page' => $page ))); ?>">
				<?php echo $page; ?>	
			</a> | 
		<?php } else { ?>
			<?php echo $page; ?> |
		<?php }} ?>
		
		<?php if( isset( $this->next ) ){ ?>
			<a href="<?php echo $this->url(
				array_merge($params, array('page' => $this->next))); ?>">
				Следующая
			</a>
		<?php } else { ?>
			<span class="disabled">Следующая</span>
		<?php } ?>	
</div>
<?php } ?>