<?php if( $this->pageCount ) :
	$url = preg_replace("/?cp=\d{1,3}/", "", $_SERVER['REQUEST_URI']) . "?cp=";
?>
<div class="pagination pagination-small">
	<ul>
	<?php if( isset( $this->previous ) ) : ?>
		<li>
			<a href="<?= $url . $this->previous ?>">«</a>
		</li>
	<?php else : ?>
		<li>
			<a href="javascript:void(0)">«</a>
		</li>
	<?php endif; ?>
	<?php foreach($this->pagesInRange as $page) : ?>
		<?php if( $page != $this->current) : ?>
			<li><a href="<?php echo $url . $page ?>"><?php echo $page; ?></a></li>
		<?php else : ?>
			<li><a href="javascript:void(0)" style="background: #e8e8e8"><?= $page; ?></a></li>
		<?php endif; ?>
	<?php endforeach; ?>
	<?php if( isset( $this->next ) ) : ?>
		<li>
			<a href="<?= $url . $this->next ?>">»</a>
		</li>
	<?php else : ?>
		<li>
			<a href="javascript:void(0)">»</a>
		</li>
	<?php endif; ?>
	</ul>
</div>
<?php endif; ?>