            <div class="row">
            <div class="span10">
            <ul class="nav nav-tabs bottom_nav_tabs">
               <li class="<?=($this->menu_sub['active'] == 'default')?'active':''?>"><a href="/" class="bnt1">Все</a></li>
               <li class="<?=($this->menu_sub['active'] == 'st')?'active':''?>"><a href="/?st=50-0" class="bnt2">Фото проверено</a></li>
<!--           <li><a href="#" class="bnt3">Фото без ретуши</a></li>-->
               <li class="<?=($this->menu_sub['active'] == 'v')?'active':''?>"><a href="/?v=1-0" class="bnt4">Анкеты с видео</a></li>
               <li class="<?=($this->menu_sub['active'] == 'rv')?'active':''?>"><a href="/11-prostitutki-s-otzyvami" class="bnt3">С отзывами</a></li>
<!--           <li><a href="#">Ещё один пункт</a></li>-->
            </ul>
        </div>
    </div>
        <?if(isset($this->error)):?>
           <div class="row">
                <div class="span7">
                <div class="other_title"><?=$this->error?></div>
           </div>
        <?endif?>
        <div class="row">
        	<div class="span7">
            	<div class="other_title"><?=$this->info['name']?></div>
            </div>
            <div class="span3 check_bocks">
            	<?if($this->info['photo_check']):?><div class="foto_check"><img src="/img/big_pls.png" width="23" height="20" alt="">фото проверено</div><?endif?>
                <?if(false):?><div class="foto_check_gras"><img src="/img/gras.png" width="18" height="16" alt="">фото без ретуши!</div><?endif?>
            </div>
        </div>
        <div class="row bg_line_other">
        	<div class="span3">
            	<table width="280" border="0" class="price_table">
                  <tr>
                    <td colspan="4" class="head_table">Тарифы:</td>
                  </tr>
                  <tr>
                    <td align="center"><img src="/img/clock.png" width="20" height="21" alt=""></td>
                    <td class="table_column1">Апартаменты</td>
                    <td class="table_column2">Выезд</td>
                    <td class="table_column3">Анал</td>
                  </tr>
                  <tr>
                    <td class="table_row">1 час</td>
                    <td class="price_td"><?=$this->info['price_1h_ap']?></td>
                    <td class="price_td"><?=$this->info['price_1h_ex']?></td>
                    <td class="price_td"><?=$this->info['price_an']?('+ '.$this->info['price_an']) : ' - ' ?></td>
                  </tr>
                  <tr>
                    <td class="table_row">2 часа</td>
                    <td class="price_td"><?=$this->info['price_2h_ap']?></td>
                    <td class="price_td"><?=$this->info['price_2h_ex']?></td>
                    <td class="price_td"><?=$this->info['price_an']?('+ '.$this->info['price_an']) : ' - ' ?></td>
                  </tr>
                  <tr>
                    <td class="table_row">Ночь</td>
                    <td class="price_td"><?=$this->info['price_n_ap']?></td>
                    <td class="price_td"><?=$this->info['price_n_ex']?></td>
                    <td class="price_td"><?=$this->info['price_an']?('+ '.$this->info['price_an']) : ' - ' ?></td>
                  </tr>
                </table>
                <?if($this->info['videolist']):?>
                <div class="left_other_title">Видео:</div>
                    <?while($video=array_shift($this->info['videolist'])):?>
                <div class="wrap_video">
                        <?$swflink = 'file='.$video['fs'].'&image=/img/videoprev.jpg&author=vipsoski.com&description=Видео - на видео проститутка '.$this->info['name'].', тел: '.$this->info['phone']?>
                            <span id="video1" class="br_img01"><embed type="application/x-shockwave-flash" src="/player.swf" width="280" height="280" style="undefined" id="player" name="player" quality="high" allowfullscreen="true" allowscriptaccess="always" flashvars="<?=$swflink;?>"></span>
                            <script type="text/javascript" src="/js/swfobject.js"></script>
                            <script type="text/javascript">
                            var s1 = new SWFObject('/player.swf','player','280','280','9');
                            s1.addParam('allowfullscreen','true');
                            s1.addParam('allowscriptaccess','always');
                            s1.addParam('flashvars','<?=$swflink;?>');
                            s1.write('video1');
                            </script>
                </div>
                    <?endwhile;?>
                
		<?endif?>
<!--                <div class="left_other_title">Расположение:</div>
                <div class="wrap_map"><img src="/img/zagluha2.jpg" width="280" height="240" alt=""></div>
                <div class="left_other_title">Эта девушка от салона:</div>
                <div class="wrap_girl_salon">
                	<div class="girl_salon_img">
                    	<a href="#" class="girl_salon_foto"><img src="/img/left_girl.jpg" width="110" height="154" alt=""></a>
                        <a href="#" class="btn">Подробнее &gt;&gt;</a>
                    </div>
                    <div class="girl_salon_info">
                    	<div class="girl_salon_name">GRAND DELUXE</div>
                        <div class="girl_salon_sity">г. Санкт-Петербург</div>
                        <div class="girl_salon_addres"><a href="#">м. Технологический. институт</a>,  <a href="#">Гражданский пр.</a>, <br><a href="#">Пр. Просвещения</a></div>
                        <div class="girl_salon_price">1 час: <span>3 500</span><br>2 часа: <span>4 500</span><br>Ночь: <span>12 000</span> (Выезд: 15 000)</div>
                    </div>
                </div>-->
<!--                <div class="left_other_title">Реклама:</div>
                <div class="wrap_banner"><a href="#"><img src="/img/left_banner.jpg" alt=""></a></div>-->
            </div>
            <div class="span4">
            	<table width="380" border="0" class="root_table_girl">
                  <tr>
                    <td colspan="2" class="root_tab_girl_head">Параметры:</td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_rtd">Телефон</td>
<!--                    <td><span><?#=$this->phoneFormat($this->info)?></span></td>-->
                    <td id="phone"></td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_td">Город</td>
                    <td>Санкт-Петербург</td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_td">Район</td>
                    <td>Центральный</td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_td">Метро</td>
                    <td><?if(!empty($this->info['metro'])):?><a href="#"><?=$this->info['metro']?></a><?endif?></td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_td">Настоящее имя</td>
                    <td><?=$this->info['name']?></</td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_td">Грудь</td>
                    <td><?=$this->info['breast']?></</td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_td">Вес</td>
                    <td><?=$this->info['weight']?></td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_td">Рост</td>
                    <td><?=$this->info['height']?></td>
                  </tr>
                  <tr>
                    <td class="root_tab_first_td">Возраст</td>
                    <td><?=$this->info['age']?></td>
                  </tr>
                </table>
                <div class="root_girl_info"><?=nl2br($this->info['about'])?></div>
                <div class="root_girl_title">Предпочтения:</div>
                <div class="wrap_rg_param">
                	<?foreach($this->services as $part=>$srv):?><?if(isset($this->part_active[$part])):?>
			<div>
                        <ul>
                        <li><?=array_shift($srv)?></li>
				<?foreach($srv as $num=>$val):?>
				<?if($this->srv_active[$part.'_'.$num]):?><li><?=$val?></li><?endif?>
				<?endforeach?>
			</ul>
                        </div>
			<?endif?><?endforeach?>
                </div>
                <?=$this->render('index/_comments_block.phtml')?>
                <?//=$this->render('shared/ankets_pre_see_slider.phtml')?>
            </div>
            <div class="span3">
            	<div class="wrap_galery">
                    <div id="gallery" data-toggle="modal-gallery" data-target="#modal-gallery">
                    <? if($this->info['photolist']):foreach($this->info['photolist'] as $thumb):?>
                    <a href="<?=$thumb['fs']?>"  data-gallery="gallery"><img src="<?=$thumb['fs']?>" alt=""></a>
                    <? endforeach; endif;?>
                    </div>
                </div>
            </div>
        </div>
               <!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade" tabindex="-1">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn btn-info modal-prev"><i class="icon-arrow-left icon-white"></i> Сюда</a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000"><i class="icon-play icon-white"></i> Слайд-Шоу</a>
        <a class="btn btn-primary modal-next">Туда <i class="icon-arrow-right icon-white"></i></a>
     
    </div>
</div>
<script>
    $('#modal-gallery').on('load', function () {
    var modalData = $(this).data('modal');
    // modalData.$links is the list of (filtered) element nodes as jQuery object
    // modalData.img is the img (or canvas) element for the loaded image
    // modalData.options.index is the index of the current link
    });
    $.get("/remote/phone/n/<?=$this->info['id']?>", function(data){
       $("#phone").html(data); 
    },"");

</script>