<style>
	.errors {
		list-style-type: none;
		color: #b94a48;
		margin-left: 270px;
		margin-top: 5px;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Добавление cалона
		</h3>
	</div>
</div>
<form class="form-horizontal" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span4">
			<div class="widget box red">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>Основные данные</h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascritp:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<? foreach ($this->form as $element): ?>
						<? if ( !preg_match('/service_group(.*)|only|submit/', $element->getName() ) ) :?>
							<?= $element ?>
						<? endif; ?>
					<? endforeach; ?>
				</div>
			</div>
		</div>
		<div class="span8">
			<div class="widget box red">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>Услуги и удобства</h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascript:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<? foreach ($this->form as $element): ?>
						<? if ( preg_match('/service_group(.*)|only/', $element->getName() ) ) :?>
							<?= $element ?>
						<? endif; ?>
					<? endforeach; ?>
				</div>
			</div>
		</div>
	</div>
	<?= $this->form->getElement('submit') ?>
</div>
</form>
<script type="text/javascript">
	window.onload = function () {
		changeView();

		$("#fieldset-worktime > legend").after("<div class='control-group'><label for='24hour' class='control-label optional' style='width: 270px'>24 часа:</label><input type='checkbox' name='24hour' id='24hour' checked='checked' /></div>");
		$("#time_from").attr("disabled", "disabled");
		$("#time_to").attr("disabled", "disabled");	
	}	

	$("#type").change( function (){
		changeView();
	});

	function changeView () {
		type = $("#type").val();
		
		switch ( type ) {
			case '1' :
				$("#fieldset-service_group_intim, #fieldset-priceexinfo, #fieldset-price_ex_i_info").css("display", "block");
				$("#fieldset-service_group_mass, #fieldset-service_group_strip, #fieldset-service_group_bdsm").css("display", "none");
			break;
			case '2' :
				$("#fieldset-service_group_mass, #fieldset-service_group_strip").css("display", "block");
				$("#fieldset-service_group_intim, #fieldset-service_group_bdsm, #fieldset-priceexinfo, #fieldset-price_ex_i_info").css("display", "none");
			break;
			case '3' :
				$("#fieldset-service_group_bdsm").css("display", "block");
				$("#fieldset-service_group_intim, #fieldset-service_group_strip, #fieldset-service_group_mass, #fieldset-priceexinfo, #fieldset-price_ex_i_info").css("display", "none");
			break;
		}
	}

	$("#fieldset-worktime").click(function (){
		if ( $("#24hour").is(":checked") ) {
			$("#time_from").attr("disabled", "disabled");
			$("#time_to").attr("disabled", "disabled");
		} else {
			$("#time_from").removeAttr("disabled");
			$("#time_to").removeAttr("disabled");
		}
	});
</script>
<script type="text/javascript">
	$("select[id='city']").change(function(){
		var metro = [];
			metro['m1'] = new Array("<?= implode('","', $this->content->metro_msk->toArray()) ?>");
			metro['m2'] = new Array("<?= implode('","', $this->content->metro_spb->toArray()) ?>");
		createList2Form(metro, 'metro', 'm');
		var district = [];
			district['d1'] = new Array("<?= implode('","', $this->content->district_msk->toArray()) ?>");
			district['d2'] = new Array("<?= implode('","', $this->content->district_spb->toArray()) ?>");
		createList2Form(district, 'district', 'd')
	});

	$(function () {
		$("input[type=radio], input[type=checkbox]").uniform();
	});
</script>