<div class="center">
	<div id = "centerwrap">
		<h2 class="ank_title">Добавление анкеты <?php echo $this->type_label ?></h2>
		<div id="cab_ankets_wrap" style="padding: 10px;">
			<br />
			<form id="<?= $this->form->getId() ?>" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
				<div class="form">
					<div class="form-left">
        				<? foreach ($this->form as $element): ?>
                			<? if ( !preg_match('/service_group(.*)|only|submit/', $element->getName() ) ) :?>
               	 				<?= $element ?>
               	 			<? endif; ?>
  						<? endforeach; ?>
  					</div>
  					<div class="form-right">
        				<? foreach ($this->form as $element): ?>
        					<? if ( preg_match('/service_group(.*)|only/', $element->getName() ) ) :?>
               	 				<?= $element ?>
               	 			<? endif; ?>
  						<? endforeach; ?>
  					</div>
  					<?= $this->form->getElement('submit') ?>
  				</div>
  			</form>
  		</div>
  	</div>
</div>
<script type="text/javascript">
	$("select[id='city']").change(function(){		
		var metro = [];
			metro['m1'] = new Array("<?= implode('","', $this->content->metro_msk->toArray()) ?>");
			metro['m2'] = new Array("<?= implode('","', $this->content->metro_spb->toArray()) ?>");
		createList2Form(metro, 'metro', 'm');
		var district = [];
			district['d1'] = new Array("<?= implode('","', $this->content->district_msk->toArray()) ?>");
			district['d2'] = new Array("<?= implode('","', $this->content->district_spb->toArray()) ?>");
		createList2Form(district, 'district', 'd')		
	});
</script>