<div id="center"><div id="cab_ankets"><div id="cab_ankets_wrap">
	<ul class="menu" style="margin:5px;">
		<!-- <li><a href="/cabinet/users">Пользователи</a></li> -->
        <li><a href="/cabinet/sections">Категории</a></li>
        <li><a href="/cabinet/uslugi">Услуги</a></li>
        <li><a href="/cabinet/metro-spb">Метро СПБ</a></li>
        <li><a href="/cabinet/metro-msk">Метро МСК</a></li>
        <li><a href="/cabinet/district-spb">Районы СПБ</a></li>
        <li><a href="/cabinet/district-msk">Районы МСК</a></li>
        <li><a href="/cabinet/menu-items">Пункты меню</a></li>
		<li><a href="/cabinet/settings">Настройки</a></li>
		<li><a href="/cabinet/meta">Мета тэги</a></li>
		<li><a href="/cabinet/articles">Статьи</a></li>
		<li><a href="/cabinet/banners">Баннеры</a></li>
		<!-- <li><a href="/cabinet/pay">Пополнить счет</a></li> -->
	</ul>
</div></div></div>
