<div id="center"><div id="cab_ankets"><div id="cab_ankets_wrap">
	<ul class="menu" style="margin:5px;">
		<!-- <li><a href="/cabinet/users">Пользователи</a></li> -->
        <li><a href="/cabinet/sections">Категории</a></li>
        <li><a href="/cabinet/menu-items">Пункты меню</a></li>
		<li><a href="/cabinet/settings">Настройки</a></li>		
		<li><a href="/cabinet/meta">Мета тэги</a></li>
		<li><a href="/cabinet/articles">Статьи</a></li>
		<li><a href="/cabinet/banners">Баннеры</a></li>
		<!-- <li><a href="/cabinet/pay">Пополнить счет</a></li> -->
	</ul>
</div></div></div>
