<div id="center"><div id="cab_ankets">
	<form id="cab_ankets_wrap" class="cab_form" method="post" action="<?=$this->url(array('action'=>isset($this->info)?'art-edit':'art-add'))?>">
		<div class="ca_top ca_bottom">
			<h3>Название статьи:</h3>
			<input type="text" name="title"<?if(isset($this->info['title'])):?> value="<?=$this->info['title']?>"<?endif?> />
			<h3>Текст статьи:</h3>
			<textarea name="text" id="editor"><?if(isset($this->info['text'])):?><?=$this->info['text']?><?endif?></textarea>
		</div>
		<input class="button" type="submit" value="Сохранить" />
	</form>
</div></div>