<style>
	.wrap_photo {
		width: 200px;
		height: 302px;
		margin: 10px 0px 10px 0px;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Фотография для проверки: <?=$this->info['name']?> (<?=$this->cities[$this->info['city']]?>)
		</h3>
	</div>
</div>
<form class="form-horizontal" action="/cabinet/check-photo-add/n/<?=$this->info['id']?>" method="post" enctype="multipart/form-data">
<p>
	<input type="submit" class="btn btn-large" value="Данные анкеты" name="to_ank_edit" />
	<input type="submit" class="btn btn-large" value="Фото" name="to_photo" />
	<input type="submit" class="btn btn-large" value="Видео" name="to_video" />
	<input type="submit" class="btn btn-large" value="Комментарии" name="to_comments">
</p>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget red">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>Услоия проверки</h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div class="alert alert-block alert-info fade in">
						<button data-dismiss="alert" class="close" type="button">×</button>
						<div>
							<h3>Как пройти проверку</h3>
							<p>Для проверки подлинности вашей анкеты и уникальности фотографий загрузите фотографию, на которой Вы держите в руках лист бумаги с датой, написанной от руки. Дата не должна отличаться более чем на 3 дня от текущей даты на момент ее загрузки. Фото должно быть в оригинальном размере, без сжатия и обработки. Не пытайтесь подделывать проверочные фотографии, иначе анкета будет заблокирована. После проверки фотографий анкета будет показываться на сайте. Проверка фото истекает через 3 месяца, после чего необходимо загрузить новую.</p>
							<p>Эта фотография предназначена только для модератора и не будет видна посетителям сайта.</p>
						</div>
						<div>
							<h3>Пишите только дату</h3>
							<p>Остерегайтесь сайтов, требующих указывать на проверочном фото их названия.</p>
							<p>Если на листке только дата Вы сможете заявить, что фото было сделано, например, для сайта знакомств и высылалось кому-то, кто просил прислать подтверждающее фото. Фото с датой (без названия сайта) не указывает на род Ваших занятий и абсолютно ничего не доказывает.</p>
						</div>
						<div>
							<h3>Бесплатно</h3>
							<p>Проверка выполняется бесплатно, срок выполнения: 48 часов.</p>
							<p>Состояние проверки можно отслеживать на данной странице.</p>
						</div>
						<div>
							<h3>Ретушь</h3>
							<p>Если лицо на фото скрыто или заретушировано, необходимо загрузить также фото без ретуши, где видно лицо, именно с данной фотосессии, фото которой загружено в разделе фотографии.</p>				
						</div>	
						<div>
							<h3>Размер и качество проверочной фотографии.</h3>
							<p>К проверке не допускаются сжатые или обработанные фотографии. Загружайте фотографии в самом высоком разрешении и максимальном качестве. Загружаемый файл должен быть не более 3 МБ, формата JPG, GIF, PNG. Минимальное разрешение не менее 800x600px.</p>
						</div>
						<?php foreach($this->info['photolist'] as $key=>$photo): $i++; ?>
						<?if(!$photo):?> 
							<div class="control-group">
								<label class="control-label" style="width: 180px;">Прикрепить фото</label>
								<div class="controls">
									<div data-provides="fileupload" class="fileupload fileupload-new">
										<span class="btn btn-file">
											<span class="fileupload-new">Select file</span>
											<span class="fileupload-exists">Change</span>
											<input type="hidden" name="MAX_FILE_SIZE" value="2097152" id="MAX_FILE_SIZE">
											<input type="file" name="file_<?php echo $key; ?>" class="default">
										</span>
										<span class="fileupload-preview"></span>
										<a style="float: none" data-dismiss="fileupload" class="close fileupload-exists" href="#">×</a>
									</div>
								</div>
							</div>
						<?php endif; ?>
						<?php endforeach ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- moderations -->
	<?php if ( checkIfArrayHasValues($this->moderations) ) :?>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget red">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>Загруженные фото</h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<?php $i = 0;?>
					<?php foreach ( $this->moderations as $moderation ) : ?>
						<?php $photos = unserialize($moderation['photo_check_indexes']) ?>
						<?php foreach ($photos as $photo) : $i++;?>
						<div class="" style="display: inline-block; margin: 10px;">
							<div class="wrap_photo" style="background:url('<?=$this->photos_path.'/th_'.$photo?>') no-repeat scroll center top transparent;"></div>
							<div class="control-group">
								<?if ( $moderation['status'] == 11 ):?>
									<p style="text-align: left; font-weight: bold;" id="failed_photo_check">Отклонена</p>
									<p style="text-align: left;"><?php echo date('Y-m-d H:i', strtotime($moderation['date'])); ?></p>
									<p style="text-align: left;"><?php if ( $moderation['comment'] ) echo $moderation['comment'] ?></p>
								<?endif?>
								<?if ( $moderation['status'] > 20 ):?>
									<p style="text-align: left; font-weight: bold;" id="success_photo_check">Проверка пройдена</p>
									<p style="text-align: left;"><?php echo date('Y-m-d H:i', strtotime($moderation['date'])); ?></p>
								<?endif?>
								<?if ( $moderation['status'] == 20 ):?>
									<p style="text-align: left; font-weight: bold;" id="moderation_photo_check">На модерации</p>
								<?endif?>
							</div>
						</div>
						<?php endforeach; ?>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
	<!-- add photo -->
	<div class="row-fluid">
		<div class="span12">
			<div class="widget red">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>Загрузить проверочные фото</h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div class="control-group" id="wrap_added_photos">
						<?php if ( $_GET['unvalid'] ) : ?>
							<div class="alert alert-block alert-warning fade in">
								<button data-dismiss="alert" class="close" type="button">×</button>
								<h4 class="alert-heading">Загрузите фото большего размера</h4>
								<p>
									Нельзя загружать фото размером меньше чем <?php echo $_GET['width']?> * <?php echo $_GET['height'] ?>
								</p>
							</div>
						<?php endif ?>
						<?php for ($j = $i; $j < ( $i + 5);$j++) : ?>
							<label class="control-label" style="width: 180px;">Прикрепить фото</label>
							<div class="controls cab_anketa_photo">
								<div data-provides="fileupload" class="fileupload fileupload-new">
									<span class="btn btn-file">
										<span class="fileupload-new">Select file</span>
										<span class="fileupload-exists">Change</span>
										<input type="hidden" name="MAX_FILE_SIZE" value="2097152" id="MAX_FILE_SIZE">
										<input type="file" name="photo_check_<?php echo $j ?>" class="default photo">
									</span>
									<span class="fileupload-preview"></span>
									<a style="float: none" data-dismiss="fileupload" class="close fileupload-exists" href="#">×</a>
								</div>
							</div>
						<?php endfor; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php if ( $_GET['new'] ) : ?>
		<input class="btn btn-large" type="submit" value="Далее" id="save" name="next" />
	<?php else : ?>
		<input class="btn btn-large" type="submit" id="save" value="Сохранить"/>
	<?php endif ?>
</div>
</form>