<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Комментарии к анкете
		</h3>
		<h4></h4>
	</div>
</div>
<div class="alert alert-block alert-info fade in">
	<button data-dismiss="alert" class="close" type="button">×</button>
	<h4 class="alert-heading">Скрыть комментарий</h4>
	<p>
		Вы можете скрыть комментарии к анкете, на тот момент когда она показывается в приоритетном(платном) показе
	</p>
</div>
<p>
	<a class="btn btn-large" href="/cabinet/edit-ank-form/id/<?php echo $this->ank_id ?>">Данные анкеты</a>
	<a class="btn btn-large" href="/cabinet/edit-photo/n/<?=$this->ank_id ?>">Фото</a>
	<a class="btn btn-large" href="/cabinet/check-photo/n/<?=$this->ank_id ?>">Фото для проверки</a>
	<a class="btn btn-large" href="/cabinet/edit-video/n/<?=$this->ank_id ?>">Видео</a>
</p>



<div id="center">
	<?if(!empty($this->errors)):?>
		<div class="message">
		<?foreach($this->errors as $error):?>
		<h2><?=$error?></h2>
		<?endforeach?>
		</div>
	<?endif?>
	<div id="cab_ankets">
		<h3 class="h3_cabinet_title">Комментарии к анкете</h3>
		<div style="text-align: left; margin: 10px 0px 10px 5px;">
			<span style="color: #757575">Вы можете скрыть комментарии к анкете, на тот момент когда она показывается в приоритетном(платном) показе</span>
		</div>
		<div class="form-buttons">
			<a href="/cabinet/edit-ank-form/id/<?php echo $this->ank_id ?>">Данные анкеты</a>
			<a href="/cabinet/edit-photo/n/<?=$this->ank_id ?>">Фото</a>
			<a href="/cabinet/check-photo/n/<?=$this->ank_id ?>">Фото для проверки</a>
			<a href="/cabinet/edit-video/n/<?=$this->ank_id ?>">Видео</a>
		</div>
		<div id="cab_ankets_wrap">
		<div class="cab_anketa_header">
			<h2>
				<?=$this->info['name']?> (
				<?=$this->cities[$this->info['city']]?>)
				<?list($phone_p1,$phone_p2)=explode('-',$this->info['phone'])?>
				+7(<?=$phone_p1?>)<?=$phone_p2?>
			</h2>
		</div>
		<?if(count($this->comments)):?>
			<form action="/cabinet/comms-hide-show?ank_id=<?php echo $this->ank_id ?>&cp=<?php echo $_GET['cp'] ?>"  method="POST" name="comms-hide-show" id="comms-hide-show"></form>
			<div class="comments">
			<?foreach($this->comments as $comment):?>
			<div class="comment">
				<h4><?if($this->admin || !$comment['flags'] & 1<<$this->adm_flag):?>
					<!--  <a href="<?=$this->url(array('action'=>'comm-del-req','n'=>$comment['id']))?>" class="del">УДАЛИТЬ</a><?endif?>	-->
					<input form="comms-hide-show" type="checkbox" name="sh_<?php echo $comment['id'] ?>" value="1">
					<?=$comment['user_login']?> | <i><?=date('d.m.y G:i',strtotime($comment['timestamp']))?></i>
				</h4>
				<?php if ( !$comment['hide'] ) : ?>
					<p><?=$comment['text']?></p>
				<?php else : ?>
					<p><del><?=$comment['text']?></del></p>
				<?php endif; ?>
				<a href="#" user_login="<?php echo $comment['user_login'] ?>" class="create_answear">
					<img src="/img/messages.png" alt="Ответить" title="Ответить" />
				</a>
			</div>
			<?endforeach?>
			</div>
			<div class="pages"><?=$this->paginationControl($this->comments,'Sliding','shared/pagination_comm.phtml')?></div>
			<div class="button-block-holder">
				<input type="submit" value="Скрыть отмеченные" class="button button-block" id="comms-hide" form="comms-hide-show" name="comms-show-hide" />
				<input type="submit" value="Показать отмеченные" class="button button-block" id="comms-show" form="comms-hide-show" name="comms-show-hide" />
			</div>
		<?else:?>
			<h4>Нет комментариев</h4>
		<?endif?>
		<form class="cab_form" method="post" action="<?=$this->url(array('action'=>'comm-add','n'=>$this->info['id']))?>">
			<div class="ca_top"><table>
				<tr>
					<th>Введите ваше имя:</th>
					<td><input name="name" value="<?=$this->comm_info['name']?>" /></td>
					<?if($this->admin):?>
					<th>Нельзя удалить:</th>
					<td><input type="checkbox" name="admin_only" /></td>
					<?endif?>
				</tr>	
			</table></div>
			<div class="ca_bottom"><textarea name="text"><?=$this->comm_info['text']?></textarea></div>
			<br />
			<input id="captcha-id" type="hidden" name="id" value="<?=$this->captcha?>" />
			<input id="add_comment_button" class="button" type="submit" value="Отправить" />
		</form>
	</div></div>
</div>
<script type="text/javascript">
	$(".create_answear").click(function (e){
		e.preventDefault();
		var $user_login = $(this).attr('user_login');
		$("textarea[name='text']").text($user_login + ", ");
		
		if ( $(".cab_form").hasClass("form-hidden") ) {
			$(".cab_form").toggleClass("form-hidden");
		}
	});

	$("#add_comment_button").click(function (e){
		e.preventDefault();
  	    var text = $("textarea[name=text]").val();

		$.get("/index/comm-add/n/<?= $this->info['id'] ?>",
			{text: text},
			function (response) {
				$("textarea[name=text]").val('');
			}
		);
	});
</script>