<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Комментарии пользователя: <?php echo $this->user_login ?>
		</h3>
	</div>
</div>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget purple">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i></h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<div class="space15"></div>
						<table class="table table-striped table-hover table-bordered" id="editable-sample">
							<thead>
								<tr>
									<th>Номер анкеты</th>
									<th>Текст</th>
									<th>Дата написания</th>
									<td>Редактирование</td>
								</tr>
							</thead>
							<tbody>
								<?php
									echo $this->partialLoop('cabinet/comments-statistic-row.phtml', $this->paginator); 
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/metro/assets/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/metro/assets/data-tables/DT_bootstrap.js"></script>
<script src="/metro/js/editable-table.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	// init sMenu text for top of table
	var sMenu = 'комментариев на странице';
	EditableTable.init(sMenu);
});
</script>
<script type="text/javascript">
	$(".blocking").easyconfirm({locale: {
		title: 'Заблокировать комментарии?',
		text: 'Хотите продолжить?',
		button: ['Нет', 'Да']
	}});

	$(".activating").easyconfirm({locale: {
		title: 'Активировать комментарии?',
		text: 'Хотите продолжить?',
		button: ['Нет', 'Да']
	}});	
</script>
