<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Комментарии к анкете
			<?=$this->info['name']?> (
			<?=$this->cities[$this->info['city']]?>)
			<?list($phone_p1,$phone_p2)=explode('-',$this->info['phone'])?>
			+7(<?=$phone_p1?>)<?=$phone_p2?>
		</h3>
		<h4></h4>
	</div>
</div>
<div class="alert alert-block alert-info fade in">
	<button data-dismiss="alert" class="close" type="button">×</button>
	<h4 class="alert-heading">Скрыть комментарий</h4>
	<p>
		Вы можете скрыть комментарии к анкете, на тот момент когда она показывается в приоритетном(платном) показе
	</p>
</div>
<p>
	<a class="btn btn-large" href="/cabinet/edit-ank-form/id/<?php echo $this->ank_id ?>">Данные анкеты</a>
	<a class="btn btn-large" href="/cabinet/edit-photo/n/<?=$this->ank_id ?>">Фото</a>
	<a class="btn btn-large" href="/cabinet/check-photo/n/<?=$this->ank_id ?>">Фото для проверки</a>
	<a class="btn btn-large" href="/cabinet/edit-video/n/<?=$this->ank_id ?>">Видео</a>
</p>
<?php if ( checkIfArrayHasValues( $this->comments ) ) :?>
<form action="/cabinet/comms-hide-show?ank_id=<?php echo $this->ank_id ?>&cp=<?php echo $_GET['cp'] ?>" method="POST" name="comms-hide-show" id="comms-hide-show">
<div class="row-fluid">
	<div class="span12">
		<div class="widget red">
			<div class="widget-title">
				<h4><i class="icon-reorder"></i>Комментарии</h4>
				<span class="tools">
					<a class="icon-chevron-down" href="javascript:void(0)"></a>
					<a href="javascript:;" class="icon-remove"></a>
				</span>
				<?php	echo $this->paginationControl($this->comments,'Sliding','partials/pagination-comm.phtml'); ?>
			</div>
			<div class="widget-body">
			<?foreach($this->comments as $comment):?>
				<div class="accordion-group">
					<div class="accordion-heading">
						<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#collapse_<?php echo $comment['id'] ?>">
							<?=$comment['user_login']?> | <i><?=date('d.m.y G:i',strtotime($comment['timestamp']))?></i>
						</a>
					</div>
					<div id="collapse_<?php echo $comment['id'] ?>" class="accordion-body collapse in">
						<div class="accordion-inner">
							<label class="checkbox">
								<input form="comms-hide-show" type="checkbox" name="sh_<?php echo $comment['id'] ?>" value="1" />
								<?php if ( !$comment['hide'] ) : ?>
									<?=$comment['text']?>
								<?php else : ?>
									<del><?=$comment['text']?></del>
								<?php endif; ?>
							</label>
						</div>
					</div>
				</div>
			<?endforeach?>
			</div>
		</div>
	</div>
	<input type="submit" class="btn btn-large btn-danger" value="Скрыть отмеченные"  id="comms-hide" name="comms-show-hide" />
	<input type="submit" class="btn btn-large" value="Показать отмеченные" id="comms-show" name="comms-show-hide" />
</div>
</form>
<?php endif ?>
<form  class="form-horizontal" method="post" action="<?=$this->url(array('action'=>'comm-add','n'=>$this->info['id']))?>">
<div class="row-fluid">
	<div class="span12">
		<div class="widget red">
			<div class="widget-title">
				<h4><i class="icon-reorder"></i>Добавить комментарий</h4>
				<span class="tools">
					<a class="icon-chevron-down" href="javascript:void(0)"></a>
					<a href="javascript:;" class="icon-remove"></a>
				</span>
			</div>
			<div class="widget-body">
				<div class="control-group">
					<label for="name" class="control-label" style="width: 270px">Введите ваше имя:</label>
					<input type="text" name="name" value="<?=$this->comm_info['name']?>" id="name">
				</div>
				<!-- 
				<div class="control-group" id="sauna-service">
					<label class="checkbox">
						<strong>Нельзя удалить:</strong>
						<input type="checkbox" name="admin_only" />
					</label>
				</div>
				-->
				<div class="control-group">
					<label for="about" class="">Текст сообщения</label>
					<textarea name="text" class="span12" rows="9" cols="41"><?=$this->comm_info['text']?></textarea>
				</div>
			</div>
		</div>
	</div>
	<input id="add_comment_button" class="btn btn-large" type="submit" value="Отправить" />
</div>
</form>
<script type="text/javascript">
$(function () {
	$("input[type=radio], input[type=checkbox]").uniform();
});
</script>
<script type="text/javascript">
	$(".create_answear").click(function (e){
		e.preventDefault();
		var $user_login = $(this).attr('user_login');
		$("textarea[name='text']").text($user_login + ", ");
		
		if ( $(".cab_form").hasClass("form-hidden") ) {
			$(".cab_form").toggleClass("form-hidden");
		}
	});

	$("#add_comment_button").click(function (e){
		e.preventDefault();
  	    var text = $("textarea[name=text]").val();

		$.get("/index/comm-add/n/<?= $this->info['id'] ?>",
			{text: text},
			function (response) {
				$("textarea[name=text]").val('');
				$("input[name=name]").val('');
			}
		);
	});
</script>