<style>
	.errors {
		list-style-type: none;
		color: #b94a48;
		margin-left: 180px;
		margin-top: 5px;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Связь с администрацией
		</h3>
	</div>
</div>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget box green">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i></h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevrone-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<form method="<?= $this->form->getMethod() ?>" enctype="multipart/form-data" class="form-horizontal">
						<div class="tab-content">
							<? if ( $this->message == Form_NewMessageForm::SUCCESS ) :?>
								<div class="alert alert-success">
									<button class="close" data-dismiss="alert">×</button>
									<strong>Успешно!</strong>&nbsp;<?php echo $this->message ?>
						 		</div>
						 		
							<? elseif ( $this->message == Form_NewMessageForm::FAILED ) : ?>
								<div class="alert alert-error">
									<button class="close" data-dismiss="alert">×</button>
									<strong>Ошибка!</strong>&nbsp;<?php echo $this->message ?>
								</div>
							<? endif ?>
							<? foreach ($this->form as $element): ?>
								<? if ( !preg_match('/submit|upload/', $element->getName() ) ) :?>
									<?= $element ?>
								<? endif ?>
								<? endforeach; ?>
								<div class="control-group">
                            		<label class="control-label" style="width: 180px;">Прикрепить фото</label>
                                	<div class="controls">
                                        <div data-provides="fileupload" class="fileupload fileupload-new">
                                            <span class="btn btn-file">
                                            <span class="fileupload-new">Select file</span>
                                            <span class="fileupload-exists">Change</span>
                                            <input type="hidden" name="MAX_FILE_SIZE" value="2097152" id="MAX_FILE_SIZE">
                                            <input type="file" name="upload" class="default">
                                            </span>
                                            <span class="fileupload-preview"></span>
                                            <a style="float: none" data-dismiss="fileupload" class="close fileupload-exists" href="#">×</a>
                                        </div>
									</div>
								</div>
							<?= $this->form->getElement('submit') ?>
						</div>
					</form>	
				</div>
			</div>
		</div>
	</div>
</div>
