<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Удаление анкеты
		</h3>
	</div>
</div>
<div class="alert alert-block alert-error fade in">
	<button data-dismiss="alert" class="close" type="button">×</button>
	<h4 class="alert-heading">Вы уверены, что хотите удалить анкету "<?=$this->info['name']?>" ?</h4>
	<p>
		Анкета будет удалена немедленно без возможности её восстановления. Так же будут удалены все фотографии связаные с анкетой без возможности их возврата
	</p>
</div>
<form class="form-horizontal" action="/cabinet/del-ank-conf/n/<?=$this->info['id']?>">
	<input class="btn btn-large btn-danger" type="submit" value="Удалить">
</form>