<div class="center">
	<div id = "centerwrap" >
		<h3 class="ank_title">Анкета <?php echo $this->type_label ?></h3>
		<div id="cab_ankets_wrap" style="padding: 10px;">
			<br />
			<div class="form-links">
				<a href="/cabinet/edit-photo/n/<?=$this->id?>">Фото</a>
				<a href="/cabinet/check-photo/n/<?=$this->id?>">Фото для проверки</a>
				<a href="/cabinet/edit-video/n/<?=$this->id?>">Видео</a>			
			</div>
			<form id="<?= $this->form->getId() ?>" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
				<div class="form">
					<div class="form-left">
        				<? foreach ($this->form as $element): ?>
                			<? if ( !preg_match('/service_group(.*)|only|submit/', $element->getName() ) ) :?>
               	 				<?= $element ?>
               	 			<? endif; ?>
  						<? endforeach; ?>
  					</div>
  					<div class="form-right">
        				<? foreach ($this->form as $element): ?>
        					<? if ( preg_match('/service_group(.*)|only/', $element->getName() ) ) :?>
               	 				<?= $element ?>
               	 			<? endif; ?>
  						<? endforeach; ?>
  					</div>
  					<?= $this->form->getElement('submit') ?>  				
  				</div>
  			</form>
  		</div>
  	</div>
</div>