<style>
	.errors {
		list-style-type: none;
		color: #b94a48;
		margin-top: 5px;
	}
	
	.hide-service {
		display: none;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Редактирование анкеты <?php echo $this->type_label ?>
		</h3>
	</div>
</div>
<p>
	<a class="btn btn-large" href="/cabinet/edit-photo/n/<?=$this->id?>">Фото</a>
	<a class="btn btn-large" href="/cabinet/check-photo/n/<?=$this->id?>">Фото для проверки</a>
	<a class="btn btn-large" href="/cabinet/edit-video/n/<?=$this->id?>">Видео</a>
	<a class="btn btn-large" href="/cabinet/comms-list/n/<?php echo $this->id ?>">Комментарии</a>
</p>

<form class="form-horizontal" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span4">
			<div class="widget box red">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>Основные данные</h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascritp:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<? foreach ($this->form as $element): ?>
						<? if ( !preg_match('/service_group(.*)|only|submit|hidden_message/', $element->getName() ) ) :?>
							<?= $element ?>
						<? endif; ?>
					<? endforeach; ?>
				</div>
			</div>
		</div>
		<div class="span8">
			<div class="widget box red">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>Услуги</h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascript:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body" id="widget-body-add-here">
					<? foreach ($this->form as $element): ?>
						<? if ( preg_match('/service_group(.*)|only|hidden_message/', $element->getName() ) ) :?>
							<?= $element ?>
						<? endif; ?>
					<? endforeach; ?>
					<div class="control-group">
						<button id="add_only" class="btn"><i class="icon-plus"></i></button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?= $this->form->getElement('submit') ?>
</div>
</form>
<script type="text/javascript">
	$(document).ready(function(){
		$("input[name='name_eng']").parent().before('<div class="control-group"><p><label>Информация для иностранцев цены должны быть указаны в долларах США</label></p></div>');
	});
</script>
<script type="text/javascript">
	$("#add_only").click(function(e){
		e.preventDefault();	

		var $val = $("input[name='only_count']").val();

		$('#widget-body-add-here').append("<div class='control-group'>");
		$('#widget-body-add-here').append("<label for='only' class='control-label optional' style='width: 270px'>Только у меня</label>");
		$('#widget-body-add-here').append("<input type='text' name='only_" + $val + "' value='' filter='StringTrim'>");
		$('#widget-body-add-here').append("</div>");

		$("input[name='only_count']").val(parseInt($val)+1);
	});
</script>
<script type="text/javascript">
	$("input[name$='_add']").change(function(){
		var $el_id = $(this).attr('id') + "_input";
		console.log($el_id);
		
		if ( $('#' + $el_id).attr('disabled') ) {
			$('#' + $el_id).removeAttr('disabled');
		} else {
			$('#' + $el_id).attr('disabled', 'disabled');
		}
	});

	$(document).ready(function(){
		$("input[name$='_add_input']").each(function(){
			if ( $(this).val() ) {
				$(this).removeAttr('disabled');
			}
		});
	});
</script>
<script type="text/javascript">
	$("select[name='place']").change(function(){
		var $val = $(this).val();

		//debug
		//console.log($val);
		if ( $val == 2 || $val == 3 ) {
			$("#sauna-service").removeClass('hide-service');
		} else {
			$("#sauna-service").addClass('hide-service');
		}
	});

	$(function () {
		$("input[type=radio], input[type=checkbox]").uniform();
	});	

	$(document).ready(function(){
		var $val = $("select[name='place']").val();

		if ( $val == 2 || $val == 3 ) {
			$("#sauna-service").removeClass('hide-service');
		}
	});
</script>