<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">Финансовая отчетноcть</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="navbar navbar-static" id="">
        	<div class="navbar-inner">
            	<div style="width: auto;" class="container">
                    <ul role="navigation" class="nav">
                    	<li class="<?= $_GET['filter'] == 0 ? "active" : null ?>">
							<a href="/cabinet/finance-statistic?filter=0">За сегодня</a>
                    	</li>
                        <li class="<?= $_GET['filter'] == 1 ? "active" : null ?>">
							<a href="/cabinet/finance-statistic?filter=1">Неделю</a>
                        </li>
                        <li class="<?= $_GET['filter'] == 2 ? "active" : null ?>">
							<a href="/cabinet/finance-statistic?filter=2">Месяц</a>
                        </li>
                        <li class="<?= $_GET['filter'] == 3 ? "active" : null ?>">
							<a href="/cabinet/finance-statistic?filter=3">Квартал (3 мес.)</a>
                        </li>
                    </ul>
                </div>
            </div>
    	</div>
	</div>
</div>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget purple">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i></h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<div class="space15"></div>
						<table class="table table-striped table-hover table-bordered" id="editable-sample">
							<thead>
								<tr>
									<th>Сумма</th>
									<th>Откуда (WMR)</th>
									<th>Откуда (WMID)</th>
									<th>Куда (WMR)</th>
									<th>Дата перевода</th>
									<th>Внутренний номер покупки</th>
									<th>Внутренний номер счета(WM)</th>
									<th>Внутренний номер перевода(WM)</th>
								</tr>
							</thead>
							<tbody>
								<?php
									echo $this->partialLoop('cabinet/finance-statistic-row.phtml', $this->paginator);	
								?>
							</tbody>
							<tfoot>
								<th>Итог: <?php echo $this->summ?></th>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/metro/assets/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/metro/assets/data-tables/DT_bootstrap.js"></script>
<script src="/metro/js/editable-table.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	// init sMenu text for top of table
	var sMenu = 'отчетов на странице';
	EditableTable.init(sMenu);
});
</script>