<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Стоимость размещения анкет и салонов
		</h3>
	</div>
</div>
<div id="page-wraper">
	<form action="<?=$this->url(array(action=>'finance-settings-write'))?>" class="form-horizontal" method="post">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget box green">
				<div class="widget-title">
					<h4>
						<i class="icon-reorder"></i>
						Стоимость размещения анкет (ед. сутки)
					</h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascript:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div class="row-fluid">
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Девушки</label>
								<div class="controls">
									<input type="text" class="input-large" name="girl_hour_price" <?if(isset($this->data['girl_hour_price'])):?>value="<?=$this->data['girl_hour_price']?>" <?endif?>>
									<span class="help-inline">Стоимость (сутки)</span>
								</div>
							</div>
						</div>
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Девушки</label>
								<div class="controls">
									<input type="text" class="input-large" name="girl_hour_discount" <?if (isset($this->data['girl_hour_discount'])):?>value="<?=$this->data['girl_hour_discount']?>"<?endif?>>
									<span class="help-inline">Скидка</span>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Подружки</label>
								<div class="controls">
									<input type="text" class="input-large" name="lesb_hour_price" <?if(isset($this->data['lesb_hour_price'])):?>value="<?=$this->data['lesb_hour_price']?>" <?endif?>>
									<span class="help-inline">Стоимость (сутки)</span>
								</div>
							</div>
						</div>
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Подружки</label>
								<div class="controls">
									<input type="text" class="input-large" name="lesb_hour_discount" <?if (isset($this->data['lesb_hour_discount'])):?>value="<?=$this->data['lesb_hour_discount']?>"<?endif?>>
									<span class="help-inline">Скидка</span>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Массажистки</label>
								<div class="controls">
									<input type="text" class="input-large" name="mass_hour_price" <?if(isset($this->data['mass_hour_price'])):?>value="<?=$this->data['mass_hour_price']?>" <?endif?>>
									<span class="help-inline">Стоимость (сутки)</span>
								</div>
							</div>
						</div>
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Массажистки</label>
								<div class="controls">
									<input type="text" class="input-large" name="mass_hour_discount" <?if (isset($this->data['mass_hour_discount'])):?>value="<?=$this->data['mass_hour_discount']?>"<?endif?>>
									<span class="help-inline">Скидка</span>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
							<div class="control-group">
								<label class="control-label">БДСМ</label>
								<div class="controls">
									<input type="text" class="input-large" name="bdsm_hour_price" <?if(isset($this->data['bdsm_hour_price'])):?>value="<?=$this->data['bdsm_hour_price']?>" <?endif?>>
									<span class="help-inline">Стоимость (сутки)</span>
								</div>
							</div>
						</div>
						<div class="span6">
							<div class="control-group">
								<label class="control-label">БДСМ</label>
								<div class="controls">
									<input type="text" class="input-large" name="bdsm_hour_discount" <?if (isset($this->data['bdsm_hour_discount'])):?>value="<?=$this->data['bdsm_hour_discount']?>"<?endif?>>
									<span class="help-inline">Скидка</span>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Мужчина</label>
								<div class="controls">
									<input type="text" class="input-large" name="man_hour_price" <?if(isset($this->data['man_hour_price'])):?>value="<?=$this->data['man_hour_price']?>" <?endif?>>
									<span class="help-inline">Стоимость (сутки)</span>
								</div>
							</div>
						</div>
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Мужчина</label>
								<div class="controls">
									<input type="text" class="input-large" name="man_hour_discount" <?if (isset($this->data['man_hour_discount'])):?>value="<?=$this->data['man_hour_discount']?>"<?endif?>>
									<span class="help-inline">Скидка</span>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Мужчина</label>
								<div class="controls">
									<input type="text" class="input-large" name="trans_hour_price" <?if(isset($this->data['trans_hour_price'])):?>value="<?=$this->data['trans_hour_price']?>" <?endif?>>
									<span class="help-inline">Стоимость (сутки)</span>
								</div>
							</div>
						</div>
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Мужчина</label>
								<div class="controls">
									<input type="text" class="input-large" name="trans_hour_discount" <?if (isset($this->data['trans_hour_discount'])):?>value="<?=$this->data['trans_hour_discount']?>"<?endif?>>
									<span class="help-inline">Скидка</span>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Пары</label>
								<div class="controls">
									<input type="text" class="input-large" name="pair_hour_price" <?if(isset($this->data['pair_hour_price'])):?>value="<?=$this->data['pair_hour_price']?>" <?endif?>>
									<span class="help-inline">Стоимость (сутки)</span>
								</div>
							</div>
						</div>
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Пары</label>
								<div class="controls">
									<input type="text" class="input-large" name="pair_hour_discount" <?if (isset($this->data['pair_hour_discount'])):?>value="<?=$this->data['pair_hour_discount']?>"<?endif?>>
									<span class="help-inline">Скидка</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<div class="widget box purple">
				<div class="widget-title">
					<h4>
						<i class="icon-reorder"></i>
						Стоимость размещения салонов (ед. сутки
					</h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascript:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div class="row-fluid">
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Салон</label>
								<div class="controls">
									<input type="text" class="input-large" name="salon_hour_price" <?if(isset($this->data['salon_hour_price'])):?>value="<?=$this->data['salon_hour_price']?>" <?endif?>>
									<span class="help-inline">Стоимость (сутки)</span>
								</div>
							</div>
						</div>
						<div class="span6">
							<div class="control-group">
								<label class="control-label">Салон</label>
								<div class="controls">
									<input type="text" class="input-large" name="salon_hour_discount" <?if (isset($this->data['salon_hour_discount'])):?>value="<?=$this->data['salon_hour_discount']?>"<?endif?>>
									<span class="help-inline">Скидка</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<input type="submit" class="btn btn-large" name="submit" id="submit" value="Сохранить">
	</form>
</div>