<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Салон добавлен!
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="alert alert-block alert-success fade in">
			<button data-dismiss="alert" class="close" type="button">×</button>
			<p>Ваша анкета салона добавлена на сайт и ожидает модерации. Также вы можете привязать к салону ваши анкеты индивидуалок, во вкладке "Анкеты" салона.</p>
			<p>После проверки модератором вам необходимо включить приоритетный показ, чтобы анкета салона появилась на сайте.</p>
			<p>Размещение анкет салонов платное. Условия размещения читайте в разделе биллинга - меню "Пополнить баланс".</p>
		</div>
	</div>
</div>
<input type="submit" class="btn btn-large" id="redirect" value="Продолжить">
<script type="text/javascript">
	$('#redirect').click(function(e){
		e.preventDefault();	
		window.location.href= '/cabinet/salons/';
	})
</script>