<div id="center">
	<div id="cab_ankets">
		<div id="cab_ankets_wrap">
			<p>Ваша анкета салона добавлена на сайт и ожидает модерации. Также вы можете привязать к салону ваши анкеты индивидуалок, во вкладке "Анкеты" салона.</p>
			<p>После проверки модератором вам необходимо включить приоритетный показ, чтобы анкета салона появилась на сайте.</p>
			<p>Размещение анкет салонов платное. Условия размещения читайте в разделе биллинга - меню "Пополнить баланс".</p>
			<div class="ancher_wrapper">
				<input type="submit" class="submit" id="redirect" value="Продолжить">
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#redirect').click(function(e){
		e.preventDefault();	
		window.location.href= '/cabinet/salons/';
	})
</script>