<style>
	.widget-wrap-photo {
		display: inline-block;
	}

	.portlet-scroll-2 {
		display: inline-block;
		height: 280px;
	}

	.photo_glass {
		background: none repeat scroll 0 0 rgba(255, 255, 255, 0.5);
		bottom: 0;
		top: 0;
		left: 0;
		right: 0;
		position: absolute;
	}
	
	h2 {
		margin: 0px;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			<? if ( ($this->user_moder || $this->admin) && preg_match('/\/cabinet\/ank-moderation(.*)/', $_SERVER['REQUEST_URI']) ) : ?>
				Анкеты <?php echo $this->getUserLoginById($this->user_id); ?>
			<?php else : ?>
				Анкеты
		<?php endif ?>
		</h3>
	</div>
</div>
<? if ( !preg_match('/\/cabinet\/ank-moderation(.*)/', $_SERVER['REQUEST_URI']) ) : ?>
<div class="row-fluid">
	<div class="span12">
		<div class="navbar navbar-static" id="">
			<div class="navbar-inner">
				<div style="width: auto;" class="container">
					<ul role="navigation" class="nav">
						<li <?php if ( $_GET['filter'] == 'all' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=all" ?>">ВСЕГО АНКЕТ: <?=$this->all ?></a></li>
						<li <?php if ( $_GET['filter'] == 'active' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=active" ?>">ИЗ НИХ АКТИВНЫХ (ПОКАЗЫВАЮТСЯ): <?=$this->active?></a></li>
						<li <?php if ( $_GET['filter'] == 'paid' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=paid" ?>">ПРИОРИТЕТНЫХ (ОПЛАЧИВАЕМЫХ): <?=$this->paid?></a></li>
						<li <?php if ( $_GET['filter'] == 'free' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=free" ?>">БЕСПЛАТНЫХ: <?=$this->active-$this->paid?></a></li>
						<li <?php if ( $_GET['filter'] == 'not_active' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=not_active" ?>">СНЯТЫ С ПОКАЗА (ВЫКЛЮЧЕНЫ): <?=$this->all-$this->active?></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<?php if($this->user_id) : ?>
	<div class="pull-left">
		<p>Ваш баланс: <strong><?=number_format($this->balance, 0, ',', ' ');?> р.</strong>&nbsp;Суточный расход: <strong><?=number_format($this->spend, 0, ',', ' ');?> р.</strong></p>
		<?php if ( $this->forecast ) : ?>
			<p>Дата отключения(прогноз): <strong><?php echo $this->forecast ?></strong></p>
		<?php endif ?>
	</div>
<?php endif; ?>
<? endif ?>
<?if ($this->admin && $this->all_anks && !empty($this->users)):?>
		<div  class="controls" style="text-align: right;">
			<script type="text/javascript">
				function redirect(sel) {
					var $uri = "<?=$this->getRightUri( $_GET, true, true )?>";
					$uri = $uri.replace(/(&?uid=\d{1,3}&?)/, '');
					$uri = $uri + "uid=" + $("select[name='uid']").val();
					window.location.href= $uri;
				}
			</script>
			<select name="uid" onchange="redirect(this)" class="input-large m-wrap">
				<option value="0">Выбрать пользователя</option>
				<?foreach($this->users as $u):?>
					<option value=<?=$u['id']?> <?if($_REQUEST['uid']==$u['id']):?>selected<?endif?>><?=$u['user_login']?></option>
				<?endforeach?>
			</select>
	</div>
<?endif?>
<?php if ( $this->ankets->count() > 1 ) : ?>
	<div class="pull-right"><?=$this->paginationControl($this->ankets,'Sliding','pages_cab.phtml')?></div>
<?php endif ?>
<div id="page-wraper">
	<?foreach($this->ankets as $row):?>
	<?php
		if(!empty($row['photolist'])){
			$photolist = unserialize($row['photolist']);
			if(isset($photolist['preview'])){
				$photo=$photolist[$photolist['preview']];
			}
			else{$photo=array_shift($photolist);}
		}
		else{$photo=false;}

		if ( !empty($row['photo_check']) ) {
			$photo_check = array_filter(unserialize($row['photolist']));
			$photo_check = array_shift($photo_check);
		} else {
			$photo_check = false;
		}
	?>
	<div class="row-fluid">	
		<div class="span12">
			<div class="widget box <?if( $row['active'] == 0 || $row['status'] == 1 || $row['status'] == 2 ):?>black<?elseif($row['status']==40):?>orange<?else:?>red<?endif?>">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>
						<?=$row['name']?> (
						<?=$this->cities[$row['city']]?>)
						<?list($phone_p1,$phone_p2)=explode('-',$row['phone'])?>
						+7(<?=$phone_p1?>)<?=$phone_p2?>
					</h4>
                    <span class="tools">
                    	<a href="javascript:;" class="icon-chevron-down"></a>
                        <a href="javascript:;" class="icon-remove"></a>
                    </span>
				</div>
				<div class="widget-body">
					<div class="row-fluid">
						<p>
							<a href="/cabinet/edit-ank-form/id/<?=$row['id']?>" class="btn">Редактировать</a>
							<a href="/cabinet/edit-photo/n/<?=$row['id']?>" class="btn">Фото</a>
							<a href="/cabinet/check-photo/n/<?=$row['id']?>" class="btn" title="Фотография подтверждающая подлинность анкеты">Фото для проверки</a>
							<a href="/cabinet/edit-video/n/<?=$row['id']?>" class="btn">Видео</a>
							<a href="/cabinet/intim-map/n/<?=$row['id']?>" class="btn">Интим-карта</a>
							<a href="/cabinet/comms-list/n/<?=$row['id']?>" class="btn">Комментарии</a>
						</p	>
						<div class="span2" style="width: 200px; margin-left: 0px; position: relative;">
							<?if ( $row['active'] == 0 ) : ?><div class="photo_glass"></div><?php endif ?>
							<a href="/anketa/<?php echo $row['name_eng'] ?>-<?php echo  $row['id'] ?>" target="_blank">
								<div<?if($photo):?> style="background:url('<?=$this->photos_path.'/'.$row['user_id'].'/th_'.$photo?>') no-repeat top; width: 185px; height: 280px;" <?endif?>></div>
							</a>
						</div>
						<div class="span2" style="width: 200px; margin-left: 10px; position: relative;">
							<h2>Просмотры</h2>
							<div>
								<?php
									$counters = new CountersAnkets();
									$counter = $counters->get_ank($row['id']);
								?>
								<table width="100%">
									<tr>
										<td><strong>За 24 часа:</strong></td>
										<td><span class="badge badge-important offset"><?= $counter['today'] ? $counter['today'] : 0 ?></span><td>
									</tr>
									<tr>
										<td><strong>За неделю:</strong></td>
										<td><span class="badge badge-important offset"><?= $counter['week'] ? $counter['week'] : 0 ?></span><td>
									</tr>
									<tr>
										<td><strong>За месяц:</strong></td>
										<td><span class="badge badge-important offset"><?= $counter['month'] ? $counter['month'] : 0 ?></span><td>
									</tr>
									<tr>
										<td><strong>Всего:</strong></td>
										<td><span class="badge badge-important offset"><?= $counter['all'] ? $counter['all'] : 0 ?></span><td>
									</tr>
								</table>
							</div>
							<div style="margin-top: 10px;">
								<strong>Добавлена: </strong>
								<p><?= rusdate(strtotime($row['timestamp'])); ?></p>
							</div>
							<div>
								<? if ( $row['photo_start'] != '0000-00-00 00:00:00' ) : ?>
								<strong>Фото проверено:</strong>
								<p><?= rusdate(strtotime($row['photo_start'])); ?></p>
								<? endif; ?>
							</div>
							<div>
								<? if ( $row['photo_finish'] != '0000-00-00 00:00:00' && $row['status'] > 20 ) : ?>
								<strong>Проверка фото истекает:</strong>
								<p><?= rusdate(strtotime($row['photo_finish'])) ?></p>
								<? endif ?>
							</div>
						</div>
						<? if ( ($this->user_moder || $this->admin) && preg_match('/\/cabinet\/ank-moderation(.*)/', $_SERVER['REQUEST_URI']) ) : ?>
						<div class="span4">
							<?if($row['active']==0):?><h2 title="Анкета выключена">АНКЕТА ВЫКЛЮЧЕНА</h2>
							<?elseif($row['status']==10):?><h2 title="Не загружены фото">Не ПОЛНЫЕ ДАННЫЕ</h2>	
							<?elseif($row['status']==11):?><h2 title="Откланена модератором">ОТКЛОНЕНА МОДЕРАТОРОМ(ПРОВЕРОЧНОЕ ФОТО)</h2>
							<?elseif($row['status']==12):?><h2 title="Откланена модератором">ОТКЛОНЕНА МОДЕРАТОРОМ(НЕ ПОЛНАЯ ИФОРМАЦИЯ)</h2>
							<?elseif($row['status']==1):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
							<?elseif($row['status']==2):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
							<?elseif($row['status']==20):?><h2 title="Анкета на модерации">НА МОДЕРАЦИИ</h2>
							<?elseif($row['status']==30):?><h2 title="Анкета показывается на сайте">ИДЕТ ПОКАЗ</h2>	
							<?elseif($row['status']==40):?><h2 title="Анкета в приорететном показе на сайте">ИДЕТ ПРИОРИТЕТНЫЙ ПОКАЗ</h2>
							<? endif; ?>
							<form action="/cabinet/ank-status-set/n/<?=$row['id'] . $this->getRightUri( $_GET ) ?>" method="post" class="form-horizontal">
								<div class="control-group">
									<select name="s" onchange="if (this.value) { showComment(this.value, this) }">
										<option value="0">Выберите</option>
										<option value="12">Отклонить(неполные данные)</option>
										<option value="11">Отклонить фото</option>
										<option value="30">Разрешить фото</option>
										<option value="31">Фото без ретуши</option>
										<option value="1">Заблокировать</option>
										<option value="2">Заблокировать (черный список)</option>
									</select>
									<input type="submit" value="применить" class="btn" id="submit_status">
									<div id="comment" style="display: none;">
										<label for="comm_texarea">	
											Комментарий (обязательно):
										</label>
										<textarea id="comm_textarea" name="comm" cols="25" rows="8" class="input-xxlarge" ></textarea>
									</div>
								</div>
								<div class="control-group">
									<a href="/anketa/<?php echo $row['name_eng'] ?>-<?php echo  $row['id'] ?>" target="_blank" class="btn">Смотреть</a>
								</div>
							</form>
						</div>
						<? else :?>
						<div class="span4">
							<?if($row['active']==0):?><h2 title="Анкета выключена">АНКЕТА ВЫКЛЮЧЕНА</h2>
							<?elseif($row['status']==10):?>
							<h2 title="Не загружены фото">НЕ ПОЛНЫЕ ДАННЫЕ</h2>
							<?php if ( !$this->isHaveRequiredPhotos( $row['id'], 3 ) ) : ?><h3>Загрузите минимум 3 фото!</h3><?php  endif ?>
							<?php if ( !$this->isHavePhotoCheck( $row['id'] ) ) : ?><h3>Загрузите проверочную фотографию!</h3><?php endif ?>
							<?php if ( $this->isHaveRequiredPhotos( $row['id'], 3 ) && $this->isHavePhotoCheck( $row['id'] ) ) : ?><h3>Загрузите новую проверочную фотографию!</h3><?php endif ?>					
							<?elseif($row['status']==11):?>
							<h2 title="Отклонена модератором">ОТКЛОНЕНА</h2>
							<h3>Проверочное фото не прошло проверку</h3>
							<?elseif($row['status']==12):?>
							<h2 title="Отклонена модератором">ОТКЛОНЕНА</h2>
							<h3>Не полная информация</h3>
							<h4>Результат проверки читайте в моих сообщениях. После изменений отправте на модерацию повторно.</h4>
							<a class="btn" href="/cabinet/to-moderation/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>">На модерацию</a>
							<?elseif($row['status']==20):?><h2 title="Анкета на модерации">НА МОДЕРАЦИИ</h2>
							<?elseif($row['status']==1):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
							<?elseif($row['status']==2):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
							<?elseif($row['status']==30):?>
							<h2 title="Анкета показывается на сайте">ИДЕТ ПОКАЗ</h2>
							<h4><?= $this->showPosition($this->per_page, false, $row['performer'], $row['id']) ?></h4>
							<?elseif($row['status']==40):?>
							<h2 title="Анкета в приорететном показе на сайте" style="color: #F37B53">ИДЕТ ПРИОРИТЕТНЫЙ ПОКАЗ</h2>
							<h4><?= $this->showPosition($this->per_page, true) ?></h4>
							<? endif; ?>
							<div class="pull_down_cab_ank_panel">
							<form action="/cabinet/priority-write/n/<?=$row['id'] . $this->getRightUri( $_GET ) ?>" method="post" class="form-horizontal">
								<div class="control-group">
									<label class="control-label">Приоритетный показ:</label>
									<select name="pr">
										<option value="0"<?if($row['priority']==0):?> selected<?endif?>>Выключен</option>
										<option value="1"<?if($row['priority']==1):?> selected<?endif?>>Включен</option>
									</select>
									<input type="submit" value="применить" class="btn">
								</div>
							</form>
							<div>
								<?php if( $row['status'] == 10 && !$this->isHaveRequiredPhotos( $row['id'] ) ): ?>
									<a href="/cabinet/edit-photo/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>" class="btn btn-large">Добавить фото</a>
								<?php endif ?>
								<?php if( $row['active'] ): ?>
									<a href="/cabinet/disable-ank/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>" class="btn btn-large btn-danger">Выключить</a>
								<?php else: ?>
									<a href="/cabinet/enable-ank/n/<?=$row['id'] . $this->getRightUri( $_GET); ?>" class="btn btn-large">Включить</a>
								<?php endif ?>
								<a href="/cabinet/del-ank/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>" class="btn btn-large btn-danger">Удалить</a>
							</div>
							</div>
						</div>
						<? endif; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?endforeach?>
</div>
<script type="text/javascript">
	function showComment( value,el ) {
		var $without_comments = [ 0, 30, 31 ];

		if ( $without_comments.indexOf(parseInt(value)) != -1) {
			$(el).siblings('div').css('display', 'none');
		} else {
			$(el).siblings('div').css('display', 'block');
		}
	}

	$("#submit_status").click(function(e){
		var $s = $('select[name="s"]').val();
		var $val = $('#comm_textarea').val();

		
	});

	$("#submit_status").click(function(e){
		$without_comments = [30, 31];
		s = $('select[name="s"]').val();
		val = $('#comm_textarea').val();

		if ( (!val || val.length == 0 || val == "Обязательно оставьте комментарий" ) && $without_comments.indexOf(parseInt(value)) == -1 ) {
			e.preventDefault();
			$('#comm_textarea').val('Обязательно оставьте комментарий');
		}
	});

	$("#comm_textarea").focus(function (){
		$(this).val('');
	})
</script>