<div id="center">
	<?php if ( $this->ankets->count() > 1 ) : ?>
		<div class="pages"><?=$this->paginationControl($this->ankets,'Sliding','pages_cab.phtml')?></div>
	<?php endif ?>
	<div id="cab_ankets">
		<ul class="top_info">
			<li><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=all" ?>" <?php if ( $_GET['filter'] == 'all' ) : ?> class="underlined" <?php endif ?>>ВСЕГО АНКЕТ: <?=$this->all ?></a></li>
			<li><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=active" ?>" <?php if ( $_GET['filter'] == 'active' ) : ?> class="underlined" <?php endif ?>>ИЗ НИХ АКТИВНЫХ (ПОКАЗЫВАЮТСЯ): <?=$this->active?></a></li>
			<li><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=paid" ?>" <?php if ( $_GET['filter'] == 'paid' ) : ?> class="underlined" <?php endif ?>>ПРИОРИТЕТНЫХ (ОПЛАЧИВАЕМЫХ): <?=$this->paid?></a></li>
			<li><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=free" ?>" <?php if ( $_GET['filter'] == 'free' ) : ?> class="underlined" <?php endif ?>>БЕСПЛАТНЫХ: <?=$this->active-$this->paid?></a></li>
			<li><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=not_active" ?>" <?php if ( $_GET['filter'] == 'not_active' ) : ?> class="underlined" <?php endif ?>>СНЯТЫ С ПОКАЗА (ВЫКЛЮЧЕНЫ): <?=$this->all-$this->active?></a></li>
		</ul>
		<? if ( ($this->user_moder || $this->admin) && preg_match('/\/cabinet\/ank-moderation(.*)/', $_SERVER['REQUEST_URI']) ) : ?>
			<ul class="top_info_login">
				<li>Анкеты <?php echo $this->getUserLoginById($this->user_id); ?><li>
			</ul>
		<?php endif ?>
		<?if($this->user_id):?>
		<hr />
		<ul class="top_info_bottom">
			<li>Ваш баланс: <strong><?=number_format($this->balance, 0, ',', ' ');?> р.</strong></li>
			<li>Суточный расход: <strong><?=number_format($this->spend, 0, ',', ' ');?> р.</strong></li>
			<?php if ( $this->forecast ) : ?>
				<li>Дата отключения(прогноз): <strong><?php echo $this->forecast ?></strong></li>
			<?php endif ?>
		</ul>
		<?else:?>
		<br />
		<?endif?>
		<div id="cab_ankets_wrap">
			<?foreach($this->ankets as $row):?>
			<?php 
				if(!empty($row['photolist'])){
					$photolist = unserialize($row['photolist']);
					if(isset($photolist['preview'])){
						$photo=$photolist[$photolist['preview']];
					}
					else{$photo=array_shift($photolist);}
				}
				else{$photo=false;}

				if ( !empty($row['photo_check']) ) {
					$photo_check = array_filter(unserialize($row['photolist']));
					$photo_check = array_shift($photo_check);
				} else {
					$photo_check = false;
				}
			?>
			<div class="cab_anketa">
				<div class="cab_anketa_header">
					<h2>
						<?=$row['name']?> (
						<?=$this->cities[$row['city']]?>)
						<?list($phone_p1,$phone_p2)=explode('-',$row['phone'])?>
						+7(<?=$phone_p1?>)<?=$phone_p2?>
					</h2>
					<ul>
						<li><a href="/cabinet/edit-ank-form/id/<?=$row['id']?>">Редактировать</a></li>
						<li><a href="/cabinet/edit-photo/n/<?=$row['id']?>">Фото</a></li>
						<li><a href="/cabinet/check-photo/n/<?=$row['id']?>" title="Фотография подтверждающая подлинность анкеты">Фото для проверки</a></li>
						<li><a href="/cabinet/edit-video/n/<?=$row['id']?>">Видео</a></li>
						<li><a href="/cabinet/comms-list/n/<?=$row['id']?>">Комментарии</a></li>
					</ul>
				</div>
				<br />
				<div class="cab_anketa_photo">
					<?if ( $row['active'] == 0 ) : ?><div class="cab_anketa_photo_glass"></div><?php endif ?>
					<a href="/anketa/<?php echo $row['name'] ?>-<?php echo  $row['id'] ?>" target="_blank">
						<div<?if($photo):?> style="background:url('<?=$this->photos_path.'/'.$row['user_id'].'/th_'.$photo?>') no-repeat top; width: 180px !important;" <?endif?>></div>
					</a>
					<br />
					<p><?if($photo && $row['status'] > 20):?>Фото проверены<?elseif($photo && $row['status'] < 30):?>Фото не проверены<?else:?>Нет фотографии<?endif?></p>
				</div>				
				<? if ( ($this->user_moder || $this->admin) && preg_match('/\/cabinet\/ank-moderation(.*)/', $_SERVER['REQUEST_URI']) ) : ?>
					<div class="cab_anketa_panel ca_right">
						<?if($row['active']==0):?><h2 title="Анкета выключена">АНКЕТА ВЫКЛЮЧЕНА</h2>
						<?elseif($row['status']==10):?><h2 title="Не загружены фото">Не ПОЛНЫЕ ДАННЫЕ</h2>	
						<?elseif($row['status']==11):?><h2 title="Откланена модератором">ОТКЛОНЕНА МОДЕРАТОРОМ(ПРОВЕРОЧНОЕ ФОТО)</h2>
						<?elseif($row['status']==12):?><h2 title="Откланена модератором">ОТКЛОНЕНА МОДЕРАТОРОМ(НЕ ПОЛНАЯ ИФОРМАЦИЯ)</h2>
						<?elseif($row['status']==1):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
					    <?elseif($row['status']==2):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
						<?elseif($row['status']==20):?><h2 title="Анкета на модерации">НА МОДЕРАЦИИ</h2>
						<?elseif($row['status']==30):?><h2 title="Анкета показывается на сайте">ИДЕТ ПОКАЗ</h2>	
						<?elseif($row['status']==40):?><h2 title="Анкета в приорететном показе на сайте">ИДЕТ ПРИОРИТЕТНЫЙ ПОКАЗ</h2>
						<? endif; ?>
						<form action="/cabinet/ank-status-set/n/<?=$row['id'] . $this->getRightUri( $_GET ) ?>" method="post">
							<select name="s" onchange="if (this.value) { showComment(this.value, this) }">
								<option value="0">Выберите</option>
								<option value="12">Отклонить(неполные данные)</option>
								<option value="11">Отклонить фото</option>
								<option value="30">Разрешить фото</option>
								<option value="1">Заблокировать</option>
								<option value="2">Заблокировать (черный список)</option>
							</select>
							<input type="submit" value="применить" id="submit_status">
							<div id="comment" style="display: none;">
								<label for="comm_texarea">	
								 	Комментарий (обязательно):
								</label>
								<textarea id="comm_textarea" name="comm" cols="25" rows="8" ></textarea>
							</div>	
						</form>
						<br />
						<div class="cab_ank_pan_sub">
							<ul class="cab_ank_sub_menu">
								<li><a href="/anketa/<?php echo $row['name'] ?>-<?php echo  $row['id'] ?>" target="_blank">Смотреть</a></li>
							</ul>
						</div>	
					</div>
				<? else :?>
				<div class="cab_anketa_panel ca_right">
					<?if($row['active']==0):?><h2 title="Анкета выключена">АНКЕТА ВЫКЛЮЧЕНА</h2>
					<?elseif($row['status']==10):?>
						<h2 title="Не загружены фото">НЕ ПОЛНЫЕ ДАННЫЕ</h2>
						<?php if ( !$this->isHaveRequiredPhotos( $row['id'], 3 ) ) : ?><h3>Загрузите минимум 3 фото!</h3><?php  endif ?>
						<?php if ( !$this->isHavePhotoCheck( $row['id'] ) ) : ?><h3>Загрузите проверочную фотографию!</h3><?php endif ?>
						<?php if ( $this->isHaveRequiredPhotos( $row['id'], 3 ) && $this->isHavePhotoCheck( $row['id'] ) ) : ?><h3>Загрузите новую проверочную фотографию!</h3><?php endif ?>					
					<?elseif($row['status']==11):?>
					    <h2 title="Отклонена модератором">ОТКЛОНЕНА</h2>
					    <h3>Проверочное фото не прошло проверку</h3>
					<?elseif($row['status']==12):?>
						<h2 title="Отклонена модератором">ОТКЛОНЕНА</h2>
						<h3>Не полная информация</h3>
						<h4>Результат проверки читайте в моих сообщениях. После изменений отправте на модерацию повторно.</h4>
						<ul class="cab_ank_sub_menu">
							<li><a href="/cabinet/to-moderation/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>">На модерацию</a></li>
						</ul>
					<?elseif($row['status']==20):?><h2 title="Анкета на модерации">НА МОДЕРАЦИИ</h2>
					<?elseif($row['status']==1):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
					<?elseif($row['status']==2):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
					<?elseif($row['status']==30):?>
						<h2 title="Анкета показывается на сайте">ИДЕТ ПОКАЗ</h2>
						<h4><?= $this->showPosition($this->per_page, false, $row['performer'], $row['id']) ?></h4>
					<?elseif($row['status']==40):?>
						<h2 title="Анкета в приорететном показе на сайте">ИДЕТ ПРИОРИТЕТНЫЙ ПОКАЗ</h2>
						<h4><?= $this->showPosition($this->per_page, true) ?></h4>
					<? endif; ?>
					<div class="pull_down_cab_ank_panel">
						<h3>Приоритетный показ:</h3>
						<form action="/cabinet/priority-write/n/<?=$row['id'] . $this->getRightUri( $_GET ) ?>" method="post">
							<select name="pr">
								<option value="0"<?if($row['priority']==0):?> selected<?endif?>>Выключен</option>
								<option value="1"<?if($row['priority']==1):?> selected<?endif?>>Включен</option>
							</select>
							<input type="submit" value="применить">
						</form>							
						<div class="cab_ank_pan_sub">
							<ul class="cab_ank_sub_menu">
								<?php if( $row['status'] == 10 && !$this->isHaveRequiredPhotos( $row['id'] ) ): ?>
								<li><a href="/cabinet/edit-photo/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>">Добавить фото</a></li>
								<?php endif ?>													
								<?php if( $row['active'] ): ?>
								<li><a href="/cabinet/disable-ank/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>">Выключить</a></li>
								<?php else: ?>
								<li><a href="/cabinet/enable-ank/n/<?=$row['id'] . $this->getRightUri( $_GET); ?>">Включить</a></li>
								<?php endif ?>
								<li><a href="/cabinet/del-ank/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>">Удалить</a></li>
							</ul>
						</div>
					</div>
				</div>
				<? endif; ?>
				<div class="cab_anketa_panel ca_left">
					<div class="cab_ank_pan_sub">
						<ul>
							<li>
								<strong>Добавлена:</strong>
								<?= rusdate(strtotime($row['timestamp'])); ?>
							</li>
							<? if ( $row['photo_start'] != '0000-00-00 00:00:00' ) : ?>
								<li>
									<strong>Фото проверено:</strong>
									<?=	rusdate(strtotime($row['photo_start'])); ?>
								</li>
							<? endif; ?>
							<? if ( $row['photo_finish'] != '0000-00-00 00:00:00' && $row['status'] > 20 ) : ?>
								<li class="left">
									<strong>Проверка фото истекает: </strong>
									<?= rusdate(strtotime($row['photo_finish'])) ?>
								</li>
							<? endif; ?>
						</ul>			
					</div>
					<div class="cab_ank_pan_sub">
						<h3>Просмотры:</h3>
					</div>
					<div class="cab_ank_pan_sub">
					<?php
						$counters = new CountersAnkets();
						$counter = $counters->get_ank($row['id']);
					?>
						<ul>
							<li><strong>За 24 часа:</strong><?= $counter['today'] ? $counter['today'] : 0 ?></li>
							<li><strong>За неделю:</strong><?= $counter['week'] ? $counter['week'] : 0 ?></li>
							<li><strong>За месяц:</strong><?= $counter['month'] ? $counter['month'] : 0 ?></li>
							<li><strong>Всего:</strong><?= $counter['all'] ? $counter['all'] : 0 ?></li>
						</ul>
					</div>
					<div class="cab_ank_pan_sub"></div>
				</div>
			</div>
			<?endforeach?>
		</div>
	</div>
	<?php if ( $this->ankets->count() > 1 ) : ?>
		<div class="pages"><?=$this->paginationControl($this->ankets,'Sliding','pages_cab.phtml')?></div>
	<?php endif ?>
</div>
<script type="text/javascript">
	function showComment( value, el ) {
		if ( value == 30 || value == 0) {
			$(el).siblings('div').css('display', 'none');
		} else {
			$(el).siblings('div').css('display', 'block');
		}
	}

	$("#submit_status").click(function(e){
		s = $('select[name="s"]').val();
		console.log(s);
		val = $('#comm_textarea').val();
		console.log(val);
		if ( (!val || val.length == 0 || val == "Обязательно оставьте комментарий" ) && s != 30 ) {
			e.preventDefault();
			$('#comm_textarea').val('Обязательно оставьте комментарий');
		}
	});

	$("#comm_textarea").focus(function (){
		$(this).val('');
	})
</script>