<style>
	b {
		color: red;
	}

	.controls .error {
		border-color: #B94A48;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Добавить/Редактировать пункт меню
		</h3>
	</div>
</div>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget box green">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i></h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascript:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<form class="form-horizontal" class="cab_form" method="post" action="<?= $this->url(array('action' => isset($this->action) ? ('menu-items-'.$this->action):'menu-items-add')) ?>" onSubmit="$('#field_uri').removeAttr('disabled');">

					<!-- menu_title -->
					<div class="control-group <?= $this->info['failed']['menu_title']['class'] ?>">
						<label class="control-label">Название в меню: <b>*</b></label>
						<div class="controls">
							<input type="text" class="span6 <?= $this->info['failed']['menu_title']['class'] ?>" name="menu_title" <?if(isset($this->info['menu_title'])):?> value='<?=($this->info['menu_title'])?>'<?endif?>>
							<span class="help-inline"><?= $this->info['failed']['menu_title']['message'] ?></span>
						</div>
					</div>

					<!-- priority -->
					<div class="control-group <?= $this->info['failed']['priority']['class'] ?>">
						<label class="control-label">Позиция в меню(1-NN): <b>*</b></label>
						<div class="controls">
							<input type="text" class="span6 <?= $this->info['failed']['priority']['class'] ?>" name="priority" <?if(isset($this->info['priority'])):?> value='<?=($this->info['priority'])?>'<?endif?>>
							<span class="help-inline"><?= $this->info['failed']['priority']['message'] ?></span>
						</div>
					</div>

					<!-- title -->
					<div class="control-group <?= $this->info['failed']['title']['class'] ?>">
						<label class="control-label">Название раздела: <b>*</b></label>
						<div class="controls">
							<input type="text" class="span6 <?= $this->info['failed']['title']['class'] ?>" name="title" <?if(isset($this->info['title'])):?> value='<?=($this->info['title'])?>'<?endif?>>
							<span class="help-inline"><?= $this->info['failed']['title']['message'] ?></span>
						</div>
					</div>

					<!-- uri -->
					<div class="control-group <?= $this->info['failed']['uri']['class'] ?>">
						<label class="control-label">Uri пункта меню: <b>*</b></label>
						<div class="controls">
							<input type="text" class="span6 <?= $this->info['failed']['uri']['class'] ?>" id="field_uri" name="uri" <?if(isset($this->info['uri'])):?> value='<?=($this->info['uri'])?>'<?endif?>>
							<label class="checkbox" style="display: inline; margin: 0px !important;">
								<input type="checkbox" id="field_uri_is_editable" name="field_uri_is_editable" <?=($this->action == 'add') ? 'checked' : ''?>/>
								<a class="show-message" href="javascript:;">
									Редактировать
								</a>
							</label>
							<span class="help-inline"><?= $this->info['failed']['uri']['message'] ?></span>
						</div>
					</div>

					<!--title_meta -->
					<div class="control-group <?= $this->info['failed']['title_meta']['class'] ?>">
						<label class="control-label">Мета-тег title:</label>
						<div class="controls">
							<input type="text" class="span6 <?= $this->info['failed']['title_meta']['class'] ?>" name="title_meta" <?if(isset($this->info['title_meta'])):?> value='<?=($this->info['title_meta'])?>'<?endif?>>
							<span class="help-inline"><?= $this->info['failed']['title_meta']['message'] ?></span>
						</div>
					</div>

					<!--keywords -->
					<div class="control-group <?= $this->info['failed']['keywords']['class'] ?>">
						<label class="control-label">Мета-тег Keywords:</label>
						<div class="controls">
							<input type="text" class="span6 <?= $this->info['failed']['keywords']['class'] ?>" name="keywords" <?if(isset($this->info['keywords'])):?> value='<?=($this->info['keywords'])?>'<?endif?>>
							<span class="help-inline"><?= $this->info['failed']['keywords']['message'] ?></span>
						</div>
					</div>

					<!--descriptions -->
					<div class="control-group <?= $this->info['failed']['descriptions']['class'] ?>">
						<label class="control-label">Мета-тег Keywords:</label>
						<div class="controls">
							<input type="text" class="span6 <?= $this->info['failed']['descriptions']['class'] ?>" name="descriptions" <?if(isset($this->info['descriptions'])):?> value='<?=($this->info['descriptions'])?>'<?endif?>>
							<span class="help-inline"><?= $this->info['failed']['descriptions']['message'] ?></span>
						</div>
					</div>

					<!-- text -->
					<div class="control-group <?= $this->info['failed']['text']['class'] ?>">
						<label class="control-label">Текст раздела:</label>
						<div class="controls">
							<textarea class="span6 ckeditor" name="text" rows="6"><?if(isset($this->info['text'])){ echo $this->info['text']; }?></textarea>
							<span class="help-inline"><?= $this->info['failed']['text']['message'] ?></span>
						</div>
					</div>

					<!-- text_left -->
					<div class="control-group <?= $this->info['failed']['text_left']['class'] ?>">
						<label class="control-label">Левая колонка:</label>
						<div class="controls">
							<textarea class="span6 <?= $this->info['failed']['text_left']['class'] ?>" name="text_left" rows="6"><?if(isset($this->info['text_left'])){ echo $this->info['text_left']; }?></textarea>
							<span class="help-inline"><?= $this->info['failed']['text_left']['message'] ?></span>
						</div>
					</div>

					<!-- text_right -->
					<div class="control-group <?= $this->info['failed']['text_right']['class'] ?>">
						<label class="control-label">Правая колонка:</label>
						<div class="controls">
							<textarea class="span6 <?= $this->info['failed']['text_right']['class'] ?>" name="text_right" rows="6"><?if(isset($this->info['text_right'])){ echo $this->info['text_right']; }?></textarea>
							<span class="help-inline"><?= $this->info['failed']['text_right']['message'] ?></span>
						</div>
					</div>

					<!-- text_footer -->
					<div class="control-group <?= $this->info['failed']['text_footer']['class'] ?>">
						<label class="control-label">Подвал:</label>
						<div class="controls">
							<textarea class="span6 <?= $this->info['failed']['text_footer']['class'] ?>" name="text_right" rows="6"><?if(isset($this->info['text_footer'])){ echo $this->info['text_footer']; }?></textarea>
							<span class="help-inline"><?= $this->info['failed']['text_footer']['message'] ?></span>
						</div>
					</div>

					<!-- type -->
					<div class="control-group <?= $this->info['failed']['type']['class'] ?>">
						<label class="control-label">Тип: </label>
							<div class="controls">
								<select class="span6" name="type">
									<?foreach($this->types_menu as $value=>$title):?>
										<option value="<?=$value?>"<?if(isset($this->info['type']) && $value==$this->info['type']):?> selected<?endif?>><?=$title?></option>
									<?endforeach?>
								</select>
								<span class="help-inline"><?= $this->info['failed']['type']['message'] ?></span>
							</div>
					 </div>

					<!-- performer -->
					<div class="control-group <?= $this->info['failed']['performer']['class'] ?>">
						<label class="control-label">Исполнитель: </label>
							<div class="controls">
								<select class="span6 <?= $this->info['failed']['performer']['class'] ?>" name="performer">
									<?foreach($this->performer as $value=>$title):?>
										<option value="<?=$value?>"<?if(isset($this->info['performer']) && $value==$this->info['performer']):?> selected<?endif?>><?=$title?></option>
									<?endforeach?>
								</select>
								<span class="help-inline"><?= $this->info['failed']['performer']['message'] ?></span>
							</div>
					</div>

					<div class="form-actions">
						<input type="submit" name="submit" id="submit" value="Сохранить" class="btn blue">
					</div>

					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	function field_uri_editable(obj){
		if ($(obj).attr('checked')){
			$('#field_uri').removeAttr('disabled');
		}else{
			$('#field_uri').attr('disabled','disabled');
		}
	}

	field_uri_editable('#field_uri_is_editable');
	$('#field_uri_is_editable').change(function(){
		field_uri_editable(this); 
	});

	$(function () {
		$("input[type=radio], input[type=checkbox]").uniform();
	});
</script>