<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Пункты меню
		</h3>
	</div>
</div>
<p>
	<a href="/cabinet/menu-items-add-form" class="btn btn-large"><i class="icon-plus-sign-alt"></i>&nbsp;Добавить</a>
</p>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget purple">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i></h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<div class="space15"></div>
						<table class="table table-striped table-hover table-bordered" id="editable-sample">
							<?php $count = 1; ?>
							<?foreach($this->items as $item):?>
							<tr>
								<td><?= $count++ ?> . <?=  $this->textToView($item['title'])?> (<?= $item['uri'] ?> )</td>
								<td width="7%"><a class="btn" href="/cabinet/menu-items-del/n/<?= $item['id'] ?>"><i class="icon-remove-sign"></i>&nbsp;Удалить</a></td>
								<td width="10%"><a class="btn" href="/cabinet/menu-items-edit-form/n/<?= $item['id'] ?>"><i class="icon-pencil"></i>&nbsp;Редактировать</a></td>
							</tr>
							<?endforeach?>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>