<style>
	.errors {
		list-style-type: none;
		color: #b94a48;
		margin-left: 180px;
		margin-top: 5px;
	}

	.grey {
		color: grey;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Мои сообщения
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<form id="<?= $this->form->getId() ?>" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>">
		<div class="widget red">
			<div class="widget-title">
				<h4><i class="icon-reorder"></i></h4>
				<span class="tools">
					<a class="icon-chevron-down" href="javascript:void(0)"></a>
				</span>
				<div class="actions">
					<div class="btn-group">
						<button data-toggle="dropdown" class="btn dropdown-toggle">Выделить <span class="caret"></span></button>
						<ul class="dropdown-menu pull-right">
							<li><a href="javascript:void(0)" id="all">Все</a></li>
							<li><a href="javascript:void(0)" id="viewed">Прочитанные</a></li>
							<li><a href="javascript:void(0)" id="new">Новые</a></li>
						</ul>
					</div>
				</div>
				<?php	echo $this->paginationControl($this->paginator,'Sliding','partials/pagination-control.phtml'); ?>
			</div>
			<div class="widget-body">
				<div class="accordion" id="accordion1">
					<?php
						echo $this->partialLoop('cabinet/messages-row.phtml', $this->paginator); 
					?>
				</div>
			</div>
		</div>
		<input type="submit" class="btn btn-large btn-danger" name="submit" id="submit" value="Удалить отмеченные">
		</form>
	</div>
</div>
<script type="text/javascript">
	$("#all").click(function(){
		$("input[type='checkbox']").each(function(){
			$(this).attr("checked", "checked");
			$(this).parent().addClass("checked");
		});
	});

	$("#viewed").click(function(){
		$("input[type='checkbox']").each(function(){
			$(this).removeAttr("checked", "checked");
			$(this).parent().removeClass("checked");
		});

		$(".checkbox-viewed").each(function(){
			$(this).attr("checked", "checked");
			$(this).parent().addClass("checked");
		});
	});	

	$("#new").click(function(){
		$("input[type='checkbox']").each(function(){
			$(this).removeAttr("checked", "checked");
			$(this).parent().removeClass("checked");
		});

		$(".checkbox-new").each(function(){
			$(this).attr("checked", "checked");
			$(this).parent().addClass("checked");
		});
	});	

	$(function () {
		$("input[type=radio], input[type=checkbox]").uniform();
	});
</script>