<?php 
	if ( $this->viewed  ) {
		$class = "checkbox-viewed";
		$color_class = "grey";
	} else {
		$class = "checkbox-new";
	}
?>
<div class="accordion-group">
	<div class="accordion-heading">
		<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion1" href="#collapse_<?php echo $this->id ?>">
			<?= $this->getMessageFrom( $this->id ) ?>
		</a>
		<a href="/cabinet/delete-message/id/<?= $this->id; ?>" class="btn pull-right" style="margin: 4px;">
			<i class="icon-remove-sign"></i>&nbsp;Удалить
		</a>
	</div>
	<div id="collapse_<?php echo $this->id ?>" class="accordion-body collapse in">
		<div class="accordion-inner">
			<label class="checkbox">
				<input type="checkbox" name="del_<?= $this->id?>" value="1" class="<?= $class ?>" />
				<a class="show-message <?php echo $color_class; ?>" href="/cabinet/show-message/id/<?= $this->id; ?>">
					<?= $this->subject; ?>
				</a>
			</label>
		</div>
	</div>
</div>
