<div class="center">
	<div id = "centerwrap" class="pay" >
		<h2>Платные услуги</h2>
		<div class="balance_spent">
			<h4>Текущий баланс: <?php echo $this->balance; ?></h4>
			<h4>Суточный расход: <?php echo $this->spend; ?></h4>
		</div>
		<span>Дата отключения(прогноз): <?php echo $this->forecast; ?></span>
		<br />
		<br />
		<p>На данный момент пополнение баланса возможно только прямым переводом на кошелек.</p>
		<ul>
			<li><a href="/cabinet/payment-strict">Прямой перевод на кошелек WebMoney</a></li>
			<li><a href="#" style="color: grey">Пополнить счет с кошелька Webmoney</a></li>
			<li><a href="#" style="color: grey">Пополнить счет через терминалы оплаты</a></li>
			<li><a href="#" style="color: grey">Пополнить счет через карты Webmoney</a></li>
			<li><a href="#" style="color: grey">История платежей</a></li>
		<!-- 
			<li><a href="/cabinet/payment?type=0">Пополнить счет с кошелька Webmoney</a></li>
			<li><a href="/cabinet/payment?type=1">Пополнить счет через терминалы оплаты</a></li>
			<li><a href="/cabinet/payment?type=2">Пополнить счет через карты Webmoney</a></li>
			<li><a href="/cabinet/payment-history">История платежей</a></li>
		-->
		</ul>
		<div class="description">
			<span>Списание средств за рекламу анкет производится каждый час.</span>	
			<span>При возниконовение вопросов по оплате воспользуйтесь формой</span>
			<span>связи с администрацией указав в получателе "Финансовые вопросы"!</span>
		</div>
		<ul>
			<li><a href="/cabinet/payment-info">Условия размещения анкет исполнителей: девушек, массажисток, БДСМ и т.д.</a></li>
			<li><a href="/cabinet/payment-salon-info">Условия размещения анкет салонов</a></li>
		</ul>
  	</div>
</div>