<div class="center">
	<div id = "centerwrap" class="pay" >
		<h2>Условия размещения анкет</h2>
		<div class="description">
			<span>Мы ценим наших посетителей и стараемся сделать так, чтобы они возвращались на наш сайт снова и снова, а их выбор не стал разочарованием. Поэтому на сайт принимаются <b>только анкеты с оригинальными фотографиями</b>. После загрузки основных фотографий и информации об анкете необходимо пройти проверку, загрузив проверочную фото. Сделать это можно перейдя по ссылке Фото для проверки в анкете. Увеличить кол-во просмотров вашей анкеты вы можете загрузить видео, и анкета станет доступна в разделе “Анкеты с видео”. Также рекомендуем заполнять поле экзотика, тогда анкета станет доступна в таких разделах как узбечки, мулатки, негритянки и  азиатки.</span>
			<span>Анкеты Девушек, Подружек, Массажисток, БДСМ, Мужчина, Транс, Пары размещаются бесплатно. Но при этом быстро опускаются на удаленные страницы сайта и их трудно найти вашим клиентам. Чтобы увеличить кол-во просмотров анкеты, необходимо включить приоритетный показ. При этом анкета выводиться выше остальных на первых страницах сайта, в случайном порядке, в зависимости от кол-ва платных анкет.</span>
		</div>
		<h3>Преимущества приоритетного(платного) показа</h3>
		<ul>
			<li>Платные анкеты после создания попадают в ленту "Новые анкеты" на главной странице сайта и получают ярлык "Новинка" на первые две недели - что повышает их посещаемость, когда вам срочно нужны звонки на первом этапе.</li>
			<li>Платные анкеты размещаются первыми в списке и выводятся на первых страницах сайта.</li>
			<li>Платные анкеты располагаются первыми в результатах поиска при прочих равных условиях.</li>
			<li>Во всех разделах сайта, таких как элитные, дешевые, азиатки, мулатки и т.д. платные анкеты выводятся первыми в списке.</li>
			<li>Платные анкеты показываются первыми на мобильной версии сайта.</li>
			<li>В платных анкетах отсутствуют ссылки на "Похожие анкеты".</li>
			<li>У платных анкет можно скрывать отзывы пользователей.</li>
			<li>Везде, где это только возможно, платные анкеты имеют приоритет. Мы продаем не конкретные места, а приоритет.</li>
		</ul>
		<br />
		<h3>Сортировка</h3>
		<br />
		<span>Платные анкеты перемешиваются между собой, причем установленная очередность следования анкет сохраняется за каждым посетителем сайта индивидуально.</span>
		<br />
		<br />
		<h3>Стоимость</h3>
		<br />
		<span>Стоимость приоритетного показа анкет</span>
		<br />
		<br />
		<!--  TABLE FOR GIRL -->
		<table width="480" border="0" class="root_table_girl">
			<tbody>
				<tr>
					<td colspan="6" class="root_tab_girl_head">Девушки</td>
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Кол-во анкет</td>
					<td class="root_tab_first_rtd">1-2</td>
					<td class="root_tab_first_rtd">3-4</td>
					<td class="root_tab_first_rtd">5-9</td>
					<td class="root_tab_first_rtd">10-14</td>
					<td class="root_tab_first_rtd">15 и более</td>
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Стоимость анкеты</td>
					<td style="text-align: center;"><?php echo $this->girl_price; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->girl_price - 5; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->girl_price - 10; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->girl_price - 15; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->girl_price - 20; ?> р. в сутки</td>
				</tr>
			</tbody>
		</table>
		<!--  END TABLE FOR GIRL -->
		<br />
		<!--  TABLE FOR LESB -->
		<table width="480" border="0" class="root_table_girl">
			<tbody>
				<tr>
					<td colspan="6" class="root_tab_girl_head">Подружки</td>
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Кол-во анкет</td>
					<td class="root_tab_first_rtd">1-2</td>
					<td class="root_tab_first_rtd">3-4</td>
					<td class="root_tab_first_rtd">5-9</td>
					<td class="root_tab_first_rtd">10-14</td>
					<td class="root_tab_first_rtd">15 и более</td>					
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Стоимость анкеты</td>
					<td style="text-align: center;"><?php echo $this->lesb_price; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->lesb_price - 5; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->lesb_price - 10; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->lesb_price - 15; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->lesb_price - 20; ?> р. в сутки</td>
				</tr>			
			</tbody>
		</table>
		<!--  END TABLE FOR LESB -->
		<br/>
		<!-- TABLE FOR MASS -->
		<table width="480" border="0" class="root_table_girl">
			<tbody>
				<tr>
					<td colspan="6" class="root_tab_girl_head">Массажистки</td>
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Кол-во анкет</td>
					<td class="root_tab_first_rtd">1-2</td>
					<td class="root_tab_first_rtd">3-4</td>
					<td class="root_tab_first_rtd">5-9</td>
					<td class="root_tab_first_rtd">10-14</td>
					<td class="root_tab_first_rtd">15 и более</td>					
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Стоимость анкеты</td>
					<td style="text-align: center;"><?php echo $this->mass_price; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->mass_price - 5; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->mass_price - 10; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->mass_price - 15; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->mass_price - 20; ?> р. в сутки</td>
				</tr>			
			</tbody>
		</table>
		<!-- END TABLE FORM MASS -->
		<br />
		<!--  TABLE FOR BDSM -->
		<table width="480" border="0" class="root_table_girl">
			<tbody>
				<tr>
					<td colspan="6" class="root_tab_girl_head">БДСМ</td>
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Кол-во анкет</td>
					<td class="root_tab_first_rtd">1-2</td>
					<td class="root_tab_first_rtd">3-4</td>
					<td class="root_tab_first_rtd">5-9</td>
					<td class="root_tab_first_rtd">10-14</td>
					<td class="root_tab_first_rtd">15 и более</td>					
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Стоимость анкеты</td>
					<td style="text-align: center;"><?php echo $this->bdsm_price; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->bdsm_price - 5; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->bdsm_price - 10; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->bdsm_price - 15; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->bdsm_price - 20; ?> р. в сутки</td>
				</tr>			
			</tbody>
		</table>
		<!--  END TABLE FOR BDSM -->
		<br/>
		<!--  TABLE FOR MAN -->
		<table width="480" border="0" class="root_table_girl">
			<tbody>
				<tr>
					<td colspan="6" class="root_tab_girl_head">Мужчина</td>
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Кол-во анкет</td>
					<td class="root_tab_first_rtd">1-2</td>
					<td class="root_tab_first_rtd">3-4</td>
					<td class="root_tab_first_rtd">5-9</td>
					<td class="root_tab_first_rtd">10-14</td>
					<td class="root_tab_first_rtd">15 и более</td>					
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Стоимость анкеты</td>
					<td style="text-align: center;"><?php echo $this->mam_price; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->mam_price - 5; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->mam_price - 10; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->mam_price - 15; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->mam_price - 20; ?> р. в сутки</td>
				</tr>			
			</tbody>
		</table>
		<!--  END TABLE FOR MAN -->
		<br/>
		<!--  TABLE FOR TRANS -->
		<table width="480" border="0" class="root_table_girl">
			<tbody>
				<tr>
					<td colspan="6" class="root_tab_girl_head">Транс</td>
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Кол-во анкет</td>
					<td class="root_tab_first_rtd">1-2</td>
					<td class="root_tab_first_rtd">3-4</td>
					<td class="root_tab_first_rtd">5-9</td>
					<td class="root_tab_first_rtd">10-14</td>
					<td class="root_tab_first_rtd">15 и более</td>					
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Стоимость анкеты</td>
					<td style="text-align: center;"><?php echo $this->trans_price; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->trans_price - 5; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->trans_price - 10; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->trans_price - 15; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->trans_price - 20; ?> р. в сутки</td>
				</tr>			
			</tbody>
		</table>
		<!--  END TABLE FOR TRANS -->
		<br/>
		<!--  TABLE FOR PAIR -->
		<table width="480" border="0" class="root_table_girl">
			<tbody>
				<tr>
					<td colspan="6" class="root_tab_girl_head">Пары</td>
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Кол-во анкет</td>
					<td class="root_tab_first_rtd">1-2</td>
					<td class="root_tab_first_rtd">3-4</td>
					<td class="root_tab_first_rtd">5-9</td>
					<td class="root_tab_first_rtd">10-14</td>
					<td class="root_tab_first_rtd">15 и более</td>					
				</tr>
				<tr>
					<td class="root_tab_first_rtd">Стоимость анкеты</td>
					<td style="text-align: center;"><?php echo $this->pair_price; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->pair_price - 5; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->pair_price - 10; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->pair_price - 15; ?> р. в сутки</td>
					<td style="text-align: center;"><?php echo $this->pair_price - 20; ?> р. в сутки</td>
				</tr>			
			</tbody>
		</table>
		<!--  END TABLE FOR PAIR -->
		<br/>
		
	</div>
</div>