<style>
	.widget-wrap-photo {
		display: inline-block;
	}

	.portlet-scroll-2 {
		display: inline-block;
		height: 280px;
	}

	h2 {
		margin: 0px;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Салоны <?php echo $this->getUserLoginById($this->user_id); ?>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="navbar navbar-static" id="">
			<div class="navbar-inner">
				<div style="width: auto;" class="container">
					<ul role="navigation" class="nav">
						<li <?php if ( $_GET['filter'] == 'all' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=all" ?>">ВСЕГО САЛОНОВ: <?=$this->all ?></a></li>
						<li <?php if ( $_GET['filter'] == 'active' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=active" ?>">ИЗ НИХ АКТИВНЫХ (ПОКАЗЫВАЮТСЯ): <?=$this->active?></a></li>
						<li <?php if ( $_GET['filter'] == 'paid' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=paid" ?>">ПРИОРИТЕТНЫХ (ОПЛАЧИВАЕМЫХ): <?=$this->paid?></a></li>
						<li <?php if ( $_GET['filter'] == 'free' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=free" ?>">БЕСПЛАТНЫХ: <?=$this->active-$this->paid?></a></li>
						<li <?php if ( $_GET['filter'] == 'not_active' ) : ?> class="active" <?php endif ?>><a href="<?php echo $this->getRightUri( $_GET, true, true ) . "filter=not_active" ?>">СНЯТЫ С ПОКАЗА (ВЫКЛЮЧЕНЫ): <?=$this->all-$this->active?></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="page-wraper">
	<?foreach($this->salons as $row):?>
	<?php
		if(!empty($row['photolist'])){
			$photolist = unserialize($row['photolist']);
			if(isset($photolist['preview'])){
				$photo=$photolist[$photolist['preview']];
			}
			else{$photo=array_shift($photolist);}
		}
		else{$photo=false;}

		if ( !empty($row['photo_check']) ) {
			$photo_check = array_filter(unserialize($row['photolist']));
			$photo_check = array_shift($photo_check);
		} else {
			$photo_check = false;
		}
	?>
	<div class="row-fluid">	
		<div class="span12">
			<div class="widget box red">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i>
						<?=$row['name']?> (
						<?=$this->cities[$row['city']]?>)
						<?list($phone_p1,$phone_p2)=explode('-',$row['phone'])?>
						+7(<?=$phone_p1?>)<?=$phone_p2?>
					</h4>
                    <span class="tools">
                    	<a href="javascript:;" class="icon-chevron-down"></a>
                        <a href="javascript:;" class="icon-remove"></a>
                    </span>
				</div>
				<div class="widget-body">
					<div class="row-fluid">
						<p>
							<a href="/cabinet/edit-salon-form/id/<?=$row['id']?>" class="btn">Редактировать</a>
							<a href="/cabinet/edit-photo-salon/n/<?=$row['id']?>" class="btn">Фото</a>
							<a href="/cabinet/edit-video-salon/n/<?=$row['id']?>" class="btn">Видео</a>
							<a href="/cabinet/intim-map-salon/n/<?=$row['id']?>" class="btn">Интим-карта</a>
							<a href="/cabinet/add-ank-to-salon/n/<?=$row['id']?>" class="btn">Анкеты</a>
						</p>
						<div class="span2" style="width: 200px; margin-left: 0px; position: relative;">
							<a href="/salon/<?php echo $row['name'] ?>-<?php echo  $row['id'] ?>" target="_blank">
								<div<?if($photo):?> style="background:url('<?=$this->photos_path.'/'.$row['user_id'].'/th_'.$photo?>') no-repeat top; width: 185px; height: 280px;" <?endif?>></div>
							</a>
						</div>
						<div class="span2" style="width: 200px; margin-left: 10px; position: relative;">
							<h2>Просмотры</h2>
							<div>
								<?php
									$counters = new CountersAnkets();
									$counter = $counters->get_ank($row['id']);
								?>
								<table width="100%">
									<tr>
										<td><strong>За 24 часа:</strong></td>
										<td><span class="badge badge-important offset"><?= $counter['today'] ? $counter['today'] : 0 ?></span><td>
									</tr>
									<tr>
										<td><strong>За неделю:</strong></td>
										<td><span class="badge badge-important offset"><?= $counter['week'] ? $counter['week'] : 0 ?></span><td>
									</tr>
									<tr>
										<td><strong>За месяц:</strong></td>
										<td><span class="badge badge-important offset"><?= $counter['month'] ? $counter['month'] : 0 ?></span><td>
									</tr>
									<tr>
										<td><strong>Всего:</strong></td>
										<td><span class="badge badge-important offset"><?= $counter['all'] ? $counter['all'] : 0 ?></span><td>
									</tr>
								</table>
							</div>
							<h2>Даты</h2>
							<div style="margin-top: 10px;">
								<strong>Добавлена: </strong><?= rusdate(strtotime($row['timestamp'])); ?>
							</div>
						</div>
						<? if ( ($this->user_moder || $this->admin) && preg_match('/\/cabinet\/salons-moderation(.*)/', $_SERVER['REQUEST_URI']) ) : ?>
						<div class="span7">
							<?if($row['active']==0):?><h2 title="Салон выключен">САЛОН ВЫКЛЮЧЕН</h2>
							<?elseif($row['status']==10):?>
							<h2 title="Не полные данные">НE ПОЛНЫЕ ДАННЫЕ</h2>
							<?php if ( !$this->isHaveRequiredSalonPhotos( $row['id'], 3 ) ) : ?><h3>Фото не загружено – загрузите минимум 3 фотографии</h3><?php endif ?>
							<?elseif($row['status']==1):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
							<?elseif($row['status']==2):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
							<?elseif($row['status']==11):?>
							<h2 title="">ОТКЛОНЕНА</h2>
							<h3>Не полная информация</h3>
							<?elseif($row['status']==20):?>
							<h2 title="На модерации">НА МОДЕРАЦИИ</h2>
							<?elseif($row['status']==30):?><h2 title="Проверена">ПРОВЕРЕНА</h2>
							<?elseif($row['status']==40):?><h2 title="Идет приоритетный показ">ИДЕТ ПРИОРИТЕТНЫЙ ПОКАЗ</h2>
							<?php endif ?>
							<form action="/cabinet/salon-status-set/n/<?=$row['id'] .  $this->getRightUri( $_GET ) ?>" method="post" class="form-horizontal">
								<div class="control-group">
									<select name="s" onchange="if (this.value) { showComment(this.value, this) }">
										<option value="0">Выберите</option>
										<option value=11>Отклонить(неполные данные)</option>
										<option value="30">Разрешить фото</option>
										<option value="1">Заблокировать</option>
										<option value="2">Заблокировать (черный список)</option>
									</select>
									<input type="submit" value="применить" class="btn" id="submit_status">
									<div id="comment" style="display: none;">
										<label for="comm_texarea">
											Комментарий (не обязательно):
										</label>
										<textarea id="comm_texarea" name="comm" cols="25" rows="8" class="input-xxlarge"></textarea>
									</div>
								</div>
								<div class="control-group">
									<a href="/salon/<?php echo $row['name'] ?>-<?php echo  $row['id'] ?>" target="_blank" class="btn">Смотреть</a>
								</div>
							</form>
						</div>
						<?php else : ?>
						<div class="span4">
							<?if($row['active']==0):?><h2 title="Салон выключен">САЛОН ВЫКЛЮЧЕН</h2>
							<?elseif($row['status']==10):?>
							<h2 title="Не полные данные">НE ПОЛНЫЕ ДАННЫЕ</h2>
							<?php if ( !$this->isHaveRequiredSalonPhotos( $row['id'], 3 ) ) : ?><h3>Фото не загружено – загрузите минимум 3 фотографии</h3><?php endif ?>
							<?elseif($row['status']==1):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
							<?elseif($row['status']==2):?><h2 title="Анкета заблокированна">ЗАБЛОКИРОВАННА</h2>
							<?elseif($row['status']==11):?>
							<h2 title="">ОТКЛОНЕНА</h2>
							<h3>Не полная информация</h3>
							<h4>Результат проверки читайте в моих сообщениях. После изменений отправте на модерацию повторно.</h4>
							<ul class="cab_ank_sub_menu">
								<li><a href="/cabinet/to-moderation-salon/n/<?=$row['id'] . $this->getRightUri( $_GET ); ?>">На модерацию</a></li>
							</ul>
							<?elseif($row['status']==20):?>
							<h2 title="На модерации">НА МОДЕРАЦИИ</h2>
							<h3>Анкета ожидает модерации</h3>
							<?elseif($row['status']==30):?>
							<h2 title="Проверена">ПРОВЕРЕНА</h2>
							<h3>Анкета салона проверена модератором, но не показывается на сайте. Необходимо включить <b>ПРИОРИТЕТНЫЙ</b> показ.</h3>
							<?elseif($row['status']==40):?>
							<h2 title="Идет приоритетный показ">ИДЕТ ПРИОРИТЕТНЫЙ ПОКАЗ</h2>
							<h4><?php echo $this->showPositionSalon($this->per_page) ?></h4>
							<?php endif ?>
							<div class="pull_down_cab_ank_panel">
								<form action="/cabinet/priority-write-salon/n/<?=$row['id'] . $this->getRightUri( $_GET ) ?>" method="post" class="form-horizontal">
									<label class="control-label">Приоритетный показ:</label>
									<div class="control-group">
										<select name="pr">
											<option value="0"<?if($row['priority']==0):?> selected<?endif?>>Выключен</option>
											<option value="1"<?if($row['priority']==1):?> selected<?endif?>>Включен</option>
										</select>
										<input type="submit" value="применить" class="btn">
									</div>
								</form>
								<div>
									<?if($row['active']):?>
										<a href="/cabinet/disable-salon/n/<?=$row['id']?>"  class="btn btn-large btn-danger">Выключить</a>
									<?else:?>
										<a href="/cabinet/enable-salon/n/<?=$row['id']?>" class="btn">Включить</a>
									<?endif?>
										<a href="/cabinet/del-salon/n/<?=$row['id']?>"  class="btn btn-large btn-danger">Удалить</a>
								</div>
							</div>
						</div>
						<?php endif ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?endforeach?>
</div>
<script type="text/javascript">
	function showComment( value, el ) {
		if ( value == 30 || value == 0) {
			$(el).siblings('div').css('display', 'none');
		} else {
			$(el).siblings('div').css('display', 'block');
		}
	}

	$("#submit_status").click(function(e){
		s = $('select[name="s"]').val();
		console.log(s);
		val = $('#comm_textarea').val();
		console.log(val);
		if ( (!val || val.length == 0 || val == "Обязательно оставьте комментарий" ) && s != 30 ) {
			e.preventDefault();
			$('#comm_textarea').val('Обязательно оставьте комментарий');
		}
	});

	$("#comm_textarea").focus(function (){
		$(this).val('');
	})
</script>