<div id="center">
	<div id="cab_ankets"><div id="cab_ankets_wrap">
		<ul class="menu" style="margin:5px;">
			<li><a href="/cabinet/section-add-form">Добавить</a></li>
		</ul>
		<table class="info_table">
			<?php $count = 1; ?>
			<?foreach($this->items as $item):?>
			<tr>
            	<td><?= $count++ ?> . <?=  $this->textToView($item['title'])?> (<?= $item['uri'] ?> )</td>
                <td class="table_del_act" width="5%"><a href="#">Удалить</a></td>
				<td class="table_ed_act" width="5%"><a href="/cabinet/section-edit-form/n/<?=$item['id']?>">Редактировать</a></td>
			</tr>
			<?endforeach?>
		</table>
	</div></div>
	<div class="pages"><?=$this->paginationControl($this->items,'Sliding','pages_cab.phtml')?></div>
</div>