<div id="center">
	<?if(empty($this->errors)):?>
	<div id="cab_ankets">
		<form id="cab_ankets_wrap" class="cab_form" action="/cabinet/section-del/n/<?=$this->info['id']?>">
			<div class="ca_top ca_bottom">
				<p>Вы уверены, что хотите удалить раздел? "<?=$this->info['title']?>" ?</p>
			</div>			
			<input class="button" type="submit" value="Удалить">
		</form>
	</div>
	<?else:?>
		<div class="message">
		<?foreach($this->errors as $error):?>
		<h2><?=$error?></h2>
		<?endforeach?>
		</div>
	<?endif?>
</div>