<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Настройки сайта
		</h3>
	</div>
</div>
<div id="pager-wraper">
	<form action="<?=$this->url(array(action=>'settings-write'))?>" class="form-horizontal" method="post">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget box red">
				<div class="widget-title">
					<h4>
						<i class="icon-reorder"></i>
					</h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascript:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div class="row-fluid">
						<div class="span12">
							<div class="control-group">
								<label class="control-label">Количество превью на странице</label>
								<div class="controls">
									<input type="text" class="input-large" name="girls_per_page" <?if(isset($this->data['girls_per_page'])):?>value="<?=$this->data['girls_per_page']?>"<?endif?>>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<input type="submit" class="btn btn-large" name="submit" id="submit" value="Сохранить">
	</form>
</div>