<style>
	.errors {
		list-style-type: none;
		color: #b94a48;
		margin-left: 180px;
		margin-top: 5px;
	}
</style>
<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			<?= $this->from ?>
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<? if ( $this->form ) : ?>
		<div class="widget red">
			<div class="widget-title">
				<h4>
					<i class="icon-reorder"></i>
					<strong><span><?= $this->subject ?></span>&nbsp;(<?= rusdate(strtotime($this->timestamp), "j %MONTH% Y H:i") ?>)</strong>
				</h4>
				<span class="tools">
					<a class="icon-chevron-down" href="javascript:void(0)"></a>
				</span>
			</div>
			<div class="widget-body" style="overflow: hidden;">
				<span><?=$this->body?></span>
				<br>
				<?php if ( $this->file ) : ?>
					Прикрепленный файл: <a class="black_link" href="/user_messages_photos/<?= $this->file ?>" ><?= $this->file ?></a>
				<?php endif ?>
			</div>
		</div>
		<div class="widget box green">
			<div class="widget-title">
				<h4><i class="icon-reorder"></i></h4>
				<span class="tools">
					<a href="javascript:;" class="icon-chevron-down"></a>
					<a href="javascript:;" class="icon-remove"></a>
				</span>
			</div>
			<div class="widget-body" >
				<form method="<?= $this->form->getMethod() ?>" enctype="multipart/form-data" class="form-horizontal">
					<div class="tab-content">
						<? if ( $this->message == Form_NewMessageForm::SUCCESS ) :?>
							<div class="alert alert-success">
								<button class="close" data-dismiss="alert">×</button>
								<strong>Успешно!</strong>&nbsp;<?php echo $this->message ?>
							</div>
						<? elseif ( $this->message == Form_NewMessageForm::FAILED ) : ?>
							<div class="alert alert-error">
								<button class="close" data-dismiss="alert">×</button>
								<strong>Ошибка!</strong>&nbsp;<?php echo $this->message ?>
							</div>
						<? endif ?>
							<? foreach ($this->form as $element): ?>
								<? if ( !preg_match('/submit|upload|delete/', $element->getName() ) ) :?>
									<?= $element ?>
								<? endif ?>
							<? endforeach; ?>
							<div class="control-group">
								<label class="control-label" style="width: 180px;">Прикрепить фото</label>
								<div class="controls">
									<div data-provides="fileupload" class="fileupload fileupload-new">
										<span class="btn btn-file">
											<span class="fileupload-new">Select file</span>
											<span class="fileupload-exists">Change</span>
											<input type="hidden" name="MAX_FILE_SIZE" value="2097152" id="MAX_FILE_SIZE">
											<input type="file" name="upload" class="default">
										</span>
										<span class="fileupload-preview"></span>
										<a style="float: none" data-dismiss="fileupload" class="close fileupload-exists" href="#">×</a>
									</div>
								</div>
							</div>
							<div class="form-actions">
								<button name="delete" id="delete-button" type="button" class="btn blue">Удалить</button>
								<input type="submit" name="submit" id="submit" value="Ответить" class="btn blue">
							</div>
					</div>
				</form>	
			</div>
		</div>
		<? else : ?>
		<div class="widget red">
			<div class="widget-title">
				<h4>
					<i class="icon-reorder"></i>
					<strong><span><?= $this->subject ?></span>&nbsp;(<?= rusdate(strtotime($this->timestamp), "j %MONTH% Y H:i") ?>)</strong>
				</h4>
				<span class="tools">
					<a class="icon-chevron-down" href="javascript:void(0)"></a>
				</span>
			</div>
			<div class="widget-body" style="overflow: hidden;">
				<span><?=$this->body?></span>
				<br>
				<?php if ( $this->file ) : ?>
					Прикрепленный файл: <a class="black_link" href="/user_messages_photos/<?= $this->file ?>" ><?= $this->file ?></a>
				<?php endif ?>
			</div>
		</div>
		<? endif; ?>
	</div>
</div>