<div id="center">
	<div id = "centerwrap-table" >
		<table class='form-table' cellspacing='0' id="sorter">
			<thead>
				<tr>
					<td>Тип</td>
					<th>Количество</th>
					<th>Приоритетных</th>
				</tr>
			</thead>
			<tr>
				<td>Девушкии</td>
				<td class="digits"><?= $this->count[1]; ?></td>
				<td class="digits"><?= $this->count_priority[1]; ?></td>
			</tr>
			<tr>
				<td>Подружки</td>
				<td class="digits"><?= $this->count[2]; ?></td>
				<td class="digits"><?= $this->count_priority[2]; ?></td>
			</tr>
			<tr>
				<td>Мужчины</td>
				<td class="digits"><?= $this->count[6]; ?></td>
				<td class="digits"><?= $this->count_priority[6]; ?></td>
			</tr>
			<tr>
				<td>Трансы</td>
				<td class="digits"><?= $this->count[7]; ?></td>
				<td class="digits"><?= $this->count_priority[7]; ?></td>
			</tr>
			<tr>
				<td>Пары</td>
				<td class="digits"><?= $this->count[5]; ?></td>
				<td class="digits"><?= $this->count_priority[5]; ?></td>
			</tr>
			<tr>
				<td>Массажистки</td>
				<td class="digits"><?= $this->count[3]; ?></td>
				<td class="digits"><?= $this->count_priority[3]; ?></td>
			</tr>
			<tr>
				<td>БДСМ</td>
				<td class="digits"><?= $this->count[4]; ?></td>
				<td class="digits"><?= $this->count_priority[4]; ?></td>
			</tr>
			<tr>
				<td>Салоны</td>
				<td class="digits"><?= $this->count[8]; ?></td>
				<td class="digits"><?= $this->count_priority[8]; ?></td>
			</tr>
			<tfoot>
				<tr>
					<td>Всего</td>
					<td class="digits"><?php echo array_sum($this->count) ?></td>
					<td class="digits"><?php echo array_sum($this->count_priority) ?></td>
				</tr>
			<tfoot>
		</table>
	</div>
</div>