<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Статистика анкет
		</h3>
	</div>
</div>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget purple">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i></h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<div class="space15"></div>
						<table class="table table-striped table-hover table-bordered" id="editable-sample">
							<thead>
								<tr>
									<th rowspan="2" class="header">Имя</th>
									<th rowspan="2" class="header">Цена за час</th>
									<td colspan="4" style="text-align: center;">Клики</td>
								</tr>
								<tr>
									<th class="header">За сутки</th>
									<th class="header">За неделю</th>
									<th class="header">За 30 дней</th>
									<th class="header">Всего</th>
								</tr>
							</thead>
							<tbody>
							<?php
								echo $this->partialLoop('cabinet/ankets-statistic-row.phtml', $this->paginator); 
							?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/metro/assets/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/metro/assets/data-tables/DT_bootstrap.js"></script>
<script src="/metro/js/editable-table.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	// init sMenu text for top of table
	var sMenu = 'анкет на странице';
	EditableTable.init(sMenu);
});
</script>