<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Активность рекламодателей
		</h3>
	</div>
</div>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget purple">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i></h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<div class="space15"></div>
						<table class="table table-striped table-hover table-bordered" id="editable-sample">
							<thead>
								<tr>
									<td>Тип</td>
									<th>Количество</th>
									<th>Приоритетных</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>Девушкии</td>
									<td class="digits"><?= $this->count[1]; ?></td>
									<td class="digits"><?= $this->count_priority[1]; ?></td>
								</tr>
								<tr>
									<td>Подружки</td>
									<td class="digits"><?= $this->count[2]; ?></td>
									<td class="digits"><?= $this->count_priority[2]; ?></td>
								</tr>
								<tr>
									<td>Мужчины</td>
									<td class="digits"><?= $this->count[6]; ?></td>
									<td class="digits"><?= $this->count_priority[6]; ?></td>
								</tr>
								<tr>
									<td>Трансы</td>
									<td class="digits"><?= $this->count[7]; ?></td>
									<td class="digits"><?= $this->count_priority[7]; ?></td>
								</tr>
								<tr>
									<td>Пары</td>
									<td class="digits"><?= $this->count[5]; ?></td>
									<td class="digits"><?= $this->count_priority[5]; ?></td>
								</tr>
								<tr>
									<td>Массажистки</td>
									<td class="digits"><?= $this->count[3]; ?></td>
									<td class="digits"><?= $this->count_priority[3]; ?></td>
								</tr>
								<tr>
									<td>БДСМ</td>
									<td class="digits"><?= $this->count[4]; ?></td>
									<td class="digits"><?= $this->count_priority[4]; ?></td>
								</tr>
								<tr>
									<td>Салоны</td>
									<td class="digits"><?= $this->count[8]; ?></td>
									<td class="digits"><?= $this->count_priority[8]; ?></td>
								</tr>
							</tbody>
							<tfoot>
								<tr>
									<td>Всего</td>
									<td class="digits"><?php echo array_sum($this->count) ?></td>
									<td class="digits"><?php echo array_sum($this->count_priority) ?></td>
								</tr>
							<tfoot>	
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/metro/assets/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/metro/assets/data-tables/DT_bootstrap.js"></script>
<script src="/metro/js/editable-table.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	// init sMenu text for top of table
	var sMenu = 'типов анкет на странице';
	EditableTable.init(sMenu);
});
</script>