<tr>
	<td>
		<?= $this->user_login; ?>
	</td>	
	<td class="digits">
		<?= $this->balance; ?>
	</td>
	<td class="digits">
		<?= $this->spent; ?>
	</td>	
	<td class="digits">
		<?= $this->ankets; ?>
	</td>
	<td class="center_content">
		<?= $this->timestamp; ?>
	</td>	
	<td class="center_content">
		<?= $this->showUserStatus($this->status); ?>
	</td>	
	<td class="padding_content">
		<?php echo $this->mail; ?>
	</td>
	<td class="center_content">
		<a class="btn btn-info" href="/cabinet/change-user-pass/id/<?= $this->id; ?>">
			<i class="icon-key"></i>
		</a>
		<? if ( $this->status || is_null($this->status) ) :?>
			<a class="btn btn-danger blocking" href="/cabinet/block-user/id/<?= $this->id; ?>?filter=<?= $_GET['filter'] ?>">
				<i class="icon-ban-circle"></i>
			</a>
		<? else : ?>
			<a class="btn btn-success activating" href="/cabinet/activate-user/id/<?= $this->id; ?>?filter=<?= $_GET['filter'] ?>">
				<i class="icon-ok"></i>
			</a>
		<? endif; ?>
		<a class="btn btn-inverse" href="/cabinet/change-user-type/id/<?= $this->id; ?>">
			<i class="icon-user"></i>
		</a>
		<a class="btn btn-primary" href="/cabinet/connect<?php echo "?uid=" . $this->id . "&login=" . $this->user_login ?>">
			<i class="icon-envelope"></i>
		</a>
	</td>
</tr>