<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Пользователи
		</h3>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="navbar navbar-static" id="">
        	<div class="navbar-inner">
            	<div style="width: auto;" class="container">
                    <ul role="navigation" class="nav">
                    	<li class="<?= $_GET['filter'] == 2 ? "active" : null ?>">
							<a href="/cabinet/users?filter=2">Рекламодатели</a>
                    	</li>
                        <li class="<?= $_GET['filter'] == 0 ? "active" : null ?>">
							<a href="/cabinet/users?filter=0">Посетители</a>
                        </li>
                        <li class="<?= $_GET['filter'] == 1 ? "active" : null ?>">
							<a href="/cabinet/users?filter=1">Админы</a>
                        </li>
                        <li class="<?= $_GET['filter'] == 4 ? "active" : null ?>">
							<a href="/cabinet/users?filter=4">Тех. админы</a>
                        </li>
                        <li class="<?= $_GET['filter'] == 8 ? "active" : null ?>">
							<a href="/cabinet/users?filter=8">Модераторы</a>
                         </li>
                    </ul>
                </div>
            </div>
    	</div>
	</div>
</div>
<div id="page-wraper">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget purple">
				<div class="widget-title">
					<h4><i class="icon-reorder"></i></h4>
					<span class="tools">
						<a href="javascript:;" class="icon-chevron-down"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<div class="space15"></div>
						<table class="table table-striped table-hover table-bordered" id="editable-sample">
							<thead>
								<tr>
									<th>Логин</th>
									<th>Баланс</th>
									<th>Потрачено</th>
									<th>Анкет</th>
									<th>Дата регистрации</th>
									<th>Статутс</th>
									<th>Email</th>
									<td>Редактирование</td>
								</tr>
							</thead>
							<tbody>
								<?php
									echo $this->partialLoop('cabinet/users-statistic-row.phtml', $this->paginator);
								?>
							</tbody>
							<tfoot>
								<tr>
									<td>
										Всего:
									</td>
									<td class="digits">
										<?= round($this->showSumBalance( $_GET['filter'] ), 2); ?>
									</td>
									<td class="digits">
										<?= round($this->showSumSpent( $_GET['filter'] ), 2); ?>
									</td>
									<td class="digits">
										<?= $this->showSumAnkets( $_GET['filter'] ); ?>
									<td>
								</tr>
							</tfoot>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript" src="/metro/assets/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="/metro/assets/data-tables/DT_bootstrap.js"></script>
<script src="/metro/js/editable-table.js" type="text/javascript"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	// init sMenu text for top of table
	var sMenu = 'пользователей на странице';
	EditableTable.init(sMenu);
});
</script>
<script type="text/javascript">
	$(".blocking").easyconfirm({locale: {
		title: 'Заблокировать',
		text: 'Хотите продолжить?',
		button: ['Нет', 'Да']
	}});

	$(".activating").easyconfirm({locale: {
		title: 'Активировать',
		text: 'Хотите продолжить?',
		button: ['Нет', 'Да']
	}});
</script>