<div class="row-fluid">
	<div class="span12">
		<h3 class="page-title">
			Настройки WebMoney
		</h3>
	</div>
</div>
<div id="pager-wraper">
	<form action="<?=$this->url(array(action=>'webmoney-settings-write'))?>" class="form-horizontal" method="post">
	<div class="row-fluid">
		<div class="span12">
			<div class="widget box green">
				<div class="widget-title">
					<h4>
						<i class="icon-reorder"></i>
					</h4>
					<span class="tools">
						<a class="icon-chevron-down" href="javascript:void(0)"></a>
						<a href="javascript:;" class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
					<div class="row-fluid">
						<div class="span12">
							<div class="control-group">
								<label class="control-label">WMR-кошелек</label>
								<div class="controls">
									<input type="text" class="input-large" name="WMR" <?if(isset($this->data['WMR'])):?>value="<?=$this->data['WMR']?>"<?endif?>>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="control-group">
								<label class="control-label">WMZ-кошелек</label>
								<div class="controls">
									<input type="text" class="input-large" name="WMZ" <?if(isset($this->data['WMZ'])):?>value="<?=$this->data['WMZ']?>"<?endif?>>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="control-group">
								<label class="control-label">WME-кошелек</label>
								<div class="controls">
									<input type="text" class="input-large" name="WME" <?if(isset($this->data['WME'])):?>value="<?=$this->data['WME']?>"<?endif?>>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="control-group">
								<label class="control-label">WMU-кошелек</label>
								<div class="controls">
									<input type="text" class="input-large" name="WMU" <?if(isset($this->data['WMU'])):?>value="<?=$this->data['WMU']?>"<?endif?>>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="control-group">
								<label class="control-label">Навзвание платежа</label>
								<div class="controls">
									<input type="text" class="input-large" name="DESC" <?if(isset($this->data['DESC'])):?>value="<?=$this->data['DESC']?>" <?endif?>>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="span12">
							<div class="control-group">
								<label class="control-label">Секретный ключ</label>
								<div class="controls">
									<input type="text" class="input-large" name="SECRET_KEY" <?if(isset($this->data['SECRET_KEY'])):?>value="<?=$this->data['SECRET_KEY']?>" <?endif?>>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<input type="submit" class="btn btn-large" name="submit" id="submit" value="Сохранить">
	</form>
</div>