<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title>PutanaStars :: Личный кабинет</title>
	<link rel="icon" href="/img/favicon.gif" type="image/gif" />
    <link rel="stylesheet" href="/css/form.css" />
	<?=$this->headLink()->appendStylesheet('/css/main.css')?>
	<?=$this->headScript()->appendFile('/js/scripts.js')?>
	<script src="/js/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="/js/jquery.tablesorter.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function() {
    		$("#sorter").tablesorter();
		});
	</script>
	<!-- TinyMCE -->
<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		// General options
		mode : "exact",
		elements : "editor,mail",
		theme : "advanced",
		language : "ru",
		plugins : "safari,style,table,advhr,advimage,advlink,iespell,inlinepopups,preview,searchreplace,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager",
		// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontselect,fontsizeselect",
		//theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,insertimage,cleanup,code,|,preview,|,forecolor,backcolor",
		theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,|,fullscreen",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		//theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,

		convert_urls : false,
		file_browser_callback : "mcImageManager.filebrowserCallBack",

		//For images plugin
		relative_urls : false,
		remove_script_host : true,

		// Example content CSS (should be your site CSS)
		content_css : "css/content.css",

		// Drop lists for link/image/media/template dialogs
		template_external_list_url : "lists/template_list.js",
		external_link_list_url : "lists/link_list.js",
		external_image_list_url : "lists/image_list.js",
		media_external_list_url : "lists/media_list.js",

		// Replace values for the template plugin
		template_replace_values : {
			username : "Some User",
			staffid : "991234"
		}
	});
</script>
<script src="/js/jquery-ui.min.js"></script>
<script src="/js/jquery.easy-confirm-dialog.js"></script>
<link rel="stylesheet" href="/css/jquery-ui.css" type="text/css" />
<!-- /TinyMCE -->
</head>
<body>
	<div id="wrap">
		<?=$this->render('header_cab.phtml')?>
		<div class="wrap_center">
			<?=$this->render('left_cabinet.phtml')?>
			<?=$this->layout()->content?>
			<?=$this->render('right_auth.phtml')?>
		</div>
	</div>
</body>
</html>
