<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Dynamic Table</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="/metro/assets/bootstrap/css/bootstrap.css" rel="stylesheet" />
   <link href="/metro/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="/metro/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="/metro/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="/metro/css/style.css" rel="stylesheet" />
   <link href="/metro/css/style-responsive.css" rel="stylesheet" />
   <link href="/metro/css/style-default.css" rel="stylesheet" id="style_color" />

   <link href="/metro/assets/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
   <link rel="stylesheet" type="text/css" href="/metro/assets/uniform/css/uniform.default.css" />
   <link rel="stylesheet" href="/metro/assets/data-tables/DT_bootstrap.css" />

   <script src="/metro/js/jquery-1.8.3.min.js" type="text/javascript"></script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
   <!-- BEGIN HEADER -->
   <div id="header" class="navbar navbar-inverse navbar-fixed-top">
       <!-- BEGIN TOP NAVIGATION BAR -->
       <div class="navbar-inner">
           <div class="container-fluid">
               <!--BEGIN SIDEBAR TOGGLE-->
               <div class="sidebar-toggle-box hidden-phone">
                   <div class="icon-reorder tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
               </div>
               <!--END SIDEBAR TOGGLE-->
               <!-- BEGIN LOGO -->
               <a class="brand" href="index.html">
                   <img src="/img/logo.png" alt="Metro Lab" />
               </a>
               <!-- END LOGO -->
               <!-- BEGIN RESPONSIVE MENU TOGGLER -->
               <a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="arrow"></span>
               </a>
               <!-- END RESPONSIVE MENU TOGGLER -->
               <div id="top_menu" class="nav notify-row">
                   <!-- BEGIN NOTIFICATION -->
                   <ul class="nav top-menu">
                       <!-- BEGIN INBOX DROPDOWN -->
                       <li class="dropdown" id="header_inbox_bar">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                               <i class="icon-envelope-alt"></i>
                               <span class="badge badge-important">5</span>
                           </a>
                           <ul class="dropdown-menu extended inbox">
                               <li>
                                   <p>You have 5 new messages</p>
                               </li>
                               <li>
                                   <a href="#">
                                       <span class="photo"><img src="" alt="avatar" /></span>
									<span class="subject">
									<span class="from">Jonathan Smith</span>
									<span class="time">Just now</span>
									</span>
									<span class="message">
									    Hello, this is an example msg.
									</span>
                                   </a>
                               </li>
                               <li>
                                   <a href="#">
                                       <span class="photo"><img src="" alt="avatar" /></span>
									<span class="subject">
									<span class="from">Jhon Doe</span>
									<span class="time">10 mins</span>
									</span>
									<span class="message">
									 Hi, Jhon Doe Bhai how are you ?
									</span>
                                   </a>
                               </li>
                               <li>
                                   <a href="#">
                                       <span class="photo"><img src="" alt="avatar" /></span>
									<span class="subject">
									<span class="from">Jason Stathum</span>
									<span class="time">3 hrs</span>
									</span>
									<span class="message">
									    This is awesome dashboard.
									</span>
                                   </a>
                               </li>
                               <li>
                                   <a href="#">
                                       <span class="photo"><img src="" alt="avatar" /></span>
									<span class="subject">
									<span class="from">Jondi Rose</span>
									<span class="time">Just now</span>
									</span>
									<span class="message">
									    Hello, this is metrolab
									</span>
                                   </a>
                               </li>
                               <li>
                                   <a href="#">See all messages</a>
                               </li>
                           </ul>
                       </li>
                       <!-- END INBOX DROPDOWN -->
                   </ul>
               </div>
               <!-- END  NOTIFICATION -->
               <div class="top-nav ">
                   <ul class="nav pull-right top-menu" >
                       <!-- BEGIN USER LOGIN DROPDOWN -->
                       <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                               <span class="username"><?php echo $this->layout()->user_login; ?></span>
                               <b class="caret"></b>
                           </a>
                           <ul class="dropdown-menu extended logout">
                               <li><a href="#"><i class="icon-exchange"></i>Смена пароля</a></li>
                               <li><a href="#"><i class="icon-cog"></i>Уведомления</a></li>
                               <li><a href="login.html"><i class="icon-key"></i>Log Out</a></li>
                           </ul>
                       </li>
                       <!-- END USER LOGIN DROPDOWN -->
                   </ul>
                   <!-- END TOP NAVIGATION MENU -->
               </div>
           </div>
       </div>
       <!-- END TOP NAVIGATION BAR -->
   </div>
   <!-- END HEADER -->
   <!-- BEGIN CONTAINER -->
   <div id="container" class="row-fluid">
      <!-- BEGIN SIDEBAR -->
      <div class="sidebar-scroll">
          <div id="sidebar" class="nav-collapse collapse">
              <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
              <div class="navbar-inverse">
                  <form class="navbar-search visible-phone">
                      <input type="text" class="search-query" placeholder="Search" />
                  </form>
              </div>
              <!-- END RESPONSIVE QUICK SEARCH FORM -->
              <!-- BEGIN SIDEBAR MENU -->
              <ul class="sidebar-menu">
                  <li class="sub-menu">
                      <a class="" href="/cabinet">
                          <i class="icon-dashboard"></i>
                          <span>Личный кабинет</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-wrench"></i>
                  	      <span>Настройки сайта</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Категории</a></li>
                  	 	<li><a class="" href="">Пункты меню</a></li>
                  	 	<li><a class="" href="">Настройки</a></li>
                  	 	<li><a class="" href="">Мета тэги</a></li>
                  	 	<li><a class="" href="">Статьи</a></li>
                  	 	<li><a class="" href="">Баннеры</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-usd"></i>
                  	      <span>Биллинг</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Настройки финансов</a></li>
                  	 	<li><a class="" href="">Настройка WebMoney</a></li>
                  	 	<li><a class="" href="">Финансовая отчетность</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-eye-open"></i>
                  	      <span>Модерация</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Анекеты</a></li>
                  	 	<li><a class="" href="">Салоны</a></li>
                  	 	<li><a class="" href="">Комментарии</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet">
                          <i class="icon-reorder"></i>
                          <span>Все анкеты</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/users?filter=2">
                          <i class="icon-group"></i>
                          <span>Пользователи</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet">
                          <i class="icon-bar-chart"></i>
                          <span>Рекламодатели</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/statistic">
                          <i class="icon-signal"></i>
                          <span>Статистика анкет</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet">
                          <i class="icon-gear"></i>
                          <span>Настройки профиля</span>
                      </a>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="javascript:;">
                  	      <i class="icon-envelope"></i>
                  	      <span>Сообщения</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Связь с администрацией</a></li>
                  	 	<li><a class="" href="">Мои сообщения</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-chevron-right"></i>
                  	      <span>Девушки</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Мои анкеты</a></li>
                  	 	<li><a class="" href="">Добавить анкету</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-chevron-right"></i>
                  	      <span>Подружки</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Мои анкеты</a></li>
                  	 	<li><a class="" href="">Добавить анкету</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-chevron-right"></i>
                  	      <span>Массажистки</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Мои анкеты</a></li>
                  	 	<li><a class="" href="">Добавить анкету</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-chevron-right"></i>
                  	      <span>БДСМ</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Мои анкеты</a></li>
                  	 	<li><a class="" href="">Добавить анкету</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-chevron-right"></i>
                  	      <span>Мужчина</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Мои анкеты</a></li>
                  	 	<li><a class="" href="">Добавить анкету</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-chevron-right"></i>
                  	      <span>Транс</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Мои анкеты</a></li>
                  	 	<li><a class="" href="">Добавить анкету</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-chevron-right"></i>
                  	      <span>Пары</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Мои анкеты</a></li>
                  	 	<li><a class="" href="">Добавить анкету</a></li>
                  	 </ul>
                  </li>
                  <li class="sub-menu">
                      <a class="" href="/cabinet/admin">
                  	      <i class="icon-chevron-right"></i>
                  	      <span>Салоны</span>
                  		  <span class="arrow"></span>
                  	 </a>
                  	 <ul class="sub">
                  	 	<li><a class="" href="">Мои салоны</a></li>
                  	 	<li><a class="" href="">Добавить салон</a></li>
                  	 </ul>
                  </li>
              </ul>
              <!-- END SIDEBAR MENU -->
          </div>
      </div>
      <!-- END SIDEBAR -->
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->
            <div class="row-fluid">
               <div class="span12">
                   <!-- BEGIN THEME CUSTOMIZER-->
                   <div id="theme-change" class="hidden-phone">
                       <i class="icon-cogs"></i>
                        <span class="settings">
                            <span class="text">Theme Color:</span>
                            <span class="colors">
                                <span class="color-default" data-style="default"></span>
                                <span class="color-green" data-style="green"></span>
                                <span class="color-gray" data-style="gray"></span>
                                <span class="color-purple" data-style="purple"></span>
                                <span class="color-red" data-style="red"></span>
                            </span>
                        </span>
                   </div>
                   <!-- END THEME CUSTOMIZER-->
               </div>
               <?=$this->layout()->content?>
            </div>
            <!-- END PAGE HEADER-->
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->
   </div>
   <!-- END CONTAINER -->
   <!-- BEGIN FOOTER -->
   <div id="footer">
       2013 &copy; Metro Lab Dashboard.
   </div>
   <!-- END FOOTER -->

   <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <script src="/metro/js/jquery.nicescroll.js" type="text/javascript"></script>
   <script src="/metro/assets/jquery-slimscroll/jquery-ui-1.9.2.custom.min.js" type="tex/javascrip"></script>
   <script src="/metro/assets/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
   <script src="/metro/assets/bootstrap/js/bootstrap.min.js"></script>
   <script src="/metro/js/jquery.scrollTo.min.js"></script>

   <!-- ie8 fixes -->
   <!--[if lt IE 9]>
   <script src="js/excanvas.js"></script>
   <script src="js/respond.js"></script>
   <![endif]-->
   
   <!--common script for all pages-->
   <script src="/metro/js/common-scripts.js"></script>
   <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>