<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Vbordele.com :: Личный кабинет</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="/metro/assets/bootstrap/css/bootstrap.css" rel="stylesheet" />
   <link href="/metro/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="/metro/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="/metro/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="/metro/css/style.css" rel="stylesheet" />
   <link href="/metro/css/style-responsive.css" rel="stylesheet" />
   <link href="/metro/css/style-red.css" rel="stylesheet" id="style_color" />

   <link href="/metro/assets/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
   <link rel="stylesheet" type="text/css" href="/metro/assets/uniform/css/uniform.default.css" />
   <link rel="stylesheet" href="/metro/assets/data-tables/DT_bootstrap.css" />

   <script src="/metro/js/jquery-1.8.3.min.js" type="text/javascript"></script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
   <!-- BEGIN HEADER -->
   <div id="header" class="navbar navbar-inverse navbar-fixed-top">
       <!-- BEGIN TOP NAVIGATION BAR -->
       <div class="navbar-inner">
           <div class="container-fluid">
               <!--BEGIN SIDEBAR TOGGLE-->
               <div class="sidebar-toggle-box hidden-phone">
                   <div class="icon-reorder tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
               </div>
               <!--END SIDEBAR TOGGLE-->
               <!-- BEGIN LOGO -->
               <a class="brand" href="/cabinet">
                   <img src="/img/logo.png" alt="Metro Lab" />
               </a>
               <!-- END LOGO -->
               <!-- BEGIN RESPONSIVE MENU TOGGLER -->
               <a class="btn btn-navbar collapsed" id="main_menu_trigger" data-toggle="collapse" data-target=".nav-collapse">
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="arrow"></span>
               </a>
               <!-- END RESPONSIVE MENU TOGGLER -->
               <div id="top_menu" class="nav notify-row">
                   <!-- BEGIN NOTIFICATION -->
                   <ul class="nav top-menu">
                       <!-- BEGIN INBOX DROPDOWN -->
                       <li class="dropdown" id="header_inbox_bar">
                           <a href="/cabinet/messages" class="dropdown-toggle">
                               <i class="icon-envelope-alt"></i>
                               <span class="badge badge-important"><? if ( $count = $this->countNewMessages() ) { echo $count; } ?></span>
                           </a>
                       </li>
                       <!-- END INBOX DROPDOWN -->
                   </ul>
               </div>
               <!-- END  NOTIFICATION -->
               <div class="top-nav ">
                   <ul class="nav pull-right top-menu" >
                       <!-- BEGIN USER LOGIN DROPDOWN -->
                       <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                               <span class="username"><?php echo $this->layout()->user_login; ?></span>
                               <b class="caret"></b>
                           </a>
                           <ul class="dropdown-menu extended logout">
                               <li><a href="/cabinet/profile?type=pass"><i class="icon-exchange"></i>Смена пароля</a></li>
                               <li><a href="/cabinet/profile?type=mess"><i class="icon-cog"></i>Уведомления</a></li>
                               <li><a href="/auth/logout"><i class="icon-key"></i>Выход</a></li>
                           </ul>
                       </li>
                       <!-- END USER LOGIN DROPDOWN -->
                   </ul>
                   <!-- END TOP NAVIGATION MENU -->
               </div>
           </div>
       </div>
       <!-- END TOP NAVIGATION BAR -->
   </div>
   <!-- END HEADER -->
   <!-- BEGIN CONTAINER -->
   <div id="container" class="row-fluid">
      <!-- BEGIN SIDEBAR -->
      <div class="sidebar-scroll">
          <div id="sidebar" class="nav-collapse collapse">
              <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
              <div class="navbar-inverse">
                  <form class="navbar-search visible-phone">
                      <input type="text" class="search-query" placeholder="Search" />
                  </form>
              </div>
              <!-- END RESPONSIVE QUICK SEARCH FORM -->
              <!-- BEGIN SIDEBAR MENU -->
              <ul class="sidebar-menu">
				<?
					if($this->admin):
				?>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-wrench"></i>
							<span>Настройки сайта</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet/sections">Категории</a></li>
							<li><a class="" href="/cabinet/uslugi">Услуги</a></li>
							<li><a href="/cabinet/metro-spb">Метро СПБ</a></li>
							<li><a href="/cabinet/metro-msk">Метро МСК</a></li>
							<li><a href="/cabinet/district-spb">Районы СПБ</a></li>
							<li><a href="/cabinet/district-msk">Районы МСК</a></li>
							<li><a class="" href="/cabinet/menu-items">Пункты меню</a></li>
							<li><a class="" href="/cabinet/settings">Настройки</a></li>
							<li><a class="" href="/cabinet/meta">Мета тэги</a></li>
							<li><a class="" href="/cabinet/articles">Статьи</a></li>
							<li><a class="" href="">Баннеры</a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-usd"></i>
							<span>Биллинг</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet/finance-settings">Настройки финансов</a></li>
							<li><a class="" href="/cabinet/webmoney-settings">Настройка WebMoney</a></li>
							<li><a class="" href="/cabinet/finance-statistic">Финансовая отчетность</a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-eye-open"></i>
							<span>Модерация</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet/ankets">Анекеты</a></li>
							<li><a class="" href="/cabinet/salons-per-users">Салоны</a></li>
							<li><a class="" href="/cabinet/comments">Комментарии</a></li>
						</ul>
					</li>
					<?if($this->all_anks):?>
						<li class="sub-menu">
							<a class="" href="/cabinet/my-anks">
								<i class="icon-reorder"></i>
								<span>В обычном режиме</span>
							</a>
						</li>
					<?else:?>
						<li class="sub-menu">
							<a class="" href="/cabinet/all-anks">
								<i class="icon-reorder"></i>
								<span>Все анкеты</span>
							</a>
						</li>
					<?endif?>
					<li class="sub-menu">
						<a class="" href="/cabinet/users?filter=2">
							<i class="icon-group"></i>
							<span>Пользователи</span>
						</a>
					</li>
					<li class="sub-menu">
						<a class="" href="/cabinet/statistic-commerce">
							<i class="icon-bar-chart"></i>
							<span>Рекламодатели</span>
						</a>
					</li>
					<li class="sub-menu">
						<a class="" href="/cabinet/statistic">
							<i class="icon-signal"></i>
							<span>Статистика анкет</span>
						</a>
					</li>
					<li class="sub-menu">
						<a class="" href="/cabinet/profile?type=pass">
							<i class="icon-gear"></i>
							<span>Настройки профиля</span>
						</a>
					</li>
				<?
					elseif($this->com_admin):
				?>
					<li class="sub-menu">
						<a class="" href="/cabinet/pay">
							<i class="icon-signal"></i>
							<span>Пополнить счет</span>
						</a>
					</li>
					<li class="sub-menu">
						<a class="" href="/cabinet/statistic">
							<i class="icon-signal"></i>
							<span>Статистика анкет</span>
						</a>
					</li>
					<li class="sub-menu">
						<a class="" href="/cabinet/profile?type=pass">
							<i class="icon-gear"></i>
							<span>Настройки профиля</span>
						</a>
					</li>
				<? 
					elseif($this->tech_admin):
				?>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-wrench"></i>
							<span>Настройки сайта</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet/sections">Категории</a></li>
							<li><a class="" href="/cabinet/uslugi">Услуги</a></li>
							<li><a href="/cabinet/metro-spb">Метро СПБ</a></li>
							<li><a href="/cabinet/metro-msk">Метро МСК</a></li>
							<li><a href="/cabinet/district-spb">Районы СПБ</a></li>
							<li><a href="/cabinet/district-msk">Районы МСК</a></li>
							<li><a class="" href="/cabinet/menu-items">Пункты меню</a></li>
							<li><a class="" href="">Настройки</a></li>
							<li><a class="" href="">Мета тэги</a></li>
							<li><a class="" href="/cabinet/articles">Статьи</a></li>
							<li><a class="" href="">Баннеры</a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="/cabinet/statistic-metro">
							<i class="icon-signal"></i>
							<span>Статистика по метро</span>
						</a>
					</li>
					<li class="sub-menu">
						<a class="" href="/cabinet/statistic-filter">
							<i class="icon-signal"></i>
							<span>Статистика по фильтрам</span>
						</a>
					</li>
				<?
					elseif ( $this->user_moder ):
				?>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-eye-open"></i>
							<span>Модерация</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="">АнекетыАнкеты <?= $this->toModerNum() ?></a></li>
							<li><a class="" href="">Комментарии <?= $this->toModerNumComment() ?></a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="/cabinet/profile?type=pass">
							<i class="icon-gear"></i>
							<span>Настройки профиля</span>
						</a>
					</li>
				<?php
					endif;
				?>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-envelope"></i>
							<span>Сообщения</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet/connect">Связь с администрацией</a></li>
							<li><a class="" href="/cabinet/messages">Мои сообщения
							<? if ( $count = $this->countNewMessages() ) {
								echo "(+" . $count . ")"; 
							}
							?>
							</a></li>
						</ul>
					</li>
				<? if ( !$this->tech_admin && !$this->user_moder ) : ?>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-chevron-right"></i>
							<span>Девушки</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet?performer=1">Мои анкеты</a></li>
							<li><a class="" href="/cabinet/add-ank-form/performer/1">Добавить анкету</a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-chevron-right"></i>
							<span>Подружки</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet?performer=2">Мои анкеты</a></li>
							<li><a class="" href="/cabinet/add-ank-form/performer/2">Добавить анкету</a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-chevron-right"></i>
							<span>Массажистки</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet?performer=3">Мои анкеты</a></li>
							<li><a class="" href="/cabinet/add-ank-form/performer/3">Добавить анкету</a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-chevron-right"></i>
							<span>БДСМ</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet?performer=4">Мои анкеты</a></li>
							<li><a class="" href="/cabinet/add-ank-form/performer/4">Добавить анкету</a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-chevron-right"></i>
							<span>Мужчина</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet?performer=6">Мои анкеты</a></li>
							<li><a class="" href="/cabinet/add-ank-form/performer/6">Добавить анкету</a></li>
						 </ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-chevron-right"></i>
							<span>Транс</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet?performer=7">Мои анкеты</a></li>
							<li><a class="" href="/cabinet/add-ank-form/performer/7">Добавить анкету</a></li>
						 </ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-chevron-right"></i>
							<span>Пары</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet?performer=5">Мои анкеты</a></li>
							<li><a class="" href="/cabinet/add-ank-form/performer/5">Добавить анкету</a></li>
						</ul>
					</li>
					<li class="sub-menu">
						<a class="" href="javascript:;">
							<i class="icon-chevron-right"></i>
							<span>Салоны</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub">
							<li><a class="" href="/cabinet/salons">Мои салоны</a></li>
							<li><a class="" href="/cabinet/add-salon-form">Добавить салон</a></li>
						</ul>
					</li>
				<? endif; ?>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	   </div>
      <!-- END SIDEBAR -->
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <div class="container-fluid">
         	<?=$this->layout()->content?>
         </div>
      </div>
      <!-- END PAGE -->
   </div>
   <!-- END CONTAINER -->
   <!-- BEGIN FOOTER -->
   <div id="footer">
       2013 &copy; Metro Lab Dashboard.
   </div>
   <!-- END FOOTER -->
   <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <script src="/metro/js/jquery.nicescroll.js" type="text/javascript"></script>
   <script src="/metro/assets/bootstrap/js/bootstrap.min.js"></script>
   <script src="/metro/js/jquery.scrollTo.min.js"></script>
   <script src="/metro/js/jquery.blockui.js"></script> 

   <script src="/metro/assets/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
   <script type="text/javascript" src="/metro/assets/bootstrap/js/bootstrap-fileupload.js"></script>

   <script type="text/javascript" src="/metro/assets/chosen-bootstrap/chosen/chosen.jquery.min.js"></script>
   <script type="text/javascript" src="/metro/assets/uniform/jquery.uniform.js"></script>

   <script type="text/javascript" src="/metro/assets/ckeditor/ckeditor.js"></script>
   <script type="text/javascript" src="/metro/assets/jquery-slimscroll/jquery.slimscroll.js"></script>

   <!-- ie8 fixes -->
   <!--[if lt IE 9]>
   <script src="js/excanvas.js"></script>
   <script src="js/respond.js"></script>
   <![endif]-->

   <!--common script for all pages-->
   <script src="/metro/js/common-scripts.js"></script>
   <!-- END JAVASCRIPTS -->
   <script src="/js/scripts.js"></script>
</body>
<!-- END BODY -->
</html>