<script type="text/javascript">
    $.get("/remote/login", function(data){
       $("#login").html(data); 
    },"");
</script>
<header id="header">
	<div class="top_header_block">
		<div class="fix_width">
			<ul class="top_header_nav_block">
				<li><a href="#" class="yellow_text"><span class="star_icon"></span>В избранное</a></li>
				<li>
					<a href="#" class="select_os">PDA</a>
					<a href="#" class="select_os">WAP</a>
					<a href="#" class="select_os active">PC</a>
				</li>
				<li class="relative" id="login">
				</li>
				<li>
					<a href="#" class="active language rus"></a>
					<a href="#" class="language ger"></a>
					<a href="#" class="language eng"></a>
				</li>
			</ul>
		</div>
	</div>
	<div class="middle_header_block">
		<div class="fix_width">
			<a href="/">
				<div class="logo">
				</div>
			</a>
			<div class="header_filter_block">
				<form name="redirectForm" method="post" action="">
					<input type="hidden" value="<?php echo $this->r_performer; ?>" name="r_performer">
					<input type="hidden" value="<?php echo $this->r_type; ?>" name="r_type">
				</form>
				<form action="<?php echo $_SERVER['REQUEST_URI'] ?>" name="filters" method="post">
					<fieldset>
						<ul class="selects_holder">
							<li>
								<label for="city">Город:</label>
								<select class="head_select" name="city" onchange="window.location = $(this).val();">
									<option value="http://vb.arcada-team.ru" <?if ( $this->city == 1 ) :?> selected<?endif?>>Москва</option>
									<option value="http://spbvb.arcada-team.ru" <?if ( $this->city == 2 ) :?> selected<?endif?>>Санкт-Петербург</option>
								</select>
							</li>
							<li>
								<label for="metro">Рядом с метро:</label>
								<select form="redirectForm" class="head_select" name="metro" name="m" 
										onchange="if (this.selectedIndex) {
											document.redirectForm.action = '/' + $(this).val();
											submitForm('redirectForm');
										}">
									<?$i=0; foreach($this->metro_list as $title) : ?>
                        				<option value="<?php echo $this->sections->getUriForMetro($i, $this->city) ?>">
                        						<?if( strpos($_SERVER['REQUEST_URI'], $this->sections->getUriForMetro($i, $this->city)) ):?> selected<?endif?><?=$title?>
                        				</option>
                     				<? $i++; endforeach ?>
								</select>
							</li>
							<li>
								<label for="area">Район:</label>
								<select class="head_select" name="metro" name="d" onchange="if (this.selectedIndex) {submitForm('filters');}">
									<?$i=0;foreach($this->district_list as $title):?>                       
                        				<option value="<?=$i?>"<?if($i==$this->filter['d']):?> selected<?endif?>><?=$title?></option>
                     				<? $i++; endforeach?>
								</select>
							</li>
							<li>
								<label for="phone_number">Номер телефона:</label>
								<div class="header_filter_phone_box">
									<input type="text" class="header_filter_phone" name="tel" value="<?php echo $this->filter['tel'] ?>">
									<input type="submit" class="header_filter_phone_btn">
								</div>
							</li>
							<li>
								<a href="/new-search" class="redbutton header_filter_block_button"><span class="search_icon"></span>Расширенный Поиск</a>
							</li>
						</ul>
					</fieldset>
				</form>
			</div>
		</div>
	</div>
	<div class="bottom_header_block">
		<div class="fix_width">
			<nav id="nav">
				<ul>
					<?php
						$arrays = array("public", "metro", "/", 'index');
						$id = str_replace($arrays, "", $_SERVER['REQUEST_URI']);

						foreach ( $this->menu_items as $item ) {
            		    	if ( $id == substr( $item['uri'],0 ) ) {
            					echo '<li class="active"><a href="' . $SERVER['SERVER_NAME'] . "/" .$item['uri'] . '">' . $item['menu_title'] . '</a></li>';
            		    	} else {
            		       		echo '<li><a href="' . $SERVER['SERVER_NAME'] . "/" .$item['uri'] . '">' . $item['menu_title'] . '</a></li>';
            		    	}
               		 	}
               		 ?>
               		 <!-- <li><a href="#">статьи</a></li> -->
				</ul>
			</nav>
			<!--
				<div class="yellow_shadow"></div>
				<a class="add_anket"><span class="add_anket_icon"></span>Добавить анекту</a>
			-->
		</div>
	</div>
</header>
<script>

</script>