<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title><?if(empty($this->meta['start_title'])):?>PutanaStars<?else:?><?=$this->meta['start_title']?><?endif?></title>
	<?if(!empty($this->meta['start_keys'])):?><meta name="keywords" content="<?=$this->meta['start_keys']?>" /><?endif?>
	<?if(!empty($this->meta['start_desc'])):?><meta name="description" content="<?=$this->meta['start_desc']?>" /><?endif?>

	<!-- styles -->
	<link media="all" rel="stylesheet" type="text/css" href="/css/style.css" />
	<link media="all" rel="stylesheet" type="text/css" href="/css/jquery-ui-1.9.2.custom.css" />
	<link media="all" rel="stylesheet" type="text/css" href="/css/jquery.custom.selectbox.css" />
	<link media="all" rel="stylesheet" type="text/css" href="/css/jquery.multiselect.css" />

	<!-- scripts -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script type="text/javascript">window.jQuery || document.write('<script src="plugins/jquery-1.9.1.min.js"><\/script>')</script>
	<!--[if lt IE 9]>
		<script type="text/javascript" src="plugins/html5.js"></script>
	<![endif]-->
	<script src="/js/scripts.js" type="text/javascript"></script>
	<script type="text/javascript" src="/plugins/jquery-ui-1.9.2.custom.js"></script>
	<script type="text/javascript" src="/plugins/jquery.custom.selectbox.min.js"></script>
	<script type="text/javascript" src="/plugins/jquery.multiselect.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
</head>
<body>
    <div id="container">
        <?=$this->render('header.phtml')?>
        <?=$this->layout()->content?>
        <?=$this->render('footer.phtml')?>
    </div>
</body>
</html>